//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a t gnr par un outil.
//     Version du runtime :4.0.30319.17929
//
//     Les modifications apportes  ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est rgnr.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mstp.BacnetCapture.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement type destine, entre autres,  la consultation des chanes localises.
    /// </summary>
    // Cette classe a t gnre automatiquement par la classe StronglyTypedResourceBuilder
    //  l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis rexcutez ResGen
    // avec l'option /str ou rgnrez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilise par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mstp.BacnetCapture.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la proprit CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources  l'aide de cette classe de ressource fortement type.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }
}
