// This file is automatically generated by the build process.
// Do not edit this file manually.
using System.IO;
namespace Yabe
{
public static class AppConfigConstants
{
public const string AppConfigName = "T3000_config.ini";
public const string AppBacnetName = "T3000 Standard BacNET Tool";
}
}
