// This file is automatically generated by the build process.
// Do not edit this file manually.
using System.IO;
namespace Yabe
{
public static class AppConfigConstants
{
public const string AppConfigName = "OptiMax_config.ini";
public const string AppBacnetName = "OptiMax Standard BacNET Tool";
}
}
