//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFA_psychometric_chart.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WFA_psychometric_chart.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string _10 {
            get {
                return ResourceManager.GetString("_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        public static string _25 {
            get {
                return ResourceManager.GetString("_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40.
        /// </summary>
        public static string _40 {
            get {
                return ResourceManager.GetString("_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        public static string _50 {
            get {
                return ResourceManager.GetString("_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75.
        /// </summary>
        public static string _75 {
            get {
                return ResourceManager.GetString("_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Enthalpy : .
        /// </summary>
        public static string _Enthalpy {
            get {
                return ResourceManager.GetString("_Enthalpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                 Internet Connection Available.
        /// </summary>
        public static string _Internet_Connection_Available {
            get {
                return ResourceManager.GetString("_Internet_Connection_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                 Internet Connection Lost:.
        /// </summary>
        public static string _Internet_Connection_Lost {
            get {
                return ResourceManager.GetString("_Internet_Connection_Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// Please make sure you are connected to internet!.
        /// </summary>
        public static string _Please_make_sure_you_are_conn {
            get {
                return ResourceManager.GetString("_Please_make_sure_you_are_conn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                  start             end 
        ///.
        /// </summary>
        public static string _start_end {
            get {
                return ResourceManager.GetString("_start_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Your chart image will be saved as .
        /// </summary>
        public static string _Your_chart_image_will_be_save {
            get {
                return ResourceManager.GetString("_Your_chart_image_will_be_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after filtering the values of hour = 
        ///.
        /// </summary>
        public static string after_filtering_the_values_of_ {
            get {
                return ResourceManager.GetString("after_filtering_the_values_of_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Information.
        /// </summary>
        public static string Building_Information {
            get {
                return ResourceManager.GetString("Building_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Information :,.
        /// </summary>
        public static string Building_Information0 {
            get {
                return ResourceManager.GetString("Building_Information0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose a path and file name.
        /// </summary>
        public static string Chose_a_path_and_file_name {
            get {
                return ResourceManager.GetString("Chose_a_path_and_file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to country,state,city,street,zip,longitude,latitude,elecation,.
        /// </summary>
        public static string country_state_city_street_zip_ {
            get {
                return ResourceManager.GetString("country_state_city_street_zip_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap d_arrow {
            get {
                object obj = ResourceManager.GetObject("d_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date,hour,minute,temperature,humidity,.
        /// </summary>
        public static string date_hour_minute_temperature_h {
            get {
                return ResourceManager.GetString("date_hour_minute_temperature_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to db insertion : success !.
        /// </summary>
        public static string db_insertion_success {
            get {
                return ResourceManager.GetString("db_insertion_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid refrence humidity value in %.
        /// </summary>
        public static string Enter_a_valid_refrence_humidit {
            get {
                return ResourceManager.GetString("Enter_a_valid_refrence_humidit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid refrence temperature value in degree celcius.
        /// </summary>
        public static string Enter_a_valid_refrence_tempera {
            get {
                return ResourceManager.GetString("Enter_a_valid_refrence_tempera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid temperature value in the input boxex in degree celcius.
        /// </summary>
        public static string Enter_a_valid_temperature_valu {
            get {
                return ResourceManager.GetString("Enter_a_valid_temperature_valu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter city name!.
        /// </summary>
        public static string Enter_city_name {
            get {
                return ResourceManager.GetString("Enter_city_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter country name!.
        /// </summary>
        public static string Enter_country_name {
            get {
                return ResourceManager.GetString("Enter_country_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter ZIP number.
        /// </summary>
        public static string enter_ZIP_number {
            get {
                return ResourceManager.GetString("enter_ZIP_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enthalpy kj/kg dry air.
        /// </summary>
        public static string Enthalpy_kj_kg_dry_air {
            get {
                return ResourceManager.GetString("Enthalpy_kj_kg_dry_air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Detected               .
        /// </summary>
        public static string Error_Detected {
            get {
                return ResourceManager.GetString("Error_Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Ended               .
        /// </summary>
        public static string Error_Ended {
            get {
                return ResourceManager.GetString("Error_Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        public static string error0 {
            get {
                return ResourceManager.GetString("error0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From :.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical Data,.
        /// </summary>
        public static string Historical_Data {
            get {
                return ResourceManager.GetString("Historical_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical Plot.
        /// </summary>
        public static string Historical_Plot {
            get {
                return ResourceManager.GetString("Historical_Plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity(in %).
        /// </summary>
        public static string Humidity_in {
            get {
                return ResourceManager.GetString("Humidity_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this section you select the maximum adjustment factor per day.If the value is deviated you could set the value of max adjustment factore as 0.01 and it will adjust your humidity as  per the 0.01% value. The total current offset is used to show by how much percent the value is updated every day and the total changed from last set..
        /// </summary>
        public static string In_this_section_you_select_the {
            get {
                return ResourceManager.GetString("In_this_section_you_select_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location,distance from building,last update date,temperature,humidity,bar pressure,wind,direction,station name,.
        /// </summary>
        public static string location_distance_from_buildin {
            get {
                return ResourceManager.GetString("location_distance_from_buildin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found in database !.
        /// </summary>
        public static string No_data_found_in_database {
            get {
                return ResourceManager.GetString("No_data_found_in_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid adjustment number eg. 1% would be 0.01.
        /// </summary>
        public static string Please_enter_a_valid_adjustmen {
            get {
                return ResourceManager.GetString("Please_enter_a_valid_adjustmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid dates,Date chosen in &apos;From&apos; section should be smaller than that in &apos;To&apos; section.
        /// </summary>
        public static string Please_enter_a_valid_dates_Dat {
            get {
                return ResourceManager.GetString("Please_enter_a_valid_dates_Dat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number : .
        /// </summary>
        public static string Please_enter_a_valid_number {
            get {
                return ResourceManager.GetString("Please_enter_a_valid_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid zip number.
        /// </summary>
        public static string Please_enter_a_valid_zip_numbe {
            get {
                return ResourceManager.GetString("Please_enter_a_valid_zip_numbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value for adjustment factor.
        /// </summary>
        public static string Please_enter_a_value_for_adjus {
            get {
                return ResourceManager.GetString("Please_enter_a_value_for_adjus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter proper pannel id field.
        /// </summary>
        public static string Please_Enter_proper_pannel_id_ {
            get {
                return ResourceManager.GetString("Please_Enter_proper_pannel_id_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter value between 0-1%.
        /// </summary>
        public static string Please_enter_value_between_0_1 {
            get {
                return ResourceManager.GetString("Please_enter_value_between_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please get and set the current weather data.
        /// </summary>
        public static string Please_get_and_set_the_current {
            get {
                return ResourceManager.GetString("Please_get_and_set_the_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please have a proper value selected from sensor 
        /// Perform get value for humidity from sensor.
        /// </summary>
        public static string Please_have_a_proper_value_sel {
            get {
                return ResourceManager.GetString("Please_have_a_proper_value_sel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please perform the follwing step first.
        /// 1.select a location 
        /// 2.pull stored building data 
        /// 3. get geo value(we need geo value).
        /// </summary>
        public static string Please_perform_the_follwing_st {
            get {
                return ResourceManager.GetString("Please_perform_the_follwing_st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please pull the current weather value first.
        /// </summary>
        public static string Please_pull_the_current_weathe {
            get {
                return ResourceManager.GetString("Please_pull_the_current_weathe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a location .
        /// </summary>
        public static string Please_select_a_location {
            get {
                return ResourceManager.GetString("Please_select_a_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a location first !.
        /// </summary>
        public static string Please_select_a_location_first {
            get {
                return ResourceManager.GetString("Please_select_a_location_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a proper region in the chart.
        /// </summary>
        public static string Please_select_a_proper_region_ {
            get {
                return ResourceManager.GetString("Please_select_a_proper_region_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select a station first..
        /// </summary>
        public static string please_select_a_station_first {
            get {
                return ResourceManager.GetString("please_select_a_station_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a station first to pull data..
        /// </summary>
        public static string Please_select_a_station_first_ {
            get {
                return ResourceManager.GetString("Please_select_a_station_first_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid date (To&gt;From).
        /// </summary>
        public static string Please_select_a_valid_date_To_ {
            get {
                return ResourceManager.GetString("Please_select_a_valid_date_To_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select correct date format[From&lt;To].
        /// </summary>
        public static string Please_select_correct_date_for {
            get {
                return ResourceManager.GetString("Please_select_correct_date_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select one or more hours first.
        /// </summary>
        public static string Please_Select_one_or_more_hour {
            get {
                return ResourceManager.GetString("Please_Select_one_or_more_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set the value from sensor.
        /// </summary>
        public static string Please_set_the_value_from_sens {
            get {
                return ResourceManager.GetString("Please_set_the_value_from_sens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pulling....
        /// </summary>
        public static string pulling {
            get {
                return ResourceManager.GetString("pulling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Building.
        /// </summary>
        public static string Refresh_Building {
            get {
                return ResourceManager.GetString("Refresh_Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Graph.
        /// </summary>
        public static string Refresh_Graph {
            get {
                return ResourceManager.GetString("Refresh_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click to insert a new node. single click to select the items you want to move and hover over where you want to put it and click again it will fix there. If you want to make x-axis constant wile moving the node move the node by constantly clicking the Alt key.If you want to make y-axis constant while moving keep pressing the Shift key and move. You can insert different color nodes based on the color selected..
        /// </summary>
        public static string Right_click_to_insert_a_new_no {
            get {
                return ResourceManager.GetString("Right_click_to_insert_a_new_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Excel file to.
        /// </summary>
        public static string Save_Excel_file_to {
            get {
                return ResourceManager.GetString("Save_Excel_file_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string Select_language {
            get {
                return ResourceManager.GetString("Select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select station name :.
        /// </summary>
        public static string Select_station_name {
            get {
                return ResourceManager.GetString("Select_station_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Heat Map.
        /// </summary>
        public static string Show_Heat_Map {
            get {
                return ResourceManager.GetString("Show_Heat_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Information :.
        /// </summary>
        public static string Station_Information {
            get {
                return ResourceManager.GetString("Station_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status : Updating data....
        /// </summary>
        public static string Status_Updating_data {
            get {
                return ResourceManager.GetString("Status_Updating_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success final !.
        /// </summary>
        public static string Success_final {
            get {
                return ResourceManager.GetString("Success_final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success !.
        /// </summary>
        public static string Success0 {
            get {
                return ResourceManager.GetString("Success0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language change will take full effect the next time you start the program..
        /// </summary>
        public static string The_language_change_will_take_ {
            get {
                return ResourceManager.GetString("The_language_change_will_take_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings have been saved.
        ///.
        /// </summary>
        public static string The_settings_have_been_saved {
            get {
                return ResourceManager.GetString("The_settings_have_been_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Status                  Time                            Error Status.
        /// </summary>
        public static string Time_Status_Time_Error_Status {
            get {
                return ResourceManager.GetString("Time_Status_Time_Error_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To :.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap u_arrow {
            get {
                object obj = ResourceManager.GetObject("u_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value inserted successfully!.
        /// </summary>
        public static string value_inserted_successfully {
            get {
                return ResourceManager.GetString("value_inserted_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wet bulb temp.
        /// </summary>
        public static string Wet_bulb_temp {
            get {
                return ResourceManager.GetString("Wet_bulb_temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file will be saved as .
        /// </summary>
        public static string Your_file_will_be_saved_as {
            get {
                return ResourceManager.GetString("Your_file_will_be_saved_as", resourceCulture);
            }
        }
    }
}
