// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "msflexgrid1.h"

/////////////////////////////////////////////////////////////////////////////
// CMsflexgrid1

IMPLEMENT_DYNCREATE(CMsflexgrid1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CMsflexgrid1 properties

/////////////////////////////////////////////////////////////////////////////
// CMsflexgrid1 operations
