//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFA_psychometric_chart.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WFA_psychometric_chart.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string _10 {
            get {
                return ResourceManager.GetString("_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        internal static string _25 {
            get {
                return ResourceManager.GetString("_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40.
        /// </summary>
        internal static string _40 {
            get {
                return ResourceManager.GetString("_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        internal static string _50 {
            get {
                return ResourceManager.GetString("_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75.
        /// </summary>
        internal static string _75 {
            get {
                return ResourceManager.GetString("_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after filtering the values of hour = 
        ///.
        /// </summary>
        internal static string after_filtering_the_values_of_ {
            get {
                return ResourceManager.GetString("after_filtering_the_values_of_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Information.
        /// </summary>
        internal static string Building_Information {
            get {
                return ResourceManager.GetString("Building_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Information :,.
        /// </summary>
        internal static string Building_Information0 {
            get {
                return ResourceManager.GetString("Building_Information0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose a path and file name.
        /// </summary>
        internal static string Chose_a_path_and_file_name {
            get {
                return ResourceManager.GetString("Chose_a_path_and_file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to country,state,city,street,zip,longitude,latitude,elecation,.
        /// </summary>
        internal static string country_state_city_street_zip_ {
            get {
                return ResourceManager.GetString("country_state_city_street_zip_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d_arrow {
            get {
                object obj = ResourceManager.GetObject("d_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date,hour,minute,temperature,humidity,.
        /// </summary>
        internal static string date_hour_minute_temperature_h {
            get {
                return ResourceManager.GetString("date_hour_minute_temperature_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid refrence humidity value in %.
        /// </summary>
        internal static string Enter_a_valid_refrence_humidit {
            get {
                return ResourceManager.GetString("Enter_a_valid_refrence_humidit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid refrence temperature value in degree celcius.
        /// </summary>
        internal static string Enter_a_valid_refrence_tempera {
            get {
                return ResourceManager.GetString("Enter_a_valid_refrence_tempera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid temperature value in the input boxex in degree celcius.
        /// </summary>
        internal static string Enter_a_valid_temperature_valu {
            get {
                return ResourceManager.GetString("Enter_a_valid_temperature_valu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical Data,.
        /// </summary>
        internal static string Historical_Data {
            get {
                return ResourceManager.GetString("Historical_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity(in %).
        /// </summary>
        internal static string Humidity_in {
            get {
                return ResourceManager.GetString("Humidity_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location,distance from building,last update date,temperature,humidity,bar pressure,wind,direction,station name,.
        /// </summary>
        internal static string location_distance_from_buildin {
            get {
                return ResourceManager.GetString("location_distance_from_buildin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid dates,Date chosen in &apos;From&apos; section should be smaller than that in &apos;To&apos; section.
        /// </summary>
        internal static string Please_enter_a_valid_dates_Dat {
            get {
                return ResourceManager.GetString("Please_enter_a_valid_dates_Dat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid zip number.
        /// </summary>
        internal static string Please_enter_a_valid_zip_numbe {
            get {
                return ResourceManager.GetString("Please_enter_a_valid_zip_numbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select one or more hours first.
        /// </summary>
        internal static string Please_Select_one_or_more_hour {
            get {
                return ResourceManager.GetString("Please_Select_one_or_more_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click to insert a new node. single click to select the items you want to move and hover over where you want to put it and click again it will fix there. If you want to make x-axis constant wile moving the node move the node by constantly clicking the Alt key.If you want to make y-axis constant while moving keep pressing the Shift key and move. You can insert different color nodes based on the color selected..
        /// </summary>
        internal static string Right_click_to_insert_a_new_no {
            get {
                return ResourceManager.GetString("Right_click_to_insert_a_new_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        internal static string Select_language {
            get {
                return ResourceManager.GetString("Select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Information :.
        /// </summary>
        internal static string Station_Information {
            get {
                return ResourceManager.GetString("Station_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success !.
        /// </summary>
        internal static string Success0 {
            get {
                return ResourceManager.GetString("Success0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language change will take full effect the next time you start the program..
        /// </summary>
        internal static string The_language_change_will_take_ {
            get {
                return ResourceManager.GetString("The_language_change_will_take_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings have been saved.
        ///.
        /// </summary>
        internal static string The_settings_have_been_saved {
            get {
                return ResourceManager.GetString("The_settings_have_been_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap u_arrow {
            get {
                object obj = ResourceManager.GetObject("u_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file will be saved as .
        /// </summary>
        internal static string Your_file_will_be_saved_as {
            get {
                return ResourceManager.GetString("Your_file_will_be_saved_as", resourceCulture);
            }
        }
    }
}
