// CO2NetView.cpp : implementation file
//

#include "stdafx.h"
#include "T3000.h"
#include "CO2NetView.h"
#include "MainFrm.h"


// CCO2NetView

IMPLEMENT_DYNCREATE(CCO2NetView, CFormView)

CCO2NetView::CCO2NetView()
	: CFormView(CCO2NetView::IDD)
{
Flag_Reg=FALSE;
}

CCO2NetView::~CCO2NetView()
{
}

void CCO2NetView::DoDataExchange(CDataExchange* pDX)
{
    CFormView::DoDataExchange(pDX);
    DDX_Control(pDX, IDC_ID_CO2_EDIT, m_edit_IDAddress);
    DDX_Control(pDX, IDC_SERIALNUM_CO2_EDIT, m_edit_SN);
    DDX_Control(pDX, IDC_FIRMWARV_CO2_EDIT, m_Edit_FVevsion);
    DDX_Control(pDX, IDC_HARDWAREV_CO2_EDIT, m_Edit_HardVer);
    DDX_Control(pDX, IDC_CO2_BRAUDRATECOMBO, m_Combox_braudrate);
    DDX_Control(pDX, IDC_EDIT_CO2_HUMIDITY, m_Edit_RHum);
    DDX_Control(pDX, IDC_RADIO_ALARM_MANUAL, m_AlarmSetting_M);
    DDX_Control(pDX, IDC_RADIO_ALARM_AUTO, m_AlarmSetting_Auto);
    DDX_Control(pDX, IDC_CO2_ALARM_STATE, m_Combox_CO2State);

    DDX_Control(pDX, IDC_EDIT_CO2_PASSWOR, m_Edit_Password);
    DDX_Control(pDX, IDC_COMBO_IPModel, m_Combox_IpModel);
    DDX_Control(pDX, IDC_MAC_ADDRESS, m_Edit_MACAddress);
    DDX_Control(pDX, IDC_IPADDRESS_IP, m_IPCtrl_IpAddress);
    DDX_Control(pDX, IDC_IPADDRESS_Gateway, m_IpCtrl_Gateway);
    DDX_Control(pDX, IDC_IPADDRESS_Subnet, m_IpCtrl_Subnet);
    DDX_Control(pDX, IDC_EDIT_ListeningPort, m_Edit_Port);
    DDX_Control(pDX, IDC_EDIT_EXTERNAL_TEMP, m_Edit_External_Temp);
    DDX_Control(pDX, IDC_EDIT_INTERNAL_TEMP, m_Internal_Temp);
    DDX_Control(pDX, IDC_CO2_TEMP_UNIT, m_Combox_TempUnit);
    DDX_Control(pDX, IDC_COMBO_CO2_SENSOR_SEL, m_Edit_SensorSelect);
    DDX_Control(pDX, IDC_CO2_CALIBRATING_OFFSET, m_Edit_Calibrate_Offset);
    DDX_Control(pDX, IDC_CO2_ALARM_SETPOINT, m_Edit_Alarm_Setpoint);
    DDX_Control(pDX, IDC_CO2_PREPARE_ALARM_SETPOINT, m_Edit_PreAlarm_Setpoint);
    DDX_Control(pDX, IDC_CO2_ALARM_ON_TIME, m_Edit_AlarmOn);
    DDX_Control(pDX, IDC_CO2_ALARM_OFF_TIME, m_Edit_AlarmOff);
    DDX_Control(pDX, IDC_EDIT_CO2_BLOCK_TIME, m_Edit_MenuBlockTimes);
    DDX_Control(pDX, IDC_EDIT_CO2_BACKLIGHT_TIME, m_Edit_BacklightTime);
    DDX_Control(pDX, IDC_RADIO_HUMIDITY_HEAT_ENABLE, m_HeatingHumiditySensor_Enable);
    DDX_Control(pDX, IDC_RADIO_HUMIDITY_HEAT_DISABLE, m_HeatingHumiditySensor_Disable);
    DDX_Control(pDX, IDC_ENABLE_PASSWORD, m_Check_Enable_Password);
    DDX_Control(pDX, IDC_MSFLEXGRID1, m_msflexgrid);
}

BEGIN_MESSAGE_MAP(CCO2NetView, CFormView)
    ON_CBN_SELCHANGE(IDC_CO2_TEMP_UNIT, &CCO2NetView::OnCbnSelchangeCo2TempUnit)
    ON_BN_CLICKED(IDC_BTN_CO2_CLEAR_CAL, &CCO2NetView::OnBnClickedBtnCo2ClearCal)
END_MESSAGE_MAP()


// CCO2NetView diagnostics
void CCO2NetView::OnInitialUpdate()
{
    CFormView::OnInitialUpdate();
     
}
#ifdef _DEBUG
void CCO2NetView::AssertValid() const
{
	CFormView::AssertValid();
}

#ifndef _WIN32_WCE
void CCO2NetView::Dump(CDumpContext& dc) const
{
	CFormView::Dump(dc);
}
#endif
#endif //_DEBUG

void CCO2NetView::Fresh(){
if (!Flag_Reg)
{
Initial_Registerlist();
Flag_Reg=TRUE;
}
for(int i=0;i<27;i++){
Read_Multi(g_tstat_id,&product_register_value[i*100],i*100,100);
}
Initial_Window();
}
void CCO2NetView::Initial_Registerlist(){
    CO2_NET_MODBUS_SERIALNUMBER_LOWORD	=	0	;
    CO2_NET_MODBUS_SERIALNUMBER_HIWORD	=	2	;
    CO2_NET_MODBUS_SOFTWARE_VERSION_LO 	=	4	;
    CO2_NET_MODBUS_SOFTWARE_VERSION_HI 	=	5	;
    CO2_NET_MODBUS_ADDRESS 	=	6	;
    CO2_NET_MODBUS_PRODUCT_MODEL 	=	7	;
    CO2_NET_MODBUS_HARDWARE_REV	=	8	;
    CO2_NET_MODBUS_PIC_REV	=	9	;
    CO2_NET_MODBUS_ADDRESS_PLUG_N_PLAY	=	10	;
    CO2_NET_MODBUS_TIME_ZONE	=	11	;
    CO2_NET_MODBUS_BAUDRATE 	=	12	;
    CO2_NET_MODBUS_DAYLIGHT_ENABLE	=	13	;
    CO2_NET_MODBUS_BOOTLOADER_VERSION	=	14	;
    CO2_NET_MODBUS_RESET_FLASH	=	15	;
    CO2_NET_MODBUS_UPDATE_STATUS 	=	16	;
    CO2_NET_MODBUS_INIT_WR_TIME	=	17	;
    CO2_NET_MODBUS_TIME_SERVER_SELECT 	=	22	;
    CO2_NET_MODBUS_SERINALNUMBER_WRITE_FLAG	=	25	;
    CO2_NET_MODBUS_REFRESH_STATUS 	=	90	;
    CO2_NET_MODBUS_REFRESH_FLASH	=	91	;
    CO2_NET_MODBUS_REFRESH_FLASH_FREQ 	=	92	;
    CO2_NET_MODBUS_MAC_ADDRESS_CHANGE_ENABLE	=	93	;
    CO2_NET_MODBUS_REFRESH_FLASH_TIMER	=	94	;
    CO2_NET_MODBUS_MAC_ADDRESS_START	=	100	;
    CO2_NET_MODBUS_IP_MODE	=	106	;
    CO2_NET_MODBUS_IP_ADDRESS_START	=	107	;
    CO2_NET_MODBUS_SUBNET_MASK_ADDRESS_START	=	111	;
    CO2_NET_MODBUS_GATEWAY_ADDRESS_START	=	115	;
    CO2_NET_MODBUS_TCP_SERVER_ENABLE 	=	119	;
    CO2_NET_MODBUS_LISTEN_PORT_AT_TCP_SERVER_MODE_START	=	120	;
    CO2_NET_MODBUS_IP_MODE_GHOST	=	121	;
    CO2_NET_MODBUS_IP_ADDRESS_GHOST_START	=	122	;
    CO2_NET_MODBUS_SUBNET_MASK_ADDRESS_GHOST_START	=	126	;
    CO2_NET_MODBUS_GATEWAY_ADDRESS_GHOST_START	=	130	;
    CO2_NET_MODBUS_TCP_SERVER_ENABLE_GHOST 	=	134	;
    CO2_NET_MODBUS_LISTEN_PORT_AT_TCP_SERVER_MODE_GHOST_START 	=	135	;
    CO2_NET_MODBUS_ENABLE_GHOST	=	136	;
    CO2_NET_MODBUS_SCAN_COMMAND	=	172	;
    CO2_NET_MODBUS_SUBNET_TYPE 	=	173	;
    CO2_NET_MODBUS_NTP_COMMAND	=	174	;
    CO2_NET_MODBUS_TIME_SERVER0_IP_START	=	175	;
    CO2_NET_MODBUS_TIME_SERVER1_IP_START	=	176	;
    CO2_NET_MODBUS_TIME_SERVER2_IP_START	=	183	;
    CO2_NET_MODBUS_TIME_SERVER3_IP_START	=	187	;
    CO2_NET_MODBUS_TIME_SERVER4_IP_START	=	191	;
    CO2_NET_MODBUS_TIME_SERVER5_IP_START	=	195	;
    CO2_NET_MODBUS_TIME_SYNC_RESULT	=	199	;
    CO2_NET_MODBUS_TEMPERATURE_SENSOR_SELECT	=	200	;
    CO2_NET_MODBUS_TEMPERATURE_DEGREE_C_OR_F	=	201	;
    CO2_NET_MODBUS_INTERNAL_TEMPERATURE_CELSIUS	=	202	;
    CO2_NET_MODBUS_INTERNAL_TEMPERATURE_FAHRENHEIT	=	203	;
    CO2_NET_MODBUS_EXTERNAL_TEMPERATURE_CELSIUS	=	204	;
    CO2_NET_MODBUS_EXTERNAL_TEMPERATURE_FAHRENHEIT	=	205	;
    CO2_NET_MODBUS_TEMPERATURE_OFFSET_INTERNAL	=	206	;
    CO2_NET_MODBUS_HUMIDITY	=	207	;
    CO2_NET_MODBUS_HUMIDITY_FREQUENCY	=	208	;
    CO2_NET_MODBUS_HUMIDITY_CALIBRATION_TABLE_COUNTER	=	209	;
    CO2_NET_MODBUS_CO2_INTERNAL_EXIST	=	210	;
    CO2_NET_MODBUS_CO2_INTERNAL	=	211	;
    CO2_NET_MODBUS_CO2_INTERNAL_OFFSET	=	212	;
    CO2_NET_MODBUS_CO2_INTERNAL_PREALARM_SETPOINT	=	213	;
    CO2_NET_MODBUS_CO2_INTERNAL_ALARM_SETPOINT	=	214	;
    CO2_NET_MODBUS_CO2_EXTERNAL_START	=	215	;
    CO2_NET_MODBUS_CO2_EXTERANL_END	=	468	;
    CO2_NET_MODBUS_CO2_EXTERNAL_OFFSET_START	=	469	;
    CO2_NET_MODBUS_CO2_EXTERNAL_OFFSET_END	=	722	;
    CO2_NET_MODBUS_CO2_EXTERNAL_PREALARM_SETPOINT_START	=	723	;
    CO2_NET_MODBUS_CO2_EXTERNAL_PREALARM_SETPOINT_END	=	976	;
    CO2_NET_MODBUS_CO2_EXTERNAL_ALARM_SETPOINT_START 	=	977	;
    CO2_NET_MODBUS_CO2_EXTERNAL_ALARM_SETPOINT_END	=	1230	;
    CO2_NET_MODBUS_CO2_SLOPE_DETECT_VALUE	=	1231	;
    CO2_NET_MODBUS_CO2_FILTER	=	1232	;
    CO2_NET_MODBUS_PASSWORD_ENABLE	=	1233	;
    CO2_NET_MODBUS_USER_PASSWORD0 	=	1234	;
    CO2_NET_MODBUS_USER_PASSWORD1	=	1235	;
    CO2_NET_MODBUS_USER_PASSWORD2	=	1236	;
    CO2_NET_MODBUS_USER_PASSWORD3	=	1237	;
    CO2_NET_MODBUS_RTC_CENTURY	=	1238	;
    CO2_NET_MODBUS_RTC_YEAR	=	1239	;
    CO2_NET_MODBUS_RTC_MONTH	=	1240	;
    CO2_NET_MODBUS_RTC_DAY	=	1241	;
    CO2_NET_MODBUS_RTC_WEEK	=	1242	;
    CO2_NET_MODBUS_RTC_HOUR	=	1243	;
    CO2_NET_MODBUS_RTC_MINUTE	=	1244	;
    CO2_NET_MODBUS_RTC_SECOND	=	1245	;
    CO2_NET_MODBUS_ALARM_AUTO_MANUAL	=	1246	;
    CO2_NET_MODBUS_PRE_ALARM_SETTING_ON_TIME	=	1247	;
    CO2_NET_MODBUS_PRE_ALARM_SETTING_OFF_TIME	=	1248	;
    CO2_NET_MODBUS_ALARM_DELAY_TIME	=	1249	;
    CO2_NET_MODBUS_OUTPUT_AUTO_MANUAL	=	1250	;
    CO2_NET_MODBUS_OUTPUT_MANUAL_VALUE_TEM	=	1251	;
    CO2_NET_MODBUS_OUTPUT_MANUAL_VALUE_HUM	=	1252	;
    CO2_NET_MODBUS_OUTPUT_MANUAL_VALUE_CO2	=	1253	;
    CO2_NET_MODBUS_OUTPUT_MODE	=	1254	;
    CO2_NET_MODBUS_OUTPUT_RANGE_MIN_TEM	=	1255	;
    CO2_NET_MODBUS_OUTPUT_RANGE_MAX_TEM	=	1256	;
    CO2_NET_MODBUS_OUTPUT_RANGE_MIN_HUM	=	1257	;
    CO2_NET_MODBUS_OUTPUT_RANGE_MAX_HUM	=	1258	;
    CO2_NET_MODBUS_OUTPUT_RANGE_MIN_CO2	=	1259	;
    CO2_NET_MODBUS_OUTPUT_RANGE_MAX_CO2	=	1260	;
    CO2_NET_MODBUS_MENU_BLOCK_SECONDS	=	1261	;
    CO2_NET_MODBUS_BACKLIGHT_KEEP_SECONDS	=	1262	;
    CO2_NET_MODBUS_EXTERNAL_NODES_PLUG_AND_PLAY 	=	1263	;
    CO2_NET_MODBUS_SCAN_DB_CTR	=	1264	;
    CO2_NET_MODBUS_RESET_SCAN_DB	=	1265	;
    CO2_NET_MODBUS_SCAN_START	=	1266	;
    CO2_NET_MODBUS_SCAN_END 	=	2535	;
    CO2_NET_MODBUS_GET_NODES_PARA_START 	=	2536	;
    CO2_NET_MODBUS_GET_NODES_PARA_END 	=	2568	;
    CO2_NET_MODBUS_SCAN_OCCUPY_START	=	2600	;
    CO2_NET_MODBUS_SCAN_OCCUPY_END	=	2632	;
    CO2_NET_MODBUS_SCAN_ONLINE_START	=	10000	;
    CO2_NET_MODBUS_SCAN_ONLINE_END	=	10001	;
    CO2_NET_MODBUS_IDLE_ID	=	10002	;
    CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_READ	=	10003	;
    CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM0	=	10004	;
    CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ0	=	10005	;
    CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM1	=	10006	;
    CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ1	=	10007	;
    CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM2	=	10008	;
    CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ2	=	10009	;
    CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM3	=	10010	;
    CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ3	=	10011	;
    CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM4	=	10012	;
    CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ4	=	10013	;
    CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM5	=	10014	;
    CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ5	=	10015	;
    CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM6	=	10016	;
    CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ6	=	10017	;
    CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM7	=	10018	;
    CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ7	=	10019	;
    CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM8	=	10020	;
    CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ8	=	10021	;
    CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM9	=	10022	;
    CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ9	=	10023	;

}
void CCO2NetView::Initial_Window(){
CString strTemp;
int IntTemp;
IntTemp=product_register_value[CO2_NET_MODBUS_ADDRESS];
strTemp.Format(_T("%d"),IntTemp);
m_edit_IDAddress.SetWindowText(strTemp);
IntTemp=product_register_value[CO2_NET_MODBUS_SERIALNUMBER_LOWORD]+product_register_value[CO2_NET_MODBUS_SERIALNUMBER_LOWORD+1]*255+
        product_register_value[CO2_NET_MODBUS_SERIALNUMBER_HIWORD]*255*255+product_register_value[CO2_NET_MODBUS_SERIALNUMBER_HIWORD+1]*255*255*255;
strTemp.Format(_T("%d"),IntTemp);
m_edit_SN.SetWindowText(strTemp);
strTemp.Format(_T("%u.%u"),product_register_value[CO2_NET_MODBUS_SOFTWARE_VERSION_HI],product_register_value[CO2_NET_MODBUS_SOFTWARE_VERSION_LO]);
m_Edit_FVevsion.SetWindowText(strTemp);
strTemp.Format(_T("%u"),product_register_value[CO2_NET_MODBUS_HARDWARE_REV]);
m_Edit_HardVer.SetWindowText(strTemp);
m_Combox_braudrate.ResetContent();
m_Combox_braudrate.AddString(_T("9600"));
m_Combox_braudrate.AddString(_T("19200"));
m_Combox_braudrate.SetCurSel(product_register_value[CO2_NET_MODBUS_BAUDRATE]);
float fTemp;
fTemp = (float)product_register_value[CO2_NET_MODBUS_HUMIDITY]/10;
if(fTemp>100)
{
    (CEdit *)GetDlgItem(IDC_EDIT_CO2_HUMIDITY)->EnableWindow(FALSE);
    //m_humidity_value = 0;
    m_Edit_RHum.SetWindowText(_T("0"));
}
else
{
    strTemp.Format(_T("%0.1f"),fTemp);
    m_Edit_RHum.SetWindowText(strTemp);
    (CEdit *)GetDlgItem(IDC_EDIT_CO2_HUMIDITY)->EnableWindow(TRUE);
}
}
// CCO2NetView message handlers
void CCO2NetView::OnCbnSelchangeCo2TempUnit()
{
     
}
#include "Table_Tamplete.h"

void CCO2NetView::OnBnClickedBtnCo2ClearCal()
{
     CTable_Tamplete dlg;
    // dlg=new CTable_Tamplete;
   //  dlg->SetWindowText(_T("External Calibration List"));
     dlg.DoModal();
}