#pragma once
#include "afxwin.h"
#include "afxcmn.h"
#include "msflexgrid1.h"
#include "afxdtctl.h"
#include "CM5/ListCtrlEx.h"
#include "CM5\MyOwnListCtrl.h"
 
#define	PRODUCT_ID					32

#define	FLASH_OFFSET				0x70000
//#define	FLASH_END					0xffff

#define TOTAL_EE_PARAMETERS			208

#define	ORIGINALADDRESSVALUE		200

#define	MAX_EXT_CO2					254
#define	SCAN_DB_SIZE				5
// CCO2NetView form view
/*
typedef enum
{
    EEP_SERIALNUMBER_LOWORD = 0,             
    EEP_SERIALNUMBER_HIWORD = 2,
    EEP_SOFTWARE_VERSION_LO = 4,
    EEP_SOFTWARE_VERSION_HI = 5,
    EEP_ADDRESS = 6,
    EEP_PRODUCT_MODEL,
    EEP_HARDWARE_REV,
    EEP_INIT_WR_TIME, 			//Erase weekly routine time block if value of this register is not 0x55
    EEP_ADDRESS_PLUG_N_PLAY = 10,
    EEP_TIME_ZONE,
    EEP_BAUDRATE,	 
    EEP_DAYLIGHT_ENABLE,
    EEP_DAYLIGHT_STATUS,
    EEP_RESET_FLASH = 15,

    // registers needed for updating status
    EEP_UPDATE_STATUS = 16,

    EEP_TIME_SERVER_SELECT = 22,

    EEP_REFRESH_FLASH_FREQ,
    EEP_SERINALNUMBER_WRITE_FLAG = EEP_REFRESH_FLASH_FREQ + 2,

    EEP_MAC_ADDRESS_START = 100,//6
    EEP_IP_MODE = 106,
    EEP_IP_ADDRESS_START = 107,//4
    EEP_SUBNET_MASK_ADDRESS_START = 111,//4
    EEP_GATEWAY_ADDRESS = 115,//4
    EEP_TCP_SERVER_ENABLE = 119,
    EEP_LISTEN_PORT_AT_TCP_SERVER_MODE_START = 120,//2

    EEP_SCAN_COMMAND = 172,
    EEP_SUBNET_TYPE = 173,
    EEP_NTP_COMMAND = 174,
    EEP_TIME_SERVER0_IP_START = 175,//4bytes
    EEP_TIME_SERVER1_IP_START = 179,//4bytes
    EEP_TIME_SERVER2_IP_START = 183,//4bytes
    EEP_TIME_SERVER3_IP_START = 187,//4bytes
    EEP_TIME_SERVER4_IP_START = 191,//4bytes
    EEP_TIME_SERVER5_IP_START = 195,//4bytes
    EEP_TIME_SYNC_RESULT = 199,

} EEP_LOCATION;
typedef enum
{
CO2_NET_MODBUS_SERIALNUMBER_LOWORD	=	0	;
CO2_NET_MODBUS_SERIALNUMBER_HIWORD	=	2	;
CO2_NET_MODBUS_SOFTWARE_VERSION_LO 	=	4	;
CO2_NET_MODBUS_SOFTWARE_VERSION_HI 	=	5	;
CO2_NET_MODBUS_ADDRESS 	=	6	;
CO2_NET_MODBUS_PRODUCT_MODEL 	=	7	;
CO2_NET_MODBUS_HARDWARE_REV	=	8	;
CO2_NET_MODBUS_PIC_REV	=	9	;
CO2_NET_MODBUS_ADDRESS_PLUG_N_PLAY	=	10	;
CO2_NET_MODBUS_TIME_ZONE	=	11	;
CO2_NET_MODBUS_BAUDRATE 	=	12	;
CO2_NET_MODBUS_DAYLIGHT_ENABLE	=	13	;
CO2_NET_MODBUS_BOOTLOADER_VERSION	=	14	;
CO2_NET_MODBUS_RESET_FLASH	=	15	;
CO2_NET_MODBUS_UPDATE_STATUS 	=	16	;
CO2_NET_MODBUS_INIT_WR_TIME	=	17	;
CO2_NET_MODBUS_TIME_SERVER_SELECT 	=	22	;
CO2_NET_MODBUS_SERINALNUMBER_WRITE_FLAG	=	25	;
CO2_NET_MODBUS_REFRESH_STATUS 	=	90	;
CO2_NET_MODBUS_REFRESH_FLASH	=	91	;
CO2_NET_MODBUS_REFRESH_FLASH_FREQ 	=	92	;
CO2_NET_MODBUS_MAC_ADDRESS_CHANGE_ENABLE	=	93	;
CO2_NET_MODBUS_REFRESH_FLASH_TIMER	=	94	;

CO2_NET_MODBUS_MAC_ADDRESS_START	=	100	;
CO2_NET_MODBUS_IP_MODE	=	106	;
CO2_NET_MODBUS_IP_ADDRESS_START	=	107	;
CO2_NET_MODBUS_SUBNET_MASK_ADDRESS_START	=	111	;
CO2_NET_MODBUS_GATEWAY_ADDRESS_START	=	115	;
CO2_NET_MODBUS_TCP_SERVER_ENABLE 	=	119	;
CO2_NET_MODBUS_LISTEN_PORT_AT_TCP_SERVER_MODE_START	=	120	;

CO2_NET_MODBUS_IP_MODE_GHOST	=	121	;
CO2_NET_MODBUS_IP_ADDRESS_GHOST_START	=	122	;
CO2_NET_MODBUS_SUBNET_MASK_ADDRESS_GHOST_START	=	126	;
CO2_NET_MODBUS_GATEWAY_ADDRESS_GHOST_START	=	130	;
CO2_NET_MODBUS_TCP_SERVER_ENABLE_GHOST 	=	134	;
CO2_NET_MODBUS_LISTEN_PORT_AT_TCP_SERVER_MODE_GHOST_START 	=	135	;
CO2_NET_MODBUS_ENABLE_GHOST	=	136	;

CO2_NET_MODBUS_SCAN_COMMAND	=	172	;
CO2_NET_MODBUS_SUBNET_TYPE 	=	173	;
CO2_NET_MODBUS_NTP_COMMAND	=	174	;

CO2_NET_MODBUS_TIME_SERVER0_IP_START	=	175	;
CO2_NET_MODBUS_TIME_SERVER1_IP_START	=	176	;
CO2_NET_MODBUS_TIME_SERVER2_IP_START	=	183	;
CO2_NET_MODBUS_TIME_SERVER3_IP_START	=	187	;
CO2_NET_MODBUS_TIME_SERVER4_IP_START	=	191	;
CO2_NET_MODBUS_TIME_SERVER5_IP_START	=	195	;
CO2_NET_MODBUS_TIME_SYNC_RESULT	=	199	;
//-----------------------------------------------------------
CO2_NET_MODBUS_TEMPERATURE_SENSOR_SELECT	=	200	;

CO2_NET_MODBUS_TEMPERATURE_DEGREE_C_OR_F	=	201	;

CO2_NET_MODBUS_INTERNAL_TEMPERATURE_CELSIUS	=	202	;
CO2_NET_MODBUS_INTERNAL_TEMPERATURE_FAHRENHEIT	=	203	;

CO2_NET_MODBUS_EXTERNAL_TEMPERATURE_CELSIUS	=	204	;
CO2_NET_MODBUS_EXTERNAL_TEMPERATURE_FAHRENHEIT	=	205	;
CO2_NET_MODBUS_TEMPERATURE_OFFSET_INTERNAL	=	206	;
//-----------------------------------------------------------
CO2_NET_MODBUS_HUMIDITY	=	207	;
CO2_NET_MODBUS_HUMIDITY_FREQUENCY	=	208	;
CO2_NET_MODBUS_HUMIDITY_CALIBRATION_TABLE_COUNTER	=	209	;
//--------------------------------------------------------
CO2_NET_MODBUS_CO2_INTERNAL_EXIST	=	210	;
CO2_NET_MODBUS_CO2_INTERNAL	=	211	;
CO2_NET_MODBUS_CO2_INTERNAL_OFFSET	=	212	;
CO2_NET_MODBUS_CO2_INTERNAL_PREALARM_SETPOINT	=	213	;
CO2_NET_MODBUS_CO2_INTERNAL_ALARM_SETPOINT	=	214	;

CO2_NET_MODBUS_CO2_EXTERNAL_START	=	215	;
CO2_NET_MODBUS_CO2_EXTERANL_END	=	468	;
CO2_NET_MODBUS_CO2_EXTERNAL_OFFSET_START	=	469	;
CO2_NET_MODBUS_CO2_EXTERNAL_OFFSET_END	=	722	;
CO2_NET_MODBUS_CO2_EXTERNAL_PREALARM_SETPOINT_START	=	723	;
CO2_NET_MODBUS_CO2_EXTERNAL_PREALARM_SETPOINT_END	=	976	;
CO2_NET_MODBUS_CO2_EXTERNAL_ALARM_SETPOINT_START 	=	977	;
CO2_NET_MODBUS_CO2_EXTERNAL_ALARM_SETPOINT_END	=	1230	;


CO2_NET_MODBUS_CO2_SLOPE_DETECT_VALUE	=	1231;
MODBUS_CO2_FILTER	=	1232	;

CO2_NET_MODBUS_PASSWORD_ENABLE	=	1233	;
CO2_NET_MODBUS_USER_PASSWORD0 	=	1234	;
CO2_NET_MODBUS_USER_PASSWORD1	=	1235	;
CO2_NET_MODBUS_USER_PASSWORD2	=	1236	;
CO2_NET_MODBUS_USER_PASSWORD3	=	1237	;

CO2_NET_MODBUS_RTC_CENTURY	=	1238	;
CO2_NET_MODBUS_RTC_YEAR	=	1239	;
CO2_NET_MODBUS_RTC_MONTH	=	1240	;
CO2_NET_MODBUS_RTC_DAY	=	1241	;
CO2_NET_MODBUS_RTC_WEEK	=	1242	;
CO2_NET_MODBUS_RTC_HOUR	=	1243	;
CO2_NET_MODBUS_RTC_MINUTE	=	1244	;
CO2_NET_MODBUS_RTC_SECOND	=	1245	;

CO2_NET_MODBUS_ALARM_AUTO_MANUAL	=	1246	;
CO2_NET_MODBUS_PRE_ALARM_SETTING_ON_TIME	=	1247	;
CO2_NET_MODBUS_PRE_ALARM_SETTING_OFF_TIME	=	1248	;
CO2_NET_MODBUS_ALARM_DELAY_TIME	=	1249	;

CO2_NET_MODBUS_OUTPUT_AUTO_MANUAL	=	1250	;
CO2_NET_MODBUS_OUTPUT_MANUAL_VALUE_TEM	=	1251	;
CO2_NET_MODBUS_OUTPUT_MANUAL_VALUE_HUM	=	1252	;
CO2_NET_MODBUS_OUTPUT_MANUAL_VALUE_CO2	=	1253	;
CO2_NET_MODBUS_OUTPUT_MODE	=	1254	;
CO2_NET_MODBUS_OUTPUT_RANGE_MIN_TEM	=	1255	;
CO2_NET_MODBUS_OUTPUT_RANGE_MAX_TEM	=	1256	;
CO2_NET_MODBUS_OUTPUT_RANGE_MIN_HUM	=	1257	;
CO2_NET_MODBUS_OUTPUT_RANGE_MAX_HUM	=	1258	;
CO2_NET_MODBUS_OUTPUT_RANGE_MIN_CO2	=	1259	;
CO2_NET_MODBUS_OUTPUT_RANGE_MAX_CO2	=	1260	;
CO2_NET_MODBUS_MENU_BLOCK_SECONDS	=	1261	;
CO2_NET_MODBUS_BACKLIGHT_KEEP_SECONDS	=	1262	;
CO2_NET_MODBUS_EXTERNAL_NODES_PLUG_AND_PLAY 	=	1263	;
CO2_NET_MODBUS_SCAN_DB_CTR	=	1264	;
CO2_NET_MODBUS_RESET_SCAN_DB	=	1265	;

CO2_NET_MODBUS_SCAN_START	=	1266	;
CO2_NET_MODBUS_SCAN_END 	=	2535	;

CO2_NET_MODBUS_GET_NODES_PARA_START 	=	2536	;
CO2_NET_MODBUS_GET_NODES_PARA_END 	=	2568	;
CO2_NET_MODBUS_SCAN_OCCUPY_START	=	2568	;
CO2_NET_MODBUS_SCAN_OCCUPY_END	=	2600	;
CO2_NET_MODBUS_SCAN_ONLINE_START	=	2600	;
CO2_NET_MODBUS_SCAN_ONLINE_END	=	2632	;
CO2_NET_MODBUS_IDLE_ID	=	2632	;

CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_READ	=	10000	;
CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM0	=	10001	;
CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ0	=	10002	;
CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM1	=	10003	;
CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ1	=	10004	;
CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM2	=	10005	;
CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ2	=	10006	;
CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM3	=	10007	;
CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ3	=	10008	;
CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM4	=	10009	;
CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ4	=	10010	;
CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM5	=	10011	;
CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ5	=	10012	;
CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM6	=	10013	;
CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ6	=	10014	;
CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM7	=	10015	;
CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ7	=	10016	;
CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM8	=	10017	;
CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ8	=	10018	;
CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM9	=	10019	;
CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ9	=	10020	;
CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_ADD_HUM	=	10021	;
CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_ADD_FREQ	=	10022	;
CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_ADD_ENABLE	=	10023	;

} MODBUS_CO2_NET_REGISTER_LIST;
*/
class CCO2NetView : public CFormView
{
	DECLARE_DYNCREATE(CCO2NetView)

public:
	CCO2NetView();           // protected constructor used by dynamic creation
	virtual ~CCO2NetView();

public:
	enum { IDD = IDD_DIALOG_NET_CO2 };
#ifdef _DEBUG
	virtual void AssertValid() const;
#ifndef _WIN32_WCE
	virtual void Dump(CDumpContext& dc) const;
#endif
#endif

protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support
    virtual void OnInitialUpdate();
	DECLARE_MESSAGE_MAP()
public:
    void Fresh();
	 void Fresh_View();
    void Initial_Registerlist();
    void Initial_Window();
   void Get_CO2_Temperature_unit(CString &strTemp);
   void Show_PassWord();
   void Show_TCPIP();
   void Show_Temperature();
   void Fresh_Grid();
   int get_serialnumber();
 void  Check_DayTime();
 void Initial_OutputList();
 void Initial_VarList();
 LRESULT OnFreshView(WPARAM wParam, LPARAM lParam);
     void  Check_HourTime();

	 afx_msg LRESULT  ResumeMessageCallBack(WPARAM wParam, LPARAM lParam);
	 afx_msg LRESULT  ReadDataCallBack(WPARAM wParam, LPARAM lParam);

public:
CBrush m_brush;
	HANDLE hFirstThread;
    CEdit m_edit_IDAddress;
    CEdit m_edit_SN;
    CEdit m_Edit_FVevsion;
    CEdit m_Edit_HardVer;
    CComboBox m_Combox_baudrate;
    CEdit m_Edit_RHum;
    CButton m_AlarmSetting_M;
    CButton m_AlarmSetting_Auto;
    CComboBox m_Combox_CO2State;
    
 
    CEdit m_Edit_Password;
    CComboBox m_Combox_IpModel;
    CEdit m_Edit_MACAddress;
    CIPAddressCtrl m_IPCtrl_IpAddress;
    CIPAddressCtrl m_IpCtrl_Gateway;
    CIPAddressCtrl m_IpCtrl_Subnet;
    CEdit m_Edit_Port;

    CEdit m_Edit_External_Temp;
    CEdit m_Internal_Temp;
    CComboBox m_Combox_TempUnit;
    CComboBox m_Edit_SensorSelect;

    CEdit m_Edit_Calibrate_Offset;
    CEdit m_Edit_Alarm_Setpoint;
    CEdit m_Edit_PreAlarm_Setpoint;
    CEdit m_Edit_AlarmOn;
    CEdit m_Edit_AlarmOff;
    CEdit m_Edit_MenuBlockTimes;
    CEdit m_Edit_BacklightTime;
    CButton m_HeatingHumiditySensor_Enable;
    CButton m_HeatingHumiditySensor_Disable;
    afx_msg void OnCbnSelchangeCo2TempUnit();
    CButton m_Check_Enable_Password;
    afx_msg void OnBnClickedBtnCo2ClearCal();
    CMsflexgrid m_msflexgrid;
	public:
    BOOL Flag_Reg;
    CString cs_temp_unit;
    // unsigned short product_register_value[4000];
	unsigned short External_ArrayData[1100];
	unsigned short Scan_ArrayData[1300]; 
#if 1
    int	CO2_NET_MODBUS_SERIALNUMBER_LOWORD	;
    int	CO2_NET_MODBUS_SERIALNUMBER_HIWORD	;
    int	CO2_NET_MODBUS_SOFTWARE_VERSION_LO 	;
    int	CO2_NET_MODBUS_SOFTWARE_VERSION_HI 	;
    int	CO2_NET_MODBUS_ADDRESS 	;
    int	CO2_NET_MODBUS_PRODUCT_MODEL 	;
    int	CO2_NET_MODBUS_HARDWARE_REV	;
    int	CO2_NET_MODBUS_PIC_REV	;
    int	CO2_NET_MODBUS_ADDRESS_PLUG_N_PLAY	;
    int	CO2_NET_MODBUS_TIME_ZONE	;
    int	CO2_NET_MODBUS_BAUDRATE 	;
    int	CO2_NET_MODBUS_DAYLIGHT_ENABLE	;
    int	CO2_NET_MODBUS_BOOTLOADER_VERSION	;
    int	CO2_NET_MODBUS_RESET_FLASH	;
    int	CO2_NET_MODBUS_UPDATE_STATUS 	;
    int	CO2_NET_MODBUS_INIT_WR_TIME	;
    int	CO2_NET_MODBUS_TIME_SERVER_SELECT 	;
    int	CO2_NET_MODBUS_SERINALNUMBER_WRITE_FLAG	;
    int	CO2_NET_MODBUS_REFRESH_STATUS 	;
    int	CO2_NET_MODBUS_REFRESH_FLASH	;
    int	CO2_NET_MODBUS_REFRESH_FLASH_FREQ 	;
    int	CO2_NET_MODBUS_MAC_ADDRESS_CHANGE_ENABLE	;
    int	CO2_NET_MODBUS_REFRESH_FLASH_TIMER	;
    int	CO2_NET_MODBUS_MAC_ADDRESS_START	;
    int	CO2_NET_MODBUS_IP_MODE	;
    int	CO2_NET_MODBUS_IP_ADDRESS_START	;
    int	CO2_NET_MODBUS_SUBNET_MASK_ADDRESS_START	;
    int	CO2_NET_MODBUS_GATEWAY_ADDRESS_START	;
    int	CO2_NET_MODBUS_TCP_SERVER_ENABLE 	;
    int	CO2_NET_MODBUS_LISTEN_PORT_AT_TCP_SERVER_MODE_START	;

    int	CO2_NET_MODBUS_IP_MODE_GHOST	;
    int	CO2_NET_MODBUS_IP_ADDRESS_GHOST_START	;
    int	CO2_NET_MODBUS_SUBNET_MASK_ADDRESS_GHOST_START	;
    int	CO2_NET_MODBUS_GATEWAY_ADDRESS_GHOST_START	;
    int	CO2_NET_MODBUS_TCP_SERVER_ENABLE_GHOST 	;
    int	CO2_NET_MODBUS_LISTEN_PORT_AT_TCP_SERVER_MODE_GHOST_START 	;
    int	CO2_NET_MODBUS_ENABLE_GHOST	;

    int	CO2_NET_MODBUS_SCAN_COMMAND	;
    int	CO2_NET_MODBUS_SUBNET_TYPE 	;
    int	CO2_NET_MODBUS_NTP_COMMAND	;
    int	CO2_NET_MODBUS_TIME_SERVER0_IP_START	;
    int	CO2_NET_MODBUS_TIME_SERVER1_IP_START	;
    int	CO2_NET_MODBUS_TIME_SERVER2_IP_START	;
    int	CO2_NET_MODBUS_TIME_SERVER3_IP_START	;
    int	CO2_NET_MODBUS_TIME_SERVER4_IP_START	;
    int	CO2_NET_MODBUS_TIME_SERVER5_IP_START	;
    int	CO2_NET_MODBUS_TIME_SYNC_RESULT	;

    int	CO2_NET_MODBUS_TEMPERATURE_SENSOR_SELECT	;
    int	CO2_NET_MODBUS_TEMPERATURE_DEGREE_C_OR_F	;
    int	CO2_NET_MODBUS_INTERNAL_TEMPERATURE_CELSIUS	;
    int	CO2_NET_MODBUS_INTERNAL_TEMPERATURE_FAHRENHEIT	;
    int	CO2_NET_MODBUS_EXTERNAL_TEMPERATURE_CELSIUS	;
    int	CO2_NET_MODBUS_EXTERNAL_TEMPERATURE_FAHRENHEIT	;

    int	CO2_NET_MODBUS_TEMPERATURE_OFFSET_INTERNAL	;
    int	CO2_NET_MODBUS_HUMIDITY	;
    int	CO2_NET_MODBUS_HUMIDITY_FREQUENCY	;
    int	CO2_NET_MODBUS_HUMIDITY_CALIBRATION_TABLE_COUNTER	;
    int	CO2_NET_MODBUS_CO2_INTERNAL_EXIST	;
    int	CO2_NET_MODBUS_CO2_INTERNAL	;
    int	CO2_NET_MODBUS_CO2_INTERNAL_OFFSET	;
    int	CO2_NET_MODBUS_CO2_INTERNAL_PREALARM_SETPOINT	;
    int	CO2_NET_MODBUS_CO2_INTERNAL_ALARM_SETPOINT	;
    int	CO2_NET_MODBUS_CO2_EXTERNAL_START	;
    int	CO2_NET_MODBUS_CO2_EXTERANL_END	;
    int	CO2_NET_MODBUS_CO2_EXTERNAL_OFFSET_START	;
    int	CO2_NET_MODBUS_CO2_EXTERNAL_OFFSET_END	;
    int	CO2_NET_MODBUS_CO2_EXTERNAL_PREALARM_SETPOINT_START	;
    int	CO2_NET_MODBUS_CO2_EXTERNAL_PREALARM_SETPOINT_END	;
    int	CO2_NET_MODBUS_CO2_EXTERNAL_ALARM_SETPOINT_START 	;
    int	CO2_NET_MODBUS_CO2_EXTERNAL_ALARM_SETPOINT_END	;
    int	CO2_NET_MODBUS_CO2_SLOPE_DETECT_VALUE	;
    int	CO2_NET_MODBUS_CO2_FILTER	;
    int	CO2_NET_MODBUS_PASSWORD_ENABLE	;
    int	CO2_NET_MODBUS_USER_PASSWORD0 	;
    int	CO2_NET_MODBUS_USER_PASSWORD1	;
    int	CO2_NET_MODBUS_USER_PASSWORD2	;
    int	CO2_NET_MODBUS_USER_PASSWORD3	;
    int	CO2_NET_MODBUS_RTC_CENTURY	;
    int	CO2_NET_MODBUS_RTC_YEAR	;
    int	CO2_NET_MODBUS_RTC_MONTH	;
    int	CO2_NET_MODBUS_RTC_DAY	;
    int	CO2_NET_MODBUS_RTC_WEEK	;
    int	CO2_NET_MODBUS_RTC_HOUR	;
    int	CO2_NET_MODBUS_RTC_MINUTE	;
    int	CO2_NET_MODBUS_RTC_SECOND	;
    int	CO2_NET_MODBUS_ALARM_AUTO_MANUAL	;
    int	CO2_NET_MODBUS_PRE_ALARM_SETTING_ON_TIME	;
    int	CO2_NET_MODBUS_PRE_ALARM_SETTING_OFF_TIME	;
    int	CO2_NET_MODBUS_ALARM_DELAY_TIME	;
    int	CO2_NET_MODBUS_OUTPUT_AUTO_MANUAL	;
    int	CO2_NET_MODBUS_OUTPUT_MANUAL_VALUE_TEM	;
    int	CO2_NET_MODBUS_OUTPUT_MANUAL_VALUE_HUM	;
    int	CO2_NET_MODBUS_OUTPUT_MANUAL_VALUE_CO2	;
    int	CO2_NET_MODBUS_OUTPUT_MODE	;
    int	CO2_NET_MODBUS_OUTPUT_RANGE_MIN_TEM	;
    int	CO2_NET_MODBUS_OUTPUT_RANGE_MAX_TEM	;
    int	CO2_NET_MODBUS_OUTPUT_RANGE_MIN_HUM	;
    int	CO2_NET_MODBUS_OUTPUT_RANGE_MAX_HUM	;
    int	CO2_NET_MODBUS_OUTPUT_RANGE_MIN_CO2	;
    int	CO2_NET_MODBUS_OUTPUT_RANGE_MAX_CO2	;
    int	CO2_NET_MODBUS_MENU_BLOCK_SECONDS	;
    int	CO2_NET_MODBUS_BACKLIGHT_KEEP_SECONDS	;
    int	CO2_NET_MODBUS_EXTERNAL_NODES_PLUG_AND_PLAY 	;
    int	CO2_NET_MODBUS_SCAN_DB_CTR	;
    int	CO2_NET_MODBUS_RESET_SCAN_DB	;
    int	CO2_NET_MODBUS_SCAN_START	;
    int	CO2_NET_MODBUS_SCAN_END 	;
    int	CO2_NET_MODBUS_GET_NODES_PARA_START 	;
    int	CO2_NET_MODBUS_GET_NODES_PARA_END 	;
    int	CO2_NET_MODBUS_SCAN_OCCUPY_START	;
    int	CO2_NET_MODBUS_SCAN_OCCUPY_END	;
    int	CO2_NET_MODBUS_SCAN_ONLINE_START	;
    int	CO2_NET_MODBUS_SCAN_ONLINE_END	;
    int	CO2_NET_MODBUS_IDLE_ID	;
    int	CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_READ	;
    int	CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM0	;
    int	CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ0	;
    int	CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM1	;
    int	CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ1	;
    int	CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM2	;
    int	CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ2	;
    int	CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM3	;
    int	CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ3	;
    int	CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM4	;
    int	CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ4	;
    int	CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM5	;
    int	CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ5	;
    int	CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM6	;
    int	CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ6	;
    int	CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM7	;
    int	CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ7	;
    int	CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM8	;
    int	CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ8	;
    int	CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_HUM9	;
    int	CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_FREQ9	;
    int	CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_ADD_HUM	;
    int	CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_ADD_FREQ	;
    int	CO2_NET_MODBUS_HUMIDITY_SENSOR_TABLE_ADD_ENABLE	;
    #endif
public:
    afx_msg void OnBnClickedRadioAlarmManual();
    afx_msg void OnBnClickedRadioAlarmAuto();
    afx_msg void OnCbnSelchangeCo2AlarmState();
    afx_msg void OnBnClickedEnablePassword();
    afx_msg void OnEnKillfocusEditCo2Passwor();
    afx_msg void OnCbnSelchangeComboIpmodel();
    afx_msg void OnBnClickedButtonApply();
    afx_msg void OnBnClickedCo2Enableidbutton();
    afx_msg void OnEnKillfocusIdCo2Edit();
    afx_msg void OnEnKillfocusCo2PrepareAlarmSetpoint();
    afx_msg void OnEnKillfocusCo2AlarmSetpoint();
    afx_msg void OnCbnSelchangeComboCo2SensorSel();
    afx_msg void OnEnKillfocusCo2CalibratingOffset();
    afx_msg void OnEnKillfocusCo2AlarmOnTime();
    afx_msg void OnEnKillfocusCo2AlarmOffTime();
    afx_msg void OnEnKillfocusEditCo2BlockTime();
    afx_msg void OnEnKillfocusEditCo2BacklightTime();
    afx_msg void OnBnClickedButtonCo2SyncTime();
    afx_msg void OnBnClickedBtnCo2Refresh();
    CDateTimeCtrl m_co2_time_picker;
    CDateTimeCtrl m_co2_day_picker;
	CEdit m_edit_co2_value;
	afx_msg void OnEnKillfocusEditCo2Value();
	afx_msg HBRUSH OnCtlColor(CDC* pDC, CWnd* pWnd, UINT nCtlColor);
	virtual BOOL PreTranslateMessage(MSG* pMsg);
	virtual LRESULT WindowProc(UINT message, WPARAM wParam, LPARAM lParam);
//	ListCtrlEx::CListCtrlEx m_co2_inputs_list;
	CMsflexgrid m_grid_input;

	void Show_InputList();
	ListCtrlEx::CListCtrlEx m_user_list;
	ListCtrlEx::CListCtrlEx m_output_list;
	DECLARE_EVENTSINK_MAP()
	void DblClickMsflexgridInput();
	CEdit m_inNameEdt;
	afx_msg void OnEnKillfocusEditName();


	CString m_oldname;
	bool m_isinput;
	int m_curcol;
	int m_currow;

    afx_msg void OnBnClickedRadioCo2CalEnable();
    afx_msg void OnBnClickedRadioCo2CalDisable();
    afx_msg void OnBnClickedRadioHumidityHeatEnable();
};


