#pragma once

#include "Bacnet_Include.h"
#include "CM5\ud_str.h"
#include "global_define.h"
#include "Global_Struct.h"
#include "ProductModel.h"
#include <map>
#define MY_MBPOLL_REG_DIALOG_MSG (WM_USER + 557)
#define MY_MBPOLL_WRITE_REG_MSG (WM_USER + 558)

extern const int WRITE_ONE_SUCCESS_LIST;
extern const int WRITE_ONE_FAIL_LIST ;
extern const int WRITE_MULTI_SUCCESS_LIST  ;
extern const int WRITE_MULTI_FAIL_LIST  ;

extern bool no_mouse_keyboard_event_enable_refresh ;
extern CString USB_Serial;
extern int g_invoke_id;
extern vector <int> Change_Color_ID;
extern HANDLE hThread;
extern DWORD nThreadID;
extern DWORD nThreadID_mstp;
extern HWND hMbpollWnd;
extern HWND hMbpollWritePopWnd;
extern int regDetailsOpenedFrom;	// 0 = MbPoll.cpp; 1 = mbpollFunctions.cpp
extern int g_language;
extern const bool WRITE_SUCCESS;
extern const bool WRITE_FAIL ;
extern	   bool g_HumChamberThread;

extern			  BOOL g_bChamber;
extern bool list_mouse_click;
extern CString CurrentT3000Version;
extern BOOL g_SelectChanged;
//Fance_4
extern unsigned short product_register_value[20000];
extern int product_type ;
extern int old_product_type;
extern HWND      m_building_config_hwnd;
extern bool g_fresh_T3000_background;
extern unsigned short multi_register_value_tcp[10000];
extern	unsigned short multi_register_value[1024];
extern unsigned short cm5_register_value[512]; //CM5
extern unsigned short m_buffer[512];//CM5
extern unsigned short reg_tstat6[1024];//tstat6_new
extern unsigned short reg_tststold[1024];
extern char charr[600][2][600];
extern unsigned short newtstat6[1024];


extern BOOL Flexflash;
extern BOOL FlexSP;
extern int FlexSPN;
extern int  MDAY,MNIGHT;


extern int nCom;
extern	CString program_path;
extern	int g_tstat_id;
extern  int g_mstp_deviceid; //用于全局根据Device id 访问 MSTP 。
extern unsigned int g_serialNum;
extern	BOOL g_tstat_id_changed;
extern  BOOL g_bPauseMultiRead;     // for background read register
extern  int now_tstat_id;//for batch load/flash read/write
extern  CString g_strImagePathName;
extern	CString	g_strDatabasefilepath;
extern	CString g_strExePth;
extern  CString g_achive_folder;
extern  CString g_achive_folder_temp_txt;
extern  CString g_achive_folder_temp_db;
extern  CString g_achive_device_name_path;
extern  CString g_strImgeFolder;
extern  CString g_strBuildingFolder;

extern  CString g_achive_monitor_datatbase_path ;

extern BOOL g_mstp_flag;
extern	BOOL g_Scanfully;
extern	BOOL g_ScanSecurity;
extern	int g_nStartID;
extern	int g_nEndID;
extern BOOL g_bCancelScan;
extern int g_ScnnedNum;
extern CString g_strScanInfoPrompt;
 
extern int gCommunicationType;
extern CString g_strCurBuildingDatabasefilePath;
extern CString m_str_curBuilding_Domain_IP;
extern CString m_str_curBuilding_Domain_Port;
extern CString g_strTstat5a;
extern CString g_strTstat5b;
extern CString g_strTstat5b2;
extern CString g_strTstat5c;
extern CString g_strTstat5d;
extern CString g_strnetWork;
extern CString g_strTstat5f;
extern CString g_strTstat5g;
extern CString g_strTstat5e;
extern CString g_strTstat5h;
extern CString g_strTstat6;
extern CString g_strTstat7;
extern CString g_strOR485;
extern CString g_strPressure;
extern CString g_strLightingCtrl;
 extern CString g_strHumChamber;

extern int g_CommunicationType;
extern int m_nbaudrat;
extern CString showing_text;

extern  CCriticalSection  critical_section;
extern  CCriticalSection  register_critical_section;



extern BOOL g_buser_log_in;
extern BOOL g_bPrivilegeMannage;
extern CString g_strLoginUserName;
extern int g_UserLevel;

extern CString g_strSensorName;
extern CString g_strInName1;
extern CString g_strInName2;
extern CString g_strInName3;
extern CString g_strInName4;
extern CString g_strInName5;
extern CString g_strInName6;
extern CString g_strInName7;
extern CString g_strInName8;

extern CString g_strInHumName;		// for tstat6 humidity input
extern CString			   g_strInCO2;
extern CString g_strLightingSensor;

extern CString g_strOutName1;
extern CString g_strOutName2;
extern CString g_strOutName3;
extern CString g_strOutName4;
extern CString g_strOutName5;
extern CString g_strOutName6;
extern CString g_strOutName7;
extern CString g_strOutName8;
extern int g_ifanStatus;
extern CString g_strFan;

extern BOOL g_bEnableRefreshTreeView;
extern BOOL g_bPauseRefreshTree;
extern unsigned int g_llTxCount;
extern unsigned int g_llRxCount;
extern int g_llerrCount ;
extern BOOL g_unint;

//int const PM_TSTAT5B = 1;
//int const PM_TSTAT5A = 2;
//int const PM_TSTAT5B2 = 3;
//int const PM_TSTAT5C = 4;
//int const PM_TSTAT6 = 6;
//int const PM_TSTAT7 = 7;
//int const PM_TSTAT5i= 8;
//int const PM_TSTAT8 = 9 ;
//int const PM_TSTAT5D = 12;
//int const PM_AirQuality = 13;
//int const PM_HUMTEMPSENSOR = 14;
//int const PM_TSTATRUNAR = 15;
//const int PM_TSTAT5E = 16;
//int const PM_TSTAT5F = 17;
//int const PM_TSTAT5G = 18;
//int const PM_TSTAT5H = 19;
//
//int const PM_T3PT10= 26;
//int const PM_T3IOA = 21;
//int const PM_T332AI = 22;
//int const PM_T38AI16O = 23;
//int const PM_T38I13O = 20;
//int const PM_T34AO = 28;
//int const PM_T36CT = 29;
//
//int const PM_ZIGBEE = 24;
//int const PM_FLEXDRIVER = 25;
//int const PM_T3PERFORMANCE = 27;
//int const PM_SOLAR = 30;
//int const PM_FWMTRANSDUCER = 31;
//int const PM_CO2_NET = 32;
//int const PM_CO2_RS485 = 33;
//int const PM_CO2_NODE = 34;
//int const PM_MINIPANEL = 35;
//int const PM_CS_SM_AC = 36;
//int const PM_CS_SM_DC = 37;
//int const PM_CS_RSM_AC = 38;
//int const PM_CS_RSM_DC = 39;
//
//
//int const PM_PRESSURE = 40;
//int const PM_PM5E = 41;
//int const PM_HUM_R=42;
//
//int const PM_T322AI=43;
//int const PM_T38AI8AO6DO=44;
//int const PM_PRESSURE_SENSOR=45;
// 
//
//
//int const PM_CM5 = 50;
//int const PM_TSTAT6_HUM_Chamber=64;
//
//int const PM_NC = 100;
//int const PM_LightingController = 103;

/*int const PM_TSTATRUNAR = 15;*/


extern int MODBUS_SERIALNUMBER_LOWORD                          ;

extern int MODBUS_SERIALNUMBER_HIWORD                          ;

extern int MODBUS_VERSION_NUMBER_LO                            ;
extern int MODBUS_VERSION_NUMBER_HI                            ;
extern int MODBUS_ADDRESS                                      ;
extern int MODBUS_PRODUCT_MODEL                                ;
extern int MODBUS_HARDWARE_REV                                 ;
extern int MODBUS_PIC_VERSION                                  ;
extern int MODBUS_HUM_PIC_VERSION                              ;
extern int MODBUS_ADDRESS_PLUG_N_PLAY                          ;

extern int MODBUS_CUSTOM_ADDRESS                               ;
extern int MODBUS_BASE_ADDRESS                                 ;
extern int MODBUS_UPDATE_STATUS                                ;
extern int MODBUS_UPDATE_PTR_HI                                ;
extern int MODBUS_UPDATE_PTR_LO                                ;
extern int MODBUS_SCRATCHPAD_ADDRESS                           ;
extern int MODBUS_HARDWARE_INFORMATION                         ;

extern int MODBUS_COOL_HEAT_MODE                               ;
extern int MODBUS_MODE_OPERATION                               ;
extern int MODBUS_SEQUENCE                                     ;
extern int MODBUS_DEGC_OR_F                                    ;
extern int MODBUS_FAN_MODE                                     ;
extern int MODBUS_POWERUP_MODE                                 ;
extern int MODBUS_AUTO_ONLY                                    ;
extern int MODBUS_FACTORY_DEFAULTS                             ;
extern int MODBUS_INFO_BYTE                                    ;
extern int MODBUS_BAUDRATE                                     ;
extern int MODBUS_OVERRIDE_TIMER                               ;
extern int MODBUS_OVERRIDE_TIMER_LEFT                          ;
extern int MODBUS_HEAT_COOL_CONFIG                             ;
extern int MODBUS_TIMER_ON                                     ;
extern int MODBUS_TIMER_OFF                                    ;
extern int MODBUS_TIMER_UNITS                                  ;
extern int MODBUS_DEAD_MASTER                                  ;
extern int MODBUS_SYSTEM_TIME_FORMAT                           ;
extern int MODBUS_FREE_COOL_CONFIG                             ;
extern int MODBUS_RS485_MODE                                   ;
extern int MODBUS_TEMPRATURE_CHIP                              ;
extern int MODBUS_ANALOG1_RANGE                                ;
extern int MODBUS_ANALOG2_RANGE                                ;
extern int MODBUS_ANALOG3_RANGE                                ;
extern int MODBUS_ANALOG4_RANGE                                ;
extern int MODBUS_ANALOG5_RANGE                                ;
extern int MODBUS_ANALOG6_RANGE                                ;
extern int MODBUS_ANALOG7_RANGE                                ;
extern int MODBUS_ANALOG8_RANGE                                ;
extern int MODBUS_INTERNAL_THERMISTOR                          ;
extern int MODBUS_ANALOG_INPUT1                                ;
extern int MODBUS_ANALOG_INPUT2                                ;
extern int MODBUS_ANALOG_INPUT3                                ;
extern int MODBUS_ANALOG_INPUT4                                ;
extern int MODBUS_ANALOG_INPUT5                                ;
extern int MODBUS_ANALOG_INPUT6                                ;
extern int MODBUS_ANALOG_INPUT7                                ;
extern int MODBUS_ANALOG_INPUT8                                ;
extern int MODBUS_EXTERNAL_SENSOR1                             ;
extern int MODBUS_EXTERNAL_SENSOR2                             ;
extern int MODBUS_INPUT_MANU_ENABLE                            ;
extern int MODBUS_FILTER                                       ;
extern int MODBUS_INPUT1_FILTER                                ;
extern int MODBUS_INPUT2_FILTER                                ;
extern int MODBUS_INPUT3_FILTER                                ;
extern int MODBUS_INPUT4_FILTER                                ;
extern int MODBUS_INPUT5_FILTER                                ;
extern int MODBUS_INPUT6_FILTER                                ;
extern int MODBUS_INPUT7_FILTER                                ;
extern int MODBUS_INPUT8_FILTER                                ;
extern int MODBUS_EX_SENSOR1_FILTER                            ;
extern int MODBUS_EX_SENSOR2_FILTER                            ;
extern int MODBUS_CALIBRATION_TERM                             ;
extern int MODBUS_CALIBRATION_INTERNAL_THERMISTOR              ;
extern int MODBUS_CALIBRATION_ANALOG1                          ;
extern int MODBUS_CALIBRATION_ANALOG2                          ;
extern int MODBUS_CALIBRATION_ANALOG3                          ;
extern int MODBUS_CALIBRATION_ANALOG4                          ;
extern int MODBUS_CALIBRATION_ANALOG5                          ;
extern int MODBUS_CALIBRATION_ANALOG6                          ;
extern int MODBUS_CALIBRATION_ANALOG7                          ;
extern int MODBUS_CALIBRATION_ANALOG8                          ;
extern int MODBUS_HUMCOUNT1_H                                  ;
extern int MODBUS_HUMRH1_H                                     ;
extern int MODBUS_HUMCOUNT2_H                                  ;
extern int MODBUS_HUMRH2_H                                     ;
extern int MODBUS_ANALOG1_FUNCTION                             ;
extern int MODBUS_ANALOG2_FUNCTION                             ;
extern int MODBUS_ANALOG3_FUNCTION                             ;
extern int MODBUS_ANALOG4_FUNCTION                             ;
extern int MODBUS_ANALOG5_FUNCTION                             ;
extern int MODBUS_ANALOG6_FUNCTION                             ;
extern int MODBUS_ANALOG7_FUNCTION                             ;
extern int MODBUS_ANALOG8_FUNCTION                             ;
extern int MODBUS_TABLE1_ZERO                                  ;
extern int MODBUS_TABLE1_HALFONE                               ;
extern int MODBUS_TABLE1_ONE                                   ;
extern int MODBUS_TABLE1_HALFTWO                               ;
extern int MODBUS_TABLE1_TWO                                   ;
extern int MODBUS_TABLE1_HALFTHREE                             ;
extern int MODBUS_TABLE1_THREE                                 ;
extern int MODBUS_TABLE1_HALFFOUR                              ;
extern int MODBUS_TABLE1_FOUR                                  ;
extern int MODBUS_TABLE1_HALFFIVE                              ;
extern int MODBUS_TABLE1_FIVE                                  ;
extern int MODBUS_TABLE2_ZERO                                  ;
extern int MODBUS_TABLE2_HALFONE                               ;
extern int MODBUS_TABLE2_ONE                                   ;
extern int MODBUS_TABLE2_HALFTWO                               ;
extern int MODBUS_TABLE2_TWO                                   ;
extern int MODBUS_TABLE2_HALFTHREE                             ;
extern int MODBUS_TABLE2_THREE                                 ;
extern int MODBUS_TABLE2_HALFFOUR                              ;
extern int MODBUS_TABLE2_FOUR                                  ;
extern int MODBUS_TABLE2_HALFFIVE                              ;
extern int MODBUS_TABLE2_FIVE                                  ;
extern int MODUBS_HUMIDITY_RH                                  ;
extern int MODBUS_HUMIDITY_FREQUENCY                           ;
extern int MODBUS_HUM_PIC_UPDATE                               ;
extern int MODBUS_HUM_CAL_NUM                                  ;
extern int MODBUS_HUM_CURRENT_DEFAULT                          ;
extern int MODBUS_MODE_OUTPUT1                                 ;
extern int MODBUS_MODE_OUTPUT2                                 ;
extern int MODBUS_MODE_OUTPUT3                                 ;
extern int MODBUS_MODE_OUTPUT4                                 ;
extern int MODBUS_MODE_OUTPUT5                                 ;
extern int MODBUS_OUTPUT1_SCALE                                ;
extern int MODBUS_OUTPUT2_SCALE                                ;
extern int MODBUS_DIGITAL_OUTPUT_STATUS                        ;
extern int MODBUS_COOLING_VALVE                                ;
extern int MODBUS_HEATING_VALVE                                ;
extern int MODBUS_DAC_OFFSET                                   ;
extern int MODBUS_OUTPUT1_DELAY_OFF_TO_ON                      ;
extern int MODBUS_OUTPUT2_DELAY_OFF_TO_ON                      ;
extern int MODBUS_OUTPUT3_DELAY_OFF_TO_ON                      ;
extern int MODBUS_OUTPUT4_DELAY_OFF_TO_ON                      ;
extern int MODBUS_OUTPUT5_DELAY_OFF_TO_ON                      ;
extern int MODBUS_OUTPUT6_DELAY_OFF_TO_ON                      ;
extern int MODBUS_OUTPUT7_DELAY_OFF_TO_ON                      ;
extern int MODBUS_DELAY1_OFF_TO_ON_TIME_CURRENT                ;
extern int MODBUS_DELAY2_OFF_TO_ON_TIME_CURRENT                ;
extern int MODBUS_DELAY3_OFF_TO_ON_TIME_CURRENT                ;
extern int MODBUS_DELAY4_OFF_TO_ON_TIME_CURRENT                ;
extern int MODBUS_DELAY5_OFF_TO_ON_TIME_CURRENT                ;
extern int MODBUS_DELAY6_OFF_TO_ON_TIME_CURRENT                ;
extern int MODBUS_DELAY7_OFF_TO_ON_TIME_CURRENT                ;
extern int MODBUS_OUTPUT1_DELAY_ON_TO_OFF                      ;
extern int MODBUS_OUTPUT2_DELAY_ON_TO_OFF                      ;
extern int MODBUS_OUTPUT3_DELAY_ON_TO_OFF                      ;
extern int MODBUS_OUTPUT4_DELAY_ON_TO_OFF                      ;
extern int MODBUS_OUTPUT5_DELAY_ON_TO_OFF                      ;
extern int MODBUS_OUTPUT6_DELAY_ON_TO_OFF                      ;
extern int MODBUS_OUTPUT7_DELAY_ON_TO_OFF                      ;
extern int MODBUS_DELAY1_ON_TO_OFF_TIME_CURRENT                ;
extern int MODBUS_DELAY2_ON_TO_OFF_TIME_CURRENT                ;
extern int MODBUS_DELAY3_ON_TO_OFF_TIME_CURRENT                ;
extern int MODBUS_DELAY4_ON_TO_OFF_TIME_CURRENT                ;
extern int MODBUS_DELAY5_ON_TO_OFF_TIME_CURRENT                ;
extern int MODBUS_DELAY6_ON_TO_OFF_TIME_CURRENT                ;
extern int MODBUS_DELAY7_ON_TO_OFF_TIME_CURRENT                ;
extern int MODBUS_CYCLING_DELAY                                ;
extern int MODBUS_CHANGOVER_DELAY                              ;
extern int MODBUS_VALVE_TRAVEL_TIME                            ;
extern int MODBUS_VALVE_PERCENT                                ;
extern int MODBUS_INTERLOCK_OUTPUT1                            ;
extern int MODBUS_INTERLOCK_OUTPUT2                            ;
extern int MODBUS_INTERLOCK_OUTPUT3                            ;
extern int MODBUS_INTERLOCK_OUTPUT4                            ;
extern int MODBUS_INTERLOCK_OUTPUT5                            ;
extern int MODBUS_INTERLOCK_OUTPUT6                            ;
extern int MODBUS_INTERLOCK_OUTPUT7                            ;
extern int MODBUS_FREEZE_DELAY_ON                              ;
extern int MODBUS_FREEZE_DELAY_OFF                             ;
extern int MODBUS_OUTPUT_MANU_ENABLE                           ;
extern int MODBUS_MANU_RELAY1                                  ;
extern int MODBUS_MANU_RELAY2                                  ;
extern int MODBUS_MANU_RELAY3                                  ;
extern int MODBUS_MANU_RELAY4                                  ;
extern int MODBUS_MANU_RELAY5                                  ;
extern int MODBUS_MANUAL_AO1                                   ;
extern int MODBUS_MANUAL_AO2                                   ;
extern int MODBUS_DEADMASTER_AUTO_MANUAL                       ;
extern int MODBUS_DEADMASTER_OUTPUT_STATE                      ;
extern int MODBUS_DEADMASTER_COOL_OUTPUT                       ;
extern int MODBUS_DEADMASTER_HEAT_OUTPUT                       ;
extern int MODBUS_OUTPUT1_FUNCTION                             ;
extern int MODBUS_OUTPUT2_FUNCTION                             ;
extern int MODBUS_OUTPUT3_FUNCTION                             ;
extern int MODBUS_OUTPUT4_FUNCTION                             ;
extern int MODBUS_OUTPUT5_FUNCTION                             ;
extern int MODBUS_OUTPUT6_FUNCTION                             ;
extern int MODBUS_OUTPUT7_FUNCTION                             ;
extern int MODBUS_FAN_SPEED                                    ;
extern int MODBUS_PID_OUTPUT1                                  ;
extern int MODBUS_PID_OUTPUT2                                  ;
extern int MODBUS_PID_OUTPUT3                                  ;
extern int MODBUS_PID_OUTPUT4                                  ;
extern int MODBUS_PID_OUTPUT5                                  ;
extern int MODBUS_PID_OUTPUT6                                  ;
extern int MODBUS_PID_OUTPUT7                                  ;
extern int MODBUS_UNIVERSAL_OUTPUT_BEGIN                       ;
extern int MODBUS_UNIVERSAL_OUTPUT_COOL1                       ;
extern int MODBUS_UNIVERSAL_OUTPUT_COOL2                       ;
extern int MODBUS_UNIVERSAL_OUTPUT_COOL3                       ;
extern int MODBUS_UNIVERSAL_OUTPUT_HEAT1                       ;
extern int MODBUS_UNIVERSAL_OUTPUT_HEAT2                       ;
extern int MODBUS_UNIVERSAL_OUTPUT_HEAT3                       ;
extern int MODBUS_FAN0_OPER_TABLE_COAST                        ;
extern int MODBUS_FAN0_OPER_TABLE_COOL1                        ;
extern int MODBUS_FAN0_OPER_TABLE_COOL2                        ;
extern int MODBUS_FAN0_OPER_TABLE_COOL3                        ;
extern int MODBUS_FAN0_OPER_TABLE_HEAT1                        ;
extern int MODBUS_FAN0_OPER_TABLE_HEAT2                        ;
extern int MODBUS_FAN0_OPER_TABLE_HEAT3                        ;
extern int MODBUS_FAN1_OPER_TABLE_COAST                        ;
extern int MODBUS_FAN1_OPER_TABLE_COOL1                        ;
extern int MODBUS_FAN1_OPER_TABLE_COOL2                        ;
extern int MODBUS_FAN1_OPER_TABLE_COOL3                        ;
extern int MODBUS_FAN1_OPER_TABLE_HEAT1                        ;
extern int MODBUS_FAN1_OPER_TABLE_HEAT2                        ;
extern int MODBUS_FAN1_OPER_TABLE_HEAT3                        ;
extern int MODBUS_FAN2_OPER_TABLE_COAST                        ;
extern int MODBUS_FAN2_OPER_TABLE_COOL1                        ;
extern int MODBUS_FAN2_OPER_TABLE_COOL2                        ;
extern int MODBUS_FAN2_OPER_TABLE_COOL3                        ;
extern int MODBUS_FAN2_OPER_TABLE_HEAT1                        ;
extern int MODBUS_FAN2_OPER_TABLE_HEAT2                        ;
extern int MODBUS_FAN2_OPER_TABLE_HEAT3                        ;
extern int MODBUS_FAN3_OPER_TABLE_COAST                        ;
extern int MODBUS_FAN3_OPER_TABLE_COOL1                        ;
extern int MODBUS_FAN3_OPER_TABLE_COOL2                        ;
extern int MODBUS_FAN3_OPER_TABLE_COOL3                        ;
extern int MODBUS_FAN3_OPER_TABLE_HEAT1                        ;
extern int MODBUS_FAN3_OPER_TABLE_HEAT2                        ;
extern int MODBUS_FAN3_OPER_TABLE_HEAT3                        ;
extern int MODBUS_FANAUT_OPER_TABLE_COAST                      ;
extern int MODBUS_FANAUT_OPER_TABLE_COOL1                      ;
extern int MODBUS_FANAUT_OPER_TABLE_COOL2                      ;
extern int MODBUS_FANAUT_OPER_TABLE_COOL3                      ;
extern int MODBUS_FANAUT_OPER_TABLE_HEAT1                      ;
extern int MODBUS_FANAUT_OPER_TABLE_HEAT2                      ;
extern int MODBUS_FANAUT_OPER_TABLE_HEAT3                      ;
extern int MODBUS_VALVE_OPERATION_TABLE_BEGIN                  ;
extern int MODBUS_VALVE_OPER_TABLE_COOL1                       ;
extern int MODBUS_VALVE_OPER_TABLE_COOL2                       ;
extern int MODBUS_VALVE_OPER_TABLE_COOL3                       ;
extern int MODBUS_VALVE_OPER_TABLE_HEAT1                       ;
extern int MODBUS_VALVE_OPER_TABLE_HEAT2                       ;
extern int MODBUS_VALVE_OPER_TABLE_HEAT3                       ;
extern int MODBUS_HEAT_UNIVERSAL_TABLE                         ;
extern int MODBUS_COOL_UNIVERSAL_TABLE                         ;
extern int MODBUS_HEAT_ORIGINAL_TABLE                          ;
extern int MODBUS_COOL_ORIGINAL_TABLE                          ;
extern int MODBUS_VALVE_OFF_TABLE_COAST                        ;
extern int MODBUS_VALVE_OFF_TABLE_COOL1                        ;
extern int MODBUS_VALVE_OFF_TABLE_COOL2                        ;
extern int MODBUS_VALVE_OFF_TABLE_COOL3                        ;
extern int MODBUS_VALVE_OFF_TABLE_HEAT1                        ;
extern int MODBUS_VALVE_OFF_TABLE_HEAT2                        ;
extern int MODBUS_VALVE_OFF_TABLE_HEAT3                        ;
extern int MODBUS_DEFAULT_SETPOINT                             ;
extern int MODBUS_SETPOINT_CONTROL                             ;
extern int MODBUS_DAYSETPOINT_OPTION                           ;
extern int MODBUS_MIDDLE_SETPOINT                              ;
extern int MODBUS_DAY_SETPOINT                                 ;
extern int MODBUS_DAY_COOLING_DEADBAND                         ;
extern int MODBUS_DAY_HEATING_DEADBAND                         ;
extern int MODBUS_DAY_COOLING_SETPOINT                         ;
extern int MODBUS_DAY_HEATING_SETPOINT                         ;
extern int MODBUS_NIGHT_SETPOINT                               ;
extern int MODBUS_APPLICATION                                  ;
extern int MODBUS_NIGHT_HEATING_DEADBAND                       ;
extern int MODBUS_NIGHT_COOLING_DEADBAND                       ;
extern int MODBUS_NIGHT_HEATING_SETPOINT                       ;
extern int MODBUS_NIGHT_COOLING_SETPOINT                       ;
extern int MODBUS_WINDOW_INTERLOCK_COOLING_SETPOINT         	 ;
extern int MODBUS_WINDOW_INTERLOCK_HEATING_SETPOINT            ;
extern int MODBUS_UNIVERSAL_NIGHTSET                           ;
extern int MODBUS_UNIVERSAL_SET                                ;
extern int MODBUS_UNIVERSAL_DB_HI                              ;
extern int MODBUS_UNIVERSAL_DB_LO                              ;
extern int MODBUS_ECOMONY_COOLING_SETPOINT                     ;
extern int MODBUS_ECOMONY_HEATING_SETPOINT                     ;
extern int MODBUS_POWERUP_SETPOINT                             ;
extern int MODBUS_MAX_SETPOINT                                 ;
extern int MODBUS_MIN_SETPOINT                                 ;
extern int MODBUS_MAX_SETPOINT2                                ;
extern int MODBUS_MIN_SETPOINT2                                ;
extern int MODBUS_MAX_SETPOINT3                                ;
extern int MODBUS_MIN_SETPOINT3                                ;
extern int MODBUS_MAX_SETPOINT4                                ;
extern int MODBUS_MIN_SETPOINT4                                ;
extern int MODBUS_SETPOINT_INCREASE                            ;
extern int MODBUS_FREEZE_TEMP_SETPOINT                         ;
extern int MODBUS_WALL_SETPOINT                                ;
extern int MODBUS_CEILING_SETPOINT                             ;
extern int MODBUS_AVERAGE_SETPOINT                             ;
extern int MODBUS_UNOCCUPIED_HEATING                           ;
extern int MODBUS_UNOCCUPIED_COOLING                           ;
extern int MODBUS_RH_SETPOINT                                  ;
extern int MODBUS_CURRENT1_SETPOINT                            ;
extern int MODBUS_TEMP_SELECT                                  ;
extern int MODBUS_INPUT1_SELECT                                ;
extern int MODBUS_COOLING_PID                                  ;
extern int MODBUS_COOLING_PTERM                                ;
extern int MODBUS_COOLING_ITERM                                ;
extern int MODBUS_UNIVERSAL_PTERM                              ;
extern int MODBUS_UNIVERSAL_ITERM                              ;
extern int MODBUS_PID_UNIVERSAL                                ;
extern int MODBUS_UNITS1_HIGH                                  ;
extern int MODBUS_UNITS1_LOW                                   ;
extern int MODBUS_UNITS2_HIGH                                  ;
extern int MODBUS_UNITS2_LOW                                   ;
extern int MODBUS_PID2_MODE_OPERATION                          ;
extern int MODBUS_KEYPAD_SELECT                                ;
extern int MODBUS_SPECIAL_MENU_LOCK                            ;
extern int MODBUS_DISPLAY                                      ;
extern int MODBUS_ICON                                         ;
extern int MODBUS_LAST_KEY_TIMER                               ;
extern int MODBUS_KEYPAD_VALUE                                 ;
extern int MODBUS_DISPLAY_HUNDRED                              ;
extern int MODBUS_DISPLAY_TEN                                  ;
extern int MODBUS_DISPLAY_DIGITAL                              ;
extern int MODBUS_DISPLAY_STATUS                               ;
extern int MODBUS_ROUND_DISPLAY                                ;
extern int MODBUS_MIN_ADDRESS                                  ;
extern int MODBUS_MAX_ADDRESS                                  ;
extern int MODBUS_EEPROM_SIZE                                  ;
extern int MODBUS_TIMER_SELECT                                 ;
extern int MODBUS_YEAR                                         ;
extern int MODBUS_MONTH                                        ;
extern int MODBUS_WEEK                                         ;
extern int MODBUS_DAY                                          ;
extern int MODBUS_HOUR                                         ;
extern int MODBUS_MINUTE                                       ;
extern int MODBUS_SECOND                                       ;
extern int MODBUS_DIAGNOSTIC_ALARM                             ;
extern int MODBUS_DAY1_EVENT1_HI                               ;
extern int MODBUS_DAY1_EVENT1_LO                               ;
extern int MODBUS_DAY1_EVENT2_HI                               ;
extern int MODBUS_DAY1_EVENT2_LO                               ;
extern int MODBUS_DAY1_EVENT3_HI                               ;
extern int MODBUS_DAY1_EVENT3_LO                               ;
extern int MODBUS_DAY1_EVENT4_HI                               ;
extern int MODBUS_DAY1_EVENT4_LO                               ;
extern int MODBUS_DAY2_EVENT1_HI                               ;
extern int MODBUS_DAY2_EVENT1_LO                               ;
extern int MODBUS_DAY2_EVENT2_HI                               ;
extern int MODBUS_DAY2_EVENT2_LO                               ;
extern int MODBUS_DAY2_EVENT3_HI                               ;
extern int MODBUS_DAY2_EVENT3_LO                               ;
extern int MODBUS_DAY2_EVENT4_HI                               ;
extern int MODBUS_DAY2_EVENT4_LO                               ;
extern int MODBUS_LCD_TURN_OFF                                 ;
extern int MODBUS_LINE1_CHAR1                                  ;
extern int MODBUS_LINE1_CHAR2                                  ;
extern int MODBUS_LINE1_CHAR3                                  ;
extern int MODBUS_LINE1_CHAR4                                  ;
extern int MODBUS_LINE2_CHAR1                                  ;
extern int MODBUS_LINE2_CHAR2                                  ;
extern int MODBUS_LINE2_CHAR3                                  ;
extern int MODBUS_LINE2_CHAR4                                  ;
extern int MODBUS_INTERNAL_CHAR1                               ;
extern int MODBUS_INTERNAL_CHAR2                               ;
extern int MODBUS_INTERNAL_CHAR3                               ;
extern int MODBUS_INTERNAL_CHAR4                               ;
extern int MODBUS_AI1_CHAR1                                    ;
extern int MODBUS_AI1_CHAR2                                    ;
extern int MODBUS_AI1_CHAR3                                    ;
extern int MODBUS_AI1_CHAR4                                    ;
extern int MODBUS_AI2_CHAR1                                    ;
extern int MODBUS_AI2_CHAR2                                    ;
extern int MODBUS_AI2_CHAR3                                    ;
extern int MODBUS_AI2_CHAR4                                    ;
extern int MODBUS_AI3_CHAR1                                    ;
extern int MODBUS_AI3_CHAR2                                    ;
extern int MODBUS_AI3_CHAR3                                    ;
extern int MODBUS_AI3_CHAR4                                    ;
extern int MODBUS_AI4_CHAR1                                    ;
extern int MODBUS_AI4_CHAR2                                    ;
extern int MODBUS_AI4_CHAR3                                    ;
extern int MODBUS_AI4_CHAR4                                    ;
extern int MODBUS_AI5_CHAR1                                    ;
extern int MODBUS_AI5_CHAR2                                    ;
extern int MODBUS_AI5_CHAR3                                    ;
extern int MODBUS_AI5_CHAR4                                    ;
extern int MODBUS_AI6_CHAR1                                    ;
extern int MODBUS_AI6_CHAR2                                    ;
extern int MODBUS_AI6_CHAR3                                    ;
extern int MODBUS_AI6_CHAR4                                    ;
extern int MODBUS_AI7_CHAR1                                    ;
extern int MODBUS_AI7_CHAR2                                    ;
extern int MODBUS_AI7_CHAR3                                    ;
extern int MODBUS_AI7_CHAR4                                    ;
extern int MODBUS_AI8_CHAR1                                    ;
extern int MODBUS_AI8_CHAR2                                    ;
extern int MODBUS_AI8_CHAR3                                    ;
extern int MODBUS_AI8_CHAR4                                    ;
extern int MODBUS_OUTPUT1_CHAR1                                ;
extern int MODBUS_OUTPUT1_CHAR2                                ;
extern int MODBUS_OUTPUT1_CHAR3                                ;
extern int MODBUS_OUTPUT1_CHAR4                                ;
extern int MODBUS_OUTPUT2_CHAR1                                ;
extern int MODBUS_OUTPUT2_CHAR2                                ;
extern int MODBUS_OUTPUT2_CHAR3                                ;
extern int MODBUS_OUTPUT2_CHAR4                                ;
extern int MODBUS_OUTPUT3_CHAR1                                ;
extern int MODBUS_OUTPUT3_CHAR2                                ;
extern int MODBUS_OUTPUT3_CHAR3                                ;
extern int MODBUS_OUTPUT3_CHAR4                                ;
extern int MODBUS_OUTPUT4_CHAR1                                ;
extern int MODBUS_OUTPUT4_CHAR2                                ;
extern int MODBUS_OUTPUT4_CHAR3                                ;
extern int MODBUS_OUTPUT4_CHAR4                                ;
extern int MODBUS_OUTPUT5_CHAR1                                ;
extern int MODBUS_OUTPUT5_CHAR2                                ;
extern int MODBUS_OUTPUT5_CHAR3                                ;
extern int MODBUS_OUTPUT5_CHAR4                                ;
extern int MODBUS_OUTPUT6_CHAR1                                ;
extern int MODBUS_OUTPUT6_CHAR2                                ;
extern int MODBUS_OUTPUT6_CHAR3                                ;
extern int MODBUS_OUTPUT6_CHAR4                                ;
extern int MODBUS_OUTPUT7_CHAR1                                ;
extern int MODBUS_OUTPUT7_CHAR2                                ;
extern int MODBUS_OUTPUT7_CHAR3                                ;
extern int MODBUS_OUTPUT7_CHAR4                                ;
extern int MODBUS_SCHEDULEA_CHAR1                              ;
extern int MODBUS_SCHEDULEA_CHAR2                              ;
extern int MODBUS_SCHEDULEA_CHAR3                              ;
extern int MODBUS_SCHEDULEA_CHAR4                              ;
extern int MODBUS_SCHEDULEB_CHAR1                              ;
extern int MODBUS_SCHEDULEB_CHAR2                              ;
extern int MODBUS_SCHEDULEB_CHAR3                              ;
extern int MODBUS_SCHEDULEB_CHAR4                              ;
extern int MODBUS_SCHEDULEC_CHAR1                              ;
extern int MODBUS_SCHEDULEC_CHAR2                              ;
extern int MODBUS_SCHEDULEC_CHAR3                              ;
extern int MODBUS_SCHEDULEC_CHAR4                              ;
extern int MODBUS_SCHEDULED_CHAR1                              ;
extern int MODBUS_SCHEDULED_CHAR2                              ;
extern int MODBUS_SCHEDULED_CHAR3                              ;
extern int MODBUS_SCHEDULED_CHAR4                              ;
extern int MODBUS_WALL_CHAR1                                   ;
extern int MODBUS_WALL_CHAR2                                   ;
extern int MODBUS_WALL_CHAR3                                   ;
extern int MODBUS_WALL_CHAR4                                   ;
extern int MODBUS_CEILING_CHAR1                                ;
extern int MODBUS_CEILING_CHAR2                                ;
extern int MODBUS_CEILING_CHAR3                                ;
extern int MODBUS_CEILING_CHAR4                                ;
extern int MODBUS_OUTDOOR_CHAR1                                ;
extern int MODBUS_OUTDOOR_CHAR2                                ;
extern int MODBUS_OUTDOOR_CHAR3                                ;
extern int MODBUS_OUTDOOR_CHAR4                                ;
extern int MODBUS_AVERAGE_CHAR1                                ;
extern int MODBUS_AVERAGE_CHAR2                                ;
extern int MODBUS_AVERAGE_CHAR3                                ;
extern int MODBUS_AVERAGE_CHAR4                                ;
extern int MODBUS_LCD_SCREEN1                                  ;
extern int MODBUS_LCD_SCREEN2                                  ;
extern int MODBUS_DEMAND_RESPONSE                              ;
extern int MODBUS_LOCK_REGISTER                                ;
extern int MODBUS_PIR_STAGE                                    ;
extern int MODBUS_FIRST_CAL_FLAG                               ;
extern int MODBUS_HUM_CAL_EREASE                               ;
extern int MODBUS_HUMCOUNT3_H                                  ;
extern int MODBUS_HUMRH3_H                                     ;
extern int MODBUS_HUMCOUNT4_H                                  ;
extern int MODBUS_HUMRH4_H                                     ;
extern int MODBUS_HUMCOUNT5_H                                  ;
extern int MODBUS_HUMRH5_H                                     ;
extern int MODBUS_HUMCOUNT6_H                                  ;
extern int MODBUS_HUMRH6_H                                     ;
extern int MODBUS_HUMCOUNT7_H                                  ;
extern int MODBUS_HUMRH7_H                                     ;
extern int MODBUS_HUMCOUNT8_H                                  ;
extern int MODBUS_HUMRH8_H                                     ;
extern int MODBUS_HUMCOUNT9_H                                  ;
extern int MODBUS_HUMRH9_H                                     ;
extern int MODBUS_HUMCOUNT10_H                                 ;
extern int MODBUS_HUMRH10_H                                    ;
extern int MODBUS_HUM_LOCK_A                                   ;
extern int MODBUS_HUM_LOCK_B                                   ;
extern int MODBUS_LCD_ROTATE_ENABLE                            ;
extern int MODBUS_SCHEDULE_ON_OFF                              ;
extern int MODBUS_DISP_ITEM_TEMPERATURE                        ;
extern int MODBUS_DISP_ITEM_SETPOINT                           ;
extern int MODBUS_DISP_ITEM_AI1                                ;
extern int MODBUS_DISP_ITEM_AI2                                ;
extern int MODBUS_DISP_ITEM_AI3                                ;
extern int MODBUS_DISP_ITEM_AI4                                ;
extern int MODBUS_DISP_ITEM_AI5                                ;
extern int MODBUS_DISP_ITEM_AI6                                ;
extern int MODBUS_DISP_ITEM_AI7                                ;
extern int MODBUS_DISP_ITEM_AI8                                ;
extern int MODBUS_DISP_ITEM_MODE                               ;
extern int MODBUS_DISP_ITEM_USER_INFO                          ;
extern int MODBUS_DISP_ITEM_CLOCK_DATE                         ;
extern int MODBUS_DISP_ITEM_CLOCK_TIME                         ;
extern int MODBUS_DISP_ITEM_EXTENAL_SENSOR1                    ;
extern int MODBUS_DISP_ITEM_EXTENAL_SENSOR2                    ;
extern int MODBUS_DISP_ITEM_EXTENAL_SENSOR3                    ;
extern int MODBUS_DISP_ITEM_EXTENAL_SENSOR4                    ;
extern int MODBUS_DISP_ITEM_OUT1                               ;
extern int MODBUS_DISP_ITEM_OUT2                               ;
extern int MODBUS_DISP_ITEM_OUT3                               ;
extern int MODBUS_DISP_ITEM_OUT4                               ;
extern int MODBUS_DISP_ITEM_OUT5                               ;
extern int MODBUS_DISP_ITEM_OUT6                               ;
extern int MODBUS_DISP_ITEM_OUT7                               ;
extern int MODBUS_OUTPUT_PWM_AUTO_COAST                        ;
extern int MODBUS_OUTPUT_PWM_AUTO_COOL1                        ;
extern int MODBUS_OUTPUT_PWM_AUTO_COOL2                        ;
extern int MODBUS_OUTPUT_PWM_AUTO_COOL3                        ;
extern int MODBUS_OUTPUT_PWM_AUTO_HEAT1                        ;
extern int MODBUS_OUTPUT_PWM_AUTO_HEAT2                        ;
extern int MODBUS_OUTPUT_PWM_AUTO_HEAT3                        ;
extern int MODBUS_PWM_OUT4                                     ;
extern int MODBUS_PWM_OUT5                                     ;
extern int MODBUS_SUN_ICON_CONTROL                             ;
extern int MODBUS_MOON_ICON_CONTROL                            ;
extern int MODBUS_EXT_SENSOR_TEMP_CAL                          ;
extern int MODBUS_BUTTON_LEFT1                                 ;
extern int MODBUS_BUTTON_LEFT2                                 ;
extern int MODBUS_BUTTON_LEFT3                                 ;
extern int MODBUS_BUTTON_LEFT4                                 ;


extern int MODBUS_HUM_HEATER_CONTROL_ENABLE;
extern int MODBUS_HUM_INPUT_MANUAL_ENABLE;
extern int MODBUS_HUM_INPUT_MANUAL_VALUE;                             
extern int MODBUS_CO2_INPUT_MANUAL_ENABLE;                            
extern int MODBUS_CO2_INPUT_VALUE    ;                                
extern int MODBUS_CO2_CALIBRATION_DATA   ;                           
extern int MODBUS_UNIVERSAL_OFF_OUTPUT_BEGIN       ;                  
extern int MODBUS_UNIVERSAL_OFF_OUTPUT_COOL1   ;                      
extern int MODBUS_UNIVERSAL_OFF_OUTPUT_COOL2  ;                       
extern int MODBUS_UNIVERSAL_OFF_OUTPUT_COOL3   ;                      
extern int MODBUS_UNIVERSAL_OFF_OUTPUT_HEAT1  ;                       
extern int MODBUS_UNIVERSAL_OFF_OUTPUT_HEAT2  ;                       
extern int MODBUS_UNIVERSAL_OFF_OUTPUT_HEAT3 ;                       
extern int MODBUS_UNIVERSAL_OFF_VALVE_BEGIN ;                        
extern int MODBUS_UNIVERSAL_OFF_VALVE_COOL1;                          
extern int MODBUS_UNIVERSAL_OFF_VALVE_COOL2 ;                         
extern int MODBUS_UNIVERSAL_OFF_VALVE_COOL3   ;                       
extern int MODBUS_UNIVERSAL_OFF_VALVE_HEAT1   ;                       
extern int MODBUS_UNIVERSAL_OFF_VALVE_HEAT2   ;                       
extern int MODBUS_UNIVERSAL_OFF_VALVE_HEAT3   ;                      

extern int MODBUS_VALUE_SENSOR        ;                             
extern int MODBUS_PIR_SELECT_ENABLE      ;                           
extern int MODBUS_PIR_REAL_VALUE    ;                                 
extern int MODBUS_PIR_OCCUPIED      ;                                 
                            


extern int MODBUS_HEATING_PID                                  ;
extern int MODBUS_CALIBRATION                                  ;
extern int MODBUS_CALIBRATION_ANALOG_IN1                       ;
extern int MODBUS_DELAY                                        ;
extern int MODBUS_HEATING_PTERM                                ;
extern int MODBUS_HEATING_ITERM                                ;
extern int MODBUS_COOLING_DEADBAND                             ;
extern int MODBUS_HEATING_DEADBAND                             ;
extern int MODBUS_OUTPUT_SCALE                                 ;
extern int MODBUS_COOLING_SETPOINT                             ;
extern int MODBUS_HEATING_SETPOINT                             ;
extern int MODBUS_EXTERNAL_SENSOR_0                            ;
extern int MODBUS_EXTERNAL_SENSOR_1                            ;
extern int MODBUS_ANALOG_IN1                                   ;
extern int MODBUS_ANALOG_IN2                                   ;
extern int MODBUS_DIGITAL_IN1                                  ;
extern int MODBUS_LED1_CONTROL                                 ;
extern int MODBUS_LED2_CONTROL                                 ;
extern int MODBUS_LED3_CONTROL                                 ;
extern int MODBUS_LED4_CONTROL                                 ;
extern int MODBUS_LED5_CONTROL                                 ;
extern int MODBUS_LED6_CONTROL                                 ;
extern int MODBUS_LED7_CONTROL                                 ;
extern int MODBUS_INTERNAL_TEMP_IC                             ;
extern int MODBUS_CALIBRATION_ANALOG_IN2                       ;
extern int MODBUS_UNIVERSAL_VALVE_BEGIN                        ;
extern int MODBUS_UNIVERSAL_VALVE_COOL1                        ;
extern int MODBUS_UNIVERSAL_VALVE_COOL2                        ;
extern int MODBUS_UNIVERSAL_VALVE_COOL3                        ;
extern int MODBUS_UNIVERSAL_VALVE_HEAT1                        ;
extern int MODBUS_UNIVERSAL_VALVE_HEAT2                        ;
extern int MODBUS_UNIVERSAL_VALVE_HEAT3                        ;
extern int MODBUS_DIGITAL1_FUNCTION                            ;
extern int MODBUS_DIGITAL_INPUT                                ;
extern int MODBUS_DEBUGTIMER                                   ;
extern int MODBUS_FAN_GRIDPOINT                                ;
extern int MODBUS_MODE_GRIDPOINT                               ;
extern int MODBUS_HOLD_GRIDPOINT                               ;
extern int MODBUS_CONFIGURATION                                ;
extern int MODBUS_UTIL_MODE                                    ;
extern int MODBUS_ROTATION_OUT2                                ;
extern int MODBUS_ROTATION_OUT3                                ;
extern int MODBUS_ROTATION_OUT4                                ;
extern int MODBUS_ROTATION_OUT5                                ;
extern int MODBUS_ROTATION_TIME_LEFT                           ;
extern int MODBUS_FREE_COOL_OUT_TEMP                           ;
extern int MODBUS_NC_MASTER_TIME                               ;
extern int MODBUS_FREE_COOL_HYSTERISIS                         ;
extern int MODBUS_OUTPUT_FREE_COOL_COAST                       ;
extern int MODBUS_OUTPUT_FREE_COOL_COOL1                       ;
extern int MODBUS_OUTPUT_FREE_COOL_COOL2                       ;
extern int MODBUS_OUTPUT_FREE_COOL_COOL3                       ;
extern int MODBUS_OUTPUT_FREE_COOL_HEAT1                       ;
extern int MODBUS_OUTPUT_FREE_COOL_HEAT2                       ;
extern int MODBUS_OUTPUT_FREE_COOL_HEAT3                       ;
extern int MODBUS_MIN_AIR                                      ;
extern int MODBUS_OAT_HOTTEST                                  ;
extern int MODBUS_OAT_COLDEST                                  ;
extern int MODBUS_OFFSET_HOTTEST                               ;
extern int MODBUS_OFFSET_COLDEST                               ;
extern int MODBUS_TWO_BYTE_SETPOINT                            ;
extern int MODBUS_CURRENT_SETPOINT                             ;
extern int MODBUS_SETPOINT_OFFSET                              ;
extern int MODBUS_CHANGEOVER_SENSOR_MODE                       ;
extern int MODBUS_EXTERNAL_SENSOR_INUSE                        ;
extern int MODBUS_EXTERNAL_SENSOR_STATUS                       ;
extern int MODBUS_NEW_COOLING_SETPOINT                         ;
extern int MODBUS_LINE1_CHAR5                                  ;
extern int MODBUS_LINE1_CHAR6                                  ;
extern int MODBUS_LINE1_CHAR7                                  ;
extern int MODBUS_LINE1_CHAR8                                  ;
extern int MODBUS_WINDOW_INTERLOCK_DELAY                       ;
extern int MODBUS_LINE2_CHAR5                                  ;
extern int MODBUS_LINE2_CHAR6                                  ;
extern int MODBUS_LINE2_CHAR7                                  ;
extern int MODBUS_LINE2_CHAR8                                  ;
extern int MODBUS_DURA_WINTER_SUMMER                           ;
extern int MODBUS_FREE_COOL_SETPOINT                           ;
extern int MODBUS_FREE_COOL_MAX_SETPOINT                       ;
extern int MODBUS_FREE_COOL_MIN_SETPOINT                       ;
extern int MODBUS_FREE_COOL_MIN_DAMPER                         ;
extern int MODBUS_HEAT_COOL                                    ;
extern int MODBUS_TURN_OFF_FAN                                 ;
extern int MODBUS_UI_LINE1_CHAR1                               ;
extern int MODBUS_UI_LINE1_CHAR2                               ;
extern int MODBUS_UI_LINE1_CHAR3                               ;
extern int MODBUS_UI_LINE1_CHAR4                               ;
extern int MODBUS_UI_LINE2_CHAR1                               ;
extern int MODBUS_UI_LINE2_CHAR2                               ;
extern int MODBUS_UI_LINE2_CHAR3                               ;
extern int MODBUS_UI_LINE2_CHAR4                               ;
extern int MODBUS_UI_INTERNAL_CHAR1                            ;
extern int MODBUS_UI_INTERNAL_CHAR2                            ;
extern int MODBUS_UI_INTERNAL_CHAR3                            ;
extern int MODBUS_UI_INTERNAL_CHAR4                            ;
extern int MODBUS_UI_AI1_CHAR1                                 ;
extern int MODBUS_UI_AI1_CHAR2                                 ;
extern int MODBUS_UI_AI1_CHAR3                                 ;
extern int MODBUS_UI_AI1_CHAR4                                 ;
extern int MODBUS_UI_AI2_CHAR1                                 ;
extern int MODBUS_UI_AI2_CHAR2                                 ;
extern int MODBUS_UI_AI2_CHAR3                                 ;
extern int MODBUS_UI_AI2_CHAR4                                 ;
extern int MODBUS_UI_AI3_CHAR1                                 ;
extern int MODBUS_UI_AI3_CHAR2                                 ;
extern int MODBUS_UI_AI3_CHAR3                                 ;
extern int MODBUS_UI_AI3_CHAR4                                 ;
extern int MODBUS_UI_AI4_CHAR1                                 ;
extern int MODBUS_UI_AI4_CHAR2                                 ;
extern int MODBUS_UI_AI4_CHAR3                                 ;
extern int MODBUS_UI_AI4_CHAR4                                 ;
extern int MODBUS_UI_AI5_CHAR1                                 ;
extern int MODBUS_UI_AI5_CHAR2                                 ;
extern int MODBUS_UI_AI5_CHAR3                                 ;
extern int MODBUS_UI_AI5_CHAR4                                 ;
extern int MODBUS_UI_AI6_CHAR1                                 ;
extern int MODBUS_UI_AI6_CHAR2                                 ;
extern int MODBUS_UI_AI6_CHAR3                                 ;
extern int MODBUS_UI_AI6_CHAR4                                 ;
extern int MODBUS_UI_AI7_CHAR1                                 ;
extern int MODBUS_UI_AI7_CHAR2                                 ;
extern int MODBUS_UI_AI7_CHAR3                                 ;
extern int MODBUS_UI_AI7_CHAR4                                 ;
extern int MODBUS_UI_AI8_CHAR1                                 ;
extern int MODBUS_UI_AI8_CHAR2                                 ;
extern int MODBUS_UI_AI8_CHAR3                                 ;
extern int MODBUS_UI_AI8_CHAR4                                 ;
extern int MODBUS_WINDOW_HEATING_SETPOINT                      ;
extern int MODBUS_WINDOW_COOLING_SETPOINT                      ;
extern int MODBUS_RELAY_PWM_ENABLE                             ;
extern int MODBUS_RELAY_PWM_TOTAL_DUTY                         ;
extern int MODBUS_RELAY_PWM_HIGH_DUTY                          ;
   
extern	int	MODBUS_SUPPLY_SETPOINT	;
extern	int	MODBUS_MAX_SUPPLY_SETPOINT	;
extern	int	MODBUS_MIN_SUPPLY_SETPOINT	;
extern	int	MODBUS_MAX_AIRFLOW_COOLING	;
extern	int	MODBUS_MAX_AIRFLOW_HEATING	;
extern	int	MODBUS_MIN_AIRFLOW	;
extern	int	MODBUS_AIRFLOW_SETPOINT 	;
extern	int	MODBUS_VAV_CONTROL	;
extern	int	MODBUS_SUPPLY_TEMP_SELECT	;
extern	int	MODBUS_PID3_VALVE_OPERATION_TABLE_BEGIN 	;
extern	int	MODBUS_PID3_VALVE_OPER_TABLE_COOL1	;
extern	int	MODBUS_PID3_VALVE_OPER_TABLE_COOL2	;
extern	int	MODBUS_PID3_VALVE_OPER_TABLE_COOL3	;
extern	int	MODBUS_PID3_VALVE_OPER_TABLE_HEAT1	;
extern	int	MODBUS_PID3_VALVE_OPER_TABLE_HEAT2	;
extern	int	MODBUS_PID3_VALVE_OPER_TABLE_HEAT3	;
extern	int	MODBUS_PID3_COOLING_DB	;
extern	int	MODBUS_PID3_HEATING_DB	;
extern	int	MODBUS_PID3_PTERM	;
extern	int	MODBUS_PID3_ITERM	;
extern	int	MODBUS_PID3_HEAT_STAGE	;
extern	int	MODBUS_PID3_COOL_STAGE	;
extern	int	MODBUS_PID3_OUTPUT	;
extern	int	MODBUS_PID3_OUTPUT_BEGIN	;
extern	int	MODBUS_PID3_OUTPUT_COOL1	;
extern	int	MODBUS_PID3_OUTPUT_COOL2	;
extern	int	MODBUS_PID3_OUTPUT_COOL3	;
extern	int	MODBUS_PID3_OUTPUT_HEAT1	;
extern	int	MODBUS_PID3_OUTPUT_HEAT2	;
extern	int	MODBUS_PID3_OUTPUT_HEAT3	;
//extern	int	MODBUS_OUTPUT6_FUNCTION		;
//extern	int	MODBUS_OUTPUT7_FUNCTION		;
//extern	int	MODBUS_ANALOG3_FUNCTION		;
//extern	int	MODBUS_ANALOG4_FUNCTION		;
//extern	int	MODBUS_ANALOG5_FUNCTION		;
//extern	int	MODBUS_ANALOG6_FUNCTION		;
//extern	int	MODBUS_ANALOG7_FUNCTION		;
extern	int	MODBUS_PID3_VALVE_OFF_TABLE_BEGIN  ;
extern	int	MODBUS_PID3_VALVE_OFF_TABLE_COOL1  ;
extern	int	MODBUS_PID3_VALVE_OFF_TABLE_COOL2  ;
extern	int	MODBUS_PID3_VALVE_OFF_TABLE_COOL3  ;
extern	int	MODBUS_PID3_VALVE_OFF_TABLE_HEAT1  ;
extern	int	MODBUS_PID3_VALVE_OFF_TABLE_HEAT2  ;
extern	int	MODBUS_PID3_VALVE_OFF_TABLE_HEAT3  ;
extern	int	MODBUS_PID3_OFF_OUTPUT_BEGIN	   ;
extern	int	MODBUS_PID3_OFF_OUTPUT_COOL1	   ;
extern	int	MODBUS_PID3_OFF_OUTPUT_COOL2	   ;
extern	int	MODBUS_PID3_OFF_OUTPUT_COOL3	   ;
extern	int	MODBUS_PID3_OFF_OUTPUT_HEAT1	   ;
extern	int	MODBUS_PID3_OFF_OUTPUT_HEAT2	   ;
extern	int	MODBUS_PID3_OFF_OUTPUT_HEAT3	   ;
extern int MODBUS_HEAT_COOL_MODE ;
extern int MODBUS_PID3_DAY_SETPOINT;
extern int MODBUS_PID3_NIGHT_SETPOINT;
extern int MODBUS_PID_D_TERM ;
extern int MODBUS_PID_SAMPLE_TIME ;

extern int selected_product_index;
extern HTREEITEM selected_tree_item;
#pragma region For_bacnet

extern CString temp_off[BAC_CUSTOMER_UNITS_COUNT];		//用于 保存 客户自定义的 单位;
extern CString temp_on[BAC_CUSTOMER_UNITS_COUNT];
extern CString temp_unit[BAC_CUSTOMER_UNITS_COUNT];
extern CString Custom_Digital_Range[BAC_CUSTOMER_UNITS_COUNT];
extern bool read_var_analog_cus_units;          //Var Cus units 自定义
extern bool read_customer_unit;	//如果这个设备没有读过 customer unit这一项,就要尝试去读，以前老版本的没有;
extern bool receive_customer_unit; //收到回复，flag就置 true;
extern bool read_analog_customer_unit;  // 这个是模拟的cus tabel ;
extern CString Analog_Customer_Units[BAC_ALALOG_CUSTMER_RANGE_TABLE_COUNT];
extern CString Analog_Variable_Units[BAC_VARIABLE_CUS_UNIT_COUNT];
extern unsigned char bacnet_add_id[254];
extern int bacnet_device_type;
extern int g_bac_instance;
extern unsigned int g_sub_instace;
extern unsigned int g_selected_serialnumber;
extern unsigned int g_selected_product_id;
extern unsigned short g_mac;
extern HWND MainFram_hwd;
extern HWND BacNet_hwd;//Used for send a message to father delete the dlg;
extern int bac_ranges_type;
extern int bac_range_number_choose;

extern int bac_program_pool_size;
extern int bac_program_size;
extern int bac_free_memory;
extern int bac_read_which_list;
extern bool bac_read_all_results;
extern bool bac_input_read_results;
extern bool bac_output_read_results;
extern bool bac_variable_read_results;
extern bool bac_program_read_results;
extern bool bac_weekly_read_results;
extern bool bac_annual_read_results;
extern bool bac_time_command_read_results;
extern bool bac_controller_read_results;
extern bool bac_screen_read_results;
extern bool bac_monitor_read_results;
extern bool bac_programcode_read_results;
extern bool bac_weeklycode_read_results;
extern bool bac_annualcode_read_results;
extern bool bac_alarmlog_read_results;
extern bool bac_tstat_read_results;
extern bool bac_basic_setting_read_results;
extern bool bac_customer_unit_read_results;
extern bool bac_user_login_read_results;
extern bool bac_graphic_label_read_results;
extern bool bac_remote_point_read_results;
extern bool bac_cm5_graphic;

extern int bac_gloab_panel;

extern int input_list_line;
extern int output_list_line;
extern int program_list_line ;
extern int weekly_list_line ;
extern int annual_list_line ;
extern int screen_list_line ;
extern int monitor_list_line;
extern int analog_range_tbl_line;
extern Time_block_mini Device_time;
extern int ext_io_list_line;

extern HWND      g_hwnd_now;
extern HWND      m_input_dlg_hwnd;
extern HWND      m_output_dlg_hwnd;
extern HWND      m_pragram_dlg_hwnd;
extern HWND      m_program_edit_hwnd;
extern HWND      m_variable_dlg_hwnd;
extern HWND      m_weekly_dlg_hwnd;
extern HWND      m_annual_dlg_hwnd;
extern HWND      m_schedule_time_dlg_hwnd;
extern HWND      m_schedule_day_dlg_hwnd;
extern HWND      m_controller_dlg_hwnd;
extern HWND      m_screen_dlg_hwnd;
extern HWND		 m_screenedit_dlg_hwnd;
extern HWND	     m_monitor_dlg_hwnd;
extern HWND	     m_alarmlog_dlg_hwnd;
extern HWND      m_alarmwindow_dlg_hwnd;
extern HWND      m_tstat_dlg_hwnd;
extern HWND      m_setting_dlg_hwnd;
extern HWND      m_flash_multy_hwnd;
extern HWND      m_customer_digital_range_dlg_hwnd;
extern HWND      m_scan_dlg_hwnd;
extern HWND	     m_tcp_server_hwnd;
extern HWND      m_user_login_hwnd;
extern HWND      m_user_config_hwnd;
extern HWND      m_add_label;
extern HWND      m_edit_label;
extern HWND      m_at_command_hwnd;
extern HWND      m_remote_point_hwnd;
extern HWND		 m_program_debug_list_hwnd;
extern HWND		 m_statusbar_hwnd ;
extern HWND	     m_ext_io_dlg_hwmd ;
extern HWND		 analog_cus_range_dlg;
extern HWND      m_tstat_schedule_dlg_hwnd ;
extern HWND      m_t3000_log_window ;
extern vector <Str_out_point> m_Output_data;
extern vector <Str_in_point>  m_Input_data;
extern vector <Str_program_point>  m_Program_data;
extern vector <Str_variable_point>  m_Variable_data;
extern vector <Str_weekly_routine_point> m_Weekly_data;
extern vector <Str_annual_routine_point> m_Annual_data;
extern vector <Str_schedual_time_point> m_Schedual_Time_data;
extern vector <Str_controller_point> m_controller_data;
extern vector <Control_group_point> m_screen_data;
extern vector <Str_tstat_schedule> m_tatat_schedule_data;
extern vector <Str_monitor_point> m_monitor_data;
extern vector <_Bac_Scan_Com_Info> m_bac_handle_Iam_data;
extern vector <_Graphic_Value_Info> m_graphic_refresh_data;
extern vector <_Bac_Scan_results_Info> m_bac_scan_result_data;
extern vector <Alarm_point> m_alarmlog_data;
extern vector <refresh_net_device> m_refresh_net_device_data;
extern vector <refresh_net_device> m_T3BB_device_data;
extern vector <Str_TstatInfo_point> m_Tstat_data;
extern vector <Str_Remote_TstDB> m_remote_device_db;
extern vector <Str_Units_element> m_customer_unit_data;
extern vector <Str_userlogin_point> m_user_login_data;
extern vector <Str_table_point> m_analog_custmer_range;
extern vector <Str_variable_uint_point> m_variable_analog_unite;
extern vector <Str_Extio_point> m_extio_config_data;

extern vector <GSM_connection_info> m_gsm_connect_info;
extern vector <Scan_Info> m_scan_info;
extern vector <Scan_Info> m_scan_info_buffer;
extern vector <Client_Info> m_tcp_connect_info;
extern vector <Str_label_point> m_graphic_label_data;	//图片里面的Label的信息要存在设备里面;
extern vector <Str_remote_point> m_remote_point_data;  //Mini panel 里面Tstat 远端点的 值;
extern Str_Setting_Info Device_Basic_Setting;
extern Str_MISC Device_Misc_Data;
extern Str_Special Device_Special_Data;
extern char m_at_write_buf[100];
extern char m_at_read_buf[450];

extern Monitor_Block m_monitor_block;
extern Str_Monitor_data_header m_monitor_head;
extern char picture_data_buffer[400]; //用来存每包 pic 的数据.
extern Str_picture_header m_picture_head; //传图片的 头，结构其实是和 monitor same.
extern int Monitor_Input__Data[14][1000];
extern unsigned char weeklt_time_schedule[BAC_SCHEDULE_COUNT][WEEKLY_SCHEDULE_SIZE + 1];
extern unsigned char program_code[BAC_PROGRAM_ITEM_COUNT][2000];//暂定2000;
extern int program_code_length[BAC_PROGRAM_ITEM_COUNT];

extern int controller_counter ; //记录扫描的子节点
extern CString bac_cs_mac;
extern CString bac_cs_device_id;
//extern CString bac_cs_vendor_id;
extern HANDLE CM5_hThread;
extern HANDLE CM5_UI_Thread;
extern DWORD nThreadID_x;
extern DWORD cm5_nThreadID;
extern int g_protocol;
extern int g_bac_read_type;
extern bool g_bac_need_read_setting;  //如果是第一次点击 需要读Setting里面的 数据;判断是否需要更改Label之类的;
extern HANDLE click_read_thread;
extern bool bac_net_initial_once;
extern unsigned char my_ip[4];
extern byte	g_DayState[8][ANNUAL_CODE_SIZE];
extern CDialog *pDialog[14];
extern CDialog *DebugWindow;
extern CDialog *T3000LogWindow;
extern CDialog *Tcp_Server_Window;
extern CString PrintText[1000];
extern CString g_Print;
extern HWND h_debug_window;
extern unsigned long timesec1970; 
extern unsigned long timestart;   
extern bool range_cancel;//用于监测Range 对话框是否正常修改，如果正常修改就为0，否则就为1;
extern int connect_invoke_id ;
//extern bool connect_replay ;
extern BACNET_OBJECT_PROPERTY_VALUE receive_object_value;  /* for bacapp printing */
extern bool bac_show_alarm_window ;	//used for judge whether need to show the alarm window.
extern bool bac_select_device_online ; //判断选中的bacnet device 是否在线;
extern SOCKET h_Broad;
extern SOCKADDR_IN h_siBind;
extern SOCKADDR_IN h_bcast;

extern vector <int> exsit_panel_number;
 
extern Point_Data_str digital_last_data[MAX_POINTS_IN_MONITOR];
extern Data_Time_Match * digital_data_point[MAX_POINTS_IN_MONITOR];
extern Data_Time_Match * analog_data_point[MAX_POINTS_IN_MONITOR];
extern int analog_data_max_value[MAX_POINTS_IN_MONITOR];
extern int analog_data_min_value[MAX_POINTS_IN_MONITOR];
extern int digital_data_count[MAX_POINTS_IN_MONITOR];	//用于记录digital data 这个指针到底存了多少数据;
extern int analog_data_count[MAX_POINTS_IN_MONITOR];
extern int get_data_count ;
extern int monitor_analog_count ;	//暂存monitor 的模拟和数字的个数;
extern int monitor_digital_count ;
extern Data_Time_Match * temp_analog_data[MAX_POINTS_IN_MONITOR];
extern int SEND_COMMAND_DELAY_TIME ;
extern bool TCP_Server_Running ;
extern bool Gsm_communication ;	//如果是通过GSM 读远程设备 许多地方要特殊处理;不能刷新太频繁;
extern CString SaveConfigFilePath;
extern CString LoadConfigFilePath;
extern vector<ALL_LOCAL_SUBNET_NODE> g_Vector_Subnet;
extern vector<ALL_LOCAL_SUBNET_NODE> g_Scan_Vector_Subnet;
extern vector<Reg_Infor> g_Vector_Write_Error;
extern CString g_strStartInterface_config;
extern bool need_read_bacnet_graphic_label_flag;
extern bool read_write_bacnet_config ;	//读写Bacnet config 的时候禁止刷新 List;

extern int g_SleepTimeForConfig;
extern vector <Tstat_Input_Struct> m_tstat_input_data;

extern vector <Tstat_Output_Struct> m_tstat_output_data;
extern CString analog_range[11];
extern CString analog_range_TSTAT6[15];
extern CString INPUT_FUNS[13];
extern CString Interlock[6];
extern CString ONTPUT_FUNS[];

extern CString OUTPUT_RANGE5[3];
extern CString OUTPUT_RANGE45[4];
extern CString OUTPUT_ANRANGE6[];
extern CString OUTPUT_ANRANGE[];


extern AddressMap TSTAT_6_ADDRESS[2000];
extern AddressMap TSTAT_5EH_LCD_ADDRESS[2000];
extern AddressMap TSTAT_5ABCDFG_LED_ADDRESS[2000];

extern AddressMap T3_8AI8AO[T3_REG_TOTAL_COUNT];
extern AddressMap T3_8AI16O[T3_REG_TOTAL_COUNT];
extern AddressMap T3_32AI[T3_REG_TOTAL_COUNT];
extern AddressMap T3_Performance[T3_REG_TOTAL_COUNT];
extern AddressMap T3_4AO[T3_REG_TOTAL_COUNT];
extern AddressMap T3_6CT[T3_REG_TOTAL_COUNT];
extern AddressMap T3_28IN[T3_REG_TOTAL_COUNT];
extern AddressMap T3_RTD[T3_REG_TOTAL_COUNT];
extern AddressMap T3_8I13O[T3_REG_TOTAL_COUNT];

extern int current_building_protocol;
extern int current_building_comport;
extern int current_building_baudrate;
extern int current_building_ip;
extern int current_building_ipport;

extern int m_user_level;

extern CString Statuspanel;   //在状态栏显示panel 2-3;

extern CString CS3000_INPUT_RANGE[4];
extern BOOL g_NEED_MULTI_READ;
extern CString STRING_SWITCH_STATUS[3];

extern vector <IspModeInfo> g_isp_device_info;
extern IspModeInfo need_isp_device;
extern vector<Registers_Infor> g_vectRegisters;
extern CString g_cstring_ini_path;
extern unsigned char product_sort_way;		//0 default   1 by connection      2 bu floor
extern BOOL g_fresh_Graphic;
extern bool b_stop_read_grp_label;		//如果读到空的grp label 就不要继续读下一个了;
extern bool b_stop_read_tstat_schedule;	    //如果读到空的tstat 就不要继续读下一个了;

extern Global_Calibration_Module   g_calibration_module_data;
 extern CDialog *g_Draw_dlg;
extern unsigned int g_progress_persent ;	//用来记录全局状态栏该显示的 进度 百分比;
extern int input_item_limit_count;	//input list 要显示多少个input 的个数， 不是根据vector 的size 来判断大小;
extern int output_item_limit_count;	//output list 要显示多少个output 的个数， 不是根据vector 的size 来判断大小;
extern int variable_item_limit_count;	//variable list 要显示多少个variable 的个数， 不是根据vector 的size 来判断大小;
extern int program_item_limit_count ;
extern int controller_item_limit_count ;
extern int screen_item_limit_count ;

extern Str_out_point m_temp_output_data[BAC_OUTPUT_ITEM_COUNT];
extern Str_in_point m_temp_Input_data[BAC_INPUT_ITEM_COUNT];
extern Str_variable_point m_temp_variable_data[BAC_VARIABLE_ITEM_COUNT];
extern Str_program_point m_temp_program_data[BAC_PROGRAM_ITEM_COUNT];
extern Str_controller_point m_temp_controller_data[BAC_PID_COUNT];
extern Control_group_point m_temp_screen_data[BAC_SCREEN_COUNT];
extern Str_weekly_routine_point m_temp_weekly_data[BAC_SCHEDULE_COUNT];
extern Str_annual_routine_point m_temp_annual_data[BAC_HOLIDAY_COUNT];
extern Str_monitor_point m_temp_monitor_data[BAC_MONITOR_COUNT];
extern Alarm_point	 m_temp_alarmlog_data[BAC_ALARMLOG_COUNT];

extern int debug_item_show;

extern char monitor_database_flag[24];   //用于标记哪些Database需要删除的 ，1 为删除;
extern int Station_NUM;
extern bool monitor_ignore_enable ;
extern int monitor_ignore_max_value ;
extern int monitor_ignore_min_value ;
extern int persent_array_count;
extern	unsigned int old_tx_count;
extern int flash_multi_auto ; //用于控制 多烧的  自动控制;
extern unsigned int T3000_Version ; //T3000的版本号.
extern HANDLE read_each_485_fun_thread ;
extern bool hide_485_progress ;
extern bool new_device_support_mini_ui;

extern int flag_auto_scroll ; // 如果客户有指定显示X轴的某些事件 此 变量会为 1;否则显示最新数据;
extern int graphic_last_scale_type ; //用于存储上次 有效的 X轴的 刻度;
extern unsigned int graphic_last_time_value; //x轴上次查看的时间;
extern const CString c_strBaudate[NUMBER_BAUDRATE];
#pragma endregion For_bacnet

extern int global_interface; //用来标识全局的界面在哪？主要是 Input 和 output;
extern bool b_remote_connection;  //全局的 用来判断 对远程设备的 特殊处理;
extern bool refresh_tree_status_immediately ;	//如果置为true了，就会立即调用 刷新 ，不用等待一个周期，用于 某些IP或状态变了，立即刷新;
extern unsigned int remote_connect_serial_number; // 远程连接的序列号;
extern char ptpLoginName[30];	//远程连接的账号和密码;
extern char ptpLoginPassword[20];

extern refresh_net_device device_same_panel_1;
extern refresh_net_device device_same_panel_2;

extern refresh_net_device device_id_data_1;
extern refresh_net_device device_id_data_2;

extern refresh_net_device device_ip_conflict_1;
extern refresh_net_device device_ip_conflict_2;

extern bool edit_confilct_mode ;

extern bool scaning_mode ;

extern int isp_mode_error_code ;

extern		bool isp_mode_is_cancel ;
extern bool isp_mode_firmware_auto;
extern CString isp_mode_detect_firmware_path;

extern HANDLE hwait_scan_thread;

extern unsigned char nDefaultDisplayType;
extern unsigned char nDefaultTextPlace;
extern unsigned char nDefaultIconSize;
extern COLORREF	  nDefaultclrTxt;

extern int bacnet_view_number;
extern int input_item_select_for_range;

extern bitset<65536*3> read_analog_package;  //用于记录trendlog 已经记录了哪些模拟包
extern bitset<65536*3> read_dig_package;     //用于记录trendlog 已经记录了哪些数字包

extern int graphic_view_index ;
extern CString grapgic_view_name[3];
extern bool graphic_view_visible[14];
extern CString bacnet_message_input_title;
extern CString bacnet_message_return_string;  //得到的输入字符串
extern pidname_map product_map;
extern pid_reglist_map product_reglist_map;
extern bool offline_mode ; //全局离线模式判断;
extern CString offline_prg_path;   //离线模式得prg 保存路径;
extern bac_mstp_com g_mstp_com; // 全局mstp com 口 连接状态
extern bool custom_bacnet_register_listview;
extern bool initial_bip ;
extern Str_modbus_reg bacnet_to_modbus_struct; //用于bacnet 协议转换为modbus 协议的结构
extern panelname_map g_panelname_map;
extern CString HolLable[BAC_HOLIDAY_COUNT]; //用于动态加载List中的下拉框
