#pragma once

#include "Bacnet_Include.h"
#include "CM5\ud_str.h"



extern int g_invoke_id;
extern vector <int> Change_Color_ID;
extern HANDLE hThread;
extern DWORD nThreadID;

extern const bool WRITE_SUCCESS;
extern const bool WRITE_FAIL ;
extern	   bool g_HumChamberThread;
extern bool g_register_occuppied ; //Add by Alex
extern			  BOOL g_bChamber;
//Fance_4
extern unsigned short product_register_value[1024];
extern int product_type ;
extern int old_product_type;

extern unsigned short multi_register_value_tcp[10000];
extern	unsigned short multi_register_value[1024];
extern unsigned short cm5_register_value[512]; //CM5
extern unsigned short m_buffer[512];//CM5
extern unsigned short reg_tstat6[1024];//tstat6_new
extern unsigned short reg_tststold[1024];
extern char charr[600][2][600];
extern unsigned short newtstat6[1024];

extern int parameterSet;
extern BOOL Flexflash;
extern BOOL FlexSP;
extern int FlexSPN;
extern int  MDAY,MNIGHT;
extern int tstat6flex[12];
extern int m_slidertsta6[12];
extern int nCom;
extern	CString program_path;
extern	int g_tstat_id;
extern int g_serialNum;
extern	BOOL g_tstat_id_changed;
extern  BOOL g_bPauseMultiRead;     // for background read register
extern  int now_tstat_id;//for batch load/flash read/write
extern  CString g_strImagePathName;
extern	CString	g_strDatabasefilepath;
extern	CString g_strExePth;
extern  CString g_strImgeFolder;
extern  CString g_strOrigDatabaseFilePath;


extern	BOOL g_Scanfully;
extern	BOOL g_ScanSecurity;
extern	int g_nStartID;
extern	int g_nEndID;
extern BOOL g_bCancelScan;
extern int g_ScnnedNum;
extern CString g_strScanInfoPrompt;

extern int gCommunicationType;



extern CString g_strTstat5a;
extern CString g_strTstat5b;
extern CString g_strTstat5b2;
extern CString g_strTstat5c;
extern CString g_strTstat5d;
extern CString g_strnetWork;
extern CString g_strTstat5f;
extern CString g_strTstat5g;
extern CString g_strTstat5e;
extern CString g_strTstat5h;
extern CString g_strTstat6;
extern CString g_strTstat7;
extern CString g_strOR485;
extern CString g_strPressure;
extern CString g_strLightingCtrl;
 extern CString g_strHumChamber;

extern int g_CommunicationType;
extern int m_nbaudrat;
extern CString showing_text;

extern  CCriticalSection  critical_section;
extern  CCriticalSection  register_critical_section;
extern CEvent g_eventPauseMultiRead;


extern BOOL g_buser_log_in;
extern BOOL g_bPrivilegeMannage;
extern CString g_strLoginUserName;
extern int g_UserLevel;

extern CString g_strSensorName;
extern CString g_strInName1;
extern CString g_strInName2;
extern CString g_strInName3;
extern CString g_strInName4;
extern CString g_strInName5;
extern CString g_strInName6;
extern CString g_strInName7;
extern CString g_strInName8;

extern CString g_strInHumName;		// for tstat6 humidity input
extern CString			   g_strInCO2;

extern CString g_strOutName1;
extern CString g_strOutName2;
extern CString g_strOutName3;
extern CString g_strOutName4;
extern CString g_strOutName5;
extern CString g_strOutName6;
extern CString g_strOutName7;
extern CString g_strOutName8;
extern int g_ifanStatus;
extern CString g_strFan;

extern BOOL g_bEnableRefreshTreeView;
extern BOOL g_bScanStart;
extern int g_llTxCount;
extern int g_llRxCount;
extern BOOL g_unint;

int const PM_TSTAT5B = 1;
int const PM_TSTAT5A = 2;
int const PM_TSTAT5B2 = 3;
int const PM_TSTAT5C = 4;
int const PM_TSTAT6 = 6;
int const PM_TSTAT7 = 7;
int const PM_TSTAT5D = 12;
int const PM_AirQuality = 13;
const int PM_TSTAT5E = 16;
int const PM_TSTAT5F = 17;
int const PM_TSTAT5G = 18;
int const PM_TSTAT5H = 19;
int const PM_T38AIOD= 20;
int const PM_T3IOA = 21;
int const PM_T332AI = 22;
int const PM_T3AI16O = 23;

int const PM_ZIGBEE = 24;
int const PM_FLEXDRIVER = 25;
int const PM_T38I13O = 26;
int const PM_T3PERFORMANCE = 27;
int const PM_T34AO = 28;
int const PM_T36CT = 29;
int const PM_SOLAR = 30;
int const PM_FWMTRANSDUCER = 31;
int const PM_CO2_NET = 32;
int const PM_CO2_RS485 = 33;
int const PM_MINIPANEL = 35;
int const PM_PRESSURE = 40;
int const PM_CM5 = 50;
int const PM_TSTAT6_HUM_Chamber=64;
int const PM_NC = 100;
int const PM_LightingController = 103;



extern int MODBUS_SERIALNUMBER_LOWORD                          ;

extern int MODBUS_SERIALNUMBER_HIWORD                          ;

extern int MODBUS_VERSION_NUMBER_LO                            ;
extern int MODBUS_VERSION_NUMBER_HI                            ;
extern int MODBUS_ADDRESS                                      ;
extern int MODBUS_PRODUCT_MODEL                                ;
extern int MODBUS_HARDWARE_REV                                 ;
extern int MODBUS_PIC_VERSION                                  ;
extern int MODBUS_HUM_PIC_VERSION                              ;
extern int MODBUS_ADDRESS_PLUG_N_PLAY                          ;

extern int MODBUS_CUSTOM_ADDRESS                               ;
extern int MODBUS_BASE_ADDRESS                                 ;
extern int MODBUS_UPDATE_STATUS                                ;
extern int MODBUS_UPDATE_PTR_HI                                ;
extern int MODBUS_UPDATE_PTR_LO                                ;
extern int MODBUS_SCRATCHPAD_ADDRESS                           ;
extern int MODBUS_HARDWARE_INFORMATION                         ;

extern int MODBUS_COOL_HEAT_MODE                               ;
extern int MODBUS_MODE_OPERATION                               ;
extern int MODBUS_SEQUENCE                                     ;
extern int MODBUS_DEGC_OR_F                                    ;
extern int MODBUS_FAN_MODE                                     ;
extern int MODBUS_POWERUP_MODE                                 ;
extern int MODBUS_AUTO_ONLY                                    ;
extern int MODBUS_FACTORY_DEFAULTS                             ;
extern int MODBUS_INFO_BYTE                                    ;
extern int MODBUS_BAUDRATE                                     ;
extern int MODBUS_OVERRIDE_TIMER                               ;
extern int MODBUS_OVERRIDE_TIMER_LEFT                          ;
extern int MODBUS_HEAT_COOL_CONFIG                             ;
extern int MODBUS_TIMER_ON                                     ;
extern int MODBUS_TIMER_OFF                                    ;
extern int MODBUS_TIMER_UNITS                                  ;
extern int MODBUS_DEAD_MASTER                                  ;
extern int MODBUS_SYSTEM_TIME_FORMAT                           ;
extern int MODBUS_FREE_COOL_CONFIG                             ;
extern int MODBUS_RS485_MODE                                   ;
extern int MODBUS_TEMPRATURE_CHIP                              ;
extern int MODBUS_ANALOG1_RANGE                                ;
extern int MODBUS_ANALOG2_RANGE                                ;
extern int MODBUS_ANALOG3_RANGE                                ;
extern int MODBUS_ANALOG4_RANGE                                ;
extern int MODBUS_ANALOG5_RANGE                                ;
extern int MODBUS_ANALOG6_RANGE                                ;
extern int MODBUS_ANALOG7_RANGE                                ;
extern int MODBUS_ANALOG8_RANGE                                ;
extern int MODBUS_INTERNAL_THERMISTOR                          ;
extern int MODBUS_ANALOG_INPUT1                                ;
extern int MODBUS_ANALOG_INPUT2                                ;
extern int MODBUS_ANALOG_INPUT3                                ;
extern int MODBUS_ANALOG_INPUT4                                ;
extern int MODBUS_ANALOG_INPUT5                                ;
extern int MODBUS_ANALOG_INPUT6                                ;
extern int MODBUS_ANALOG_INPUT7                                ;
extern int MODBUS_ANALOG_INPUT8                                ;
extern int MODBUS_EXTERNAL_SENSOR1                             ;
extern int MODBUS_EXTERNAL_SENSOR2                             ;
extern int MODBUS_INPUT_MANU_ENABLE                            ;
extern int MODBUS_FILTER                                       ;
extern int MODBUS_INPUT1_FILTER                                ;
extern int MODBUS_INPUT2_FILTER                                ;
extern int MODBUS_INPUT3_FILTER                                ;
extern int MODBUS_INPUT4_FILTER                                ;
extern int MODBUS_INPUT5_FILTER                                ;
extern int MODBUS_INPUT6_FILTER                                ;
extern int MODBUS_INPUT7_FILTER                                ;
extern int MODBUS_INPUT8_FILTER                                ;
extern int MODBUS_EX_SENSOR1_FILTER                            ;
extern int MODBUS_EX_SENSOR2_FILTER                            ;
extern int MODBUS_CALIBRATION_TERM                             ;
extern int MODBUS_CALIBRATION_INTERNAL_THERMISTOR              ;
extern int MODBUS_CALIBRATION_ANALOG1                          ;
extern int MODBUS_CALIBRATION_ANALOG2                          ;
extern int MODBUS_CALIBRATION_ANALOG3                          ;
extern int MODBUS_CALIBRATION_ANALOG4                          ;
extern int MODBUS_CALIBRATION_ANALOG5                          ;
extern int MODBUS_CALIBRATION_ANALOG6                          ;
extern int MODBUS_CALIBRATION_ANALOG7                          ;
extern int MODBUS_CALIBRATION_ANALOG8                          ;
extern int MODBUS_HUMCOUNT1_H                                  ;
extern int MODBUS_HUMRH1_H                                     ;
extern int MODBUS_HUMCOUNT2_H                                  ;
extern int MODBUS_HUMRH2_H                                     ;
extern int MODBUS_ANALOG1_FUNCTION                             ;
extern int MODBUS_ANALOG2_FUNCTION                             ;
extern int MODBUS_ANALOG3_FUNCTION                             ;
extern int MODBUS_ANALOG4_FUNCTION                             ;
extern int MODBUS_ANALOG5_FUNCTION                             ;
extern int MODBUS_ANALOG6_FUNCTION                             ;
extern int MODBUS_ANALOG7_FUNCTION                             ;
extern int MODBUS_ANALOG8_FUNCTION                             ;
extern int MODBUS_TABLE1_ZERO                                  ;
extern int MODBUS_TABLE1_HALFONE                               ;
extern int MODBUS_TABLE1_ONE                                   ;
extern int MODBUS_TABLE1_HALFTWO                               ;
extern int MODBUS_TABLE1_TWO                                   ;
extern int MODBUS_TABLE1_HALFTHREE                             ;
extern int MODBUS_TABLE1_THREE                                 ;
extern int MODBUS_TABLE1_HALFFOUR                              ;
extern int MODBUS_TABLE1_FOUR                                  ;
extern int MODBUS_TABLE1_HALFFIVE                              ;
extern int MODBUS_TABLE1_FIVE                                  ;
extern int MODBUS_TABLE2_ZERO                                  ;
extern int MODBUS_TABLE2_HALFONE                               ;
extern int MODBUS_TABLE2_ONE                                   ;
extern int MODBUS_TABLE2_HALFTWO                               ;
extern int MODBUS_TABLE2_TWO                                   ;
extern int MODBUS_TABLE2_HALFTHREE                             ;
extern int MODBUS_TABLE2_THREE                                 ;
extern int MODBUS_TABLE2_HALFFOUR                              ;
extern int MODBUS_TABLE2_FOUR                                  ;
extern int MODBUS_TABLE2_HALFFIVE                              ;
extern int MODBUS_TABLE2_FIVE                                  ;
extern int MODUBS_HUMIDITY_RH                                  ;
extern int MODBUS_HUMIDITY_FREQUENCY                           ;
extern int MODBUS_HUM_PIC_UPDATE                               ;
extern int MODBUS_HUM_CAL_NUM                                  ;
extern int MODBUS_HUM_CURRENT_DEFAULT                          ;
extern int MODBUS_MODE_OUTPUT1                                 ;
extern int MODBUS_MODE_OUTPUT2                                 ;
extern int MODBUS_MODE_OUTPUT3                                 ;
extern int MODBUS_MODE_OUTPUT4                                 ;
extern int MODBUS_MODE_OUTPUT5                                 ;
extern int MODBUS_OUTPUT1_SCALE                                ;
extern int MODBUS_OUTPUT2_SCALE                                ;
extern int MODBUS_DIGITAL_OUTPUT_STATUS                        ;
extern int MODBUS_COOLING_VALVE                                ;
extern int MODBUS_HEATING_VALVE                                ;
extern int MODBUS_DAC_OFFSET                                   ;
extern int MODBUS_OUTPUT1_DELAY_OFF_TO_ON                      ;
extern int MODBUS_OUTPUT2_DELAY_OFF_TO_ON                      ;
extern int MODBUS_OUTPUT3_DELAY_OFF_TO_ON                      ;
extern int MODBUS_OUTPUT4_DELAY_OFF_TO_ON                      ;
extern int MODBUS_OUTPUT5_DELAY_OFF_TO_ON                      ;
extern int MODBUS_OUTPUT6_DELAY_OFF_TO_ON                      ;
extern int MODBUS_OUTPUT7_DELAY_OFF_TO_ON                      ;
extern int MODBUS_DELAY1_OFF_TO_ON_TIME_CURRENT                ;
extern int MODBUS_DELAY2_OFF_TO_ON_TIME_CURRENT                ;
extern int MODBUS_DELAY3_OFF_TO_ON_TIME_CURRENT                ;
extern int MODBUS_DELAY4_OFF_TO_ON_TIME_CURRENT                ;
extern int MODBUS_DELAY5_OFF_TO_ON_TIME_CURRENT                ;
extern int MODBUS_DELAY6_OFF_TO_ON_TIME_CURRENT                ;
extern int MODBUS_DELAY7_OFF_TO_ON_TIME_CURRENT                ;
extern int MODBUS_OUTPUT1_DELAY_ON_TO_OFF                      ;
extern int MODBUS_OUTPUT2_DELAY_ON_TO_OFF                      ;
extern int MODBUS_OUTPUT3_DELAY_ON_TO_OFF                      ;
extern int MODBUS_OUTPUT4_DELAY_ON_TO_OFF                      ;
extern int MODBUS_OUTPUT5_DELAY_ON_TO_OFF                      ;
extern int MODBUS_OUTPUT6_DELAY_ON_TO_OFF                      ;
extern int MODBUS_OUTPUT7_DELAY_ON_TO_OFF                      ;
extern int MODBUS_DELAY1_ON_TO_OFF_TIME_CURRENT                ;
extern int MODBUS_DELAY2_ON_TO_OFF_TIME_CURRENT                ;
extern int MODBUS_DELAY3_ON_TO_OFF_TIME_CURRENT                ;
extern int MODBUS_DELAY4_ON_TO_OFF_TIME_CURRENT                ;
extern int MODBUS_DELAY5_ON_TO_OFF_TIME_CURRENT                ;
extern int MODBUS_DELAY6_ON_TO_OFF_TIME_CURRENT                ;
extern int MODBUS_DELAY7_ON_TO_OFF_TIME_CURRENT                ;
extern int MODBUS_CYCLING_DELAY                                ;
extern int MODBUS_CHANGOVER_DELAY                              ;
extern int MODBUS_VALVE_TRAVEL_TIME                            ;
extern int MODBUS_VALVE_PERCENT                                ;
extern int MODBUS_INTERLOCK_OUTPUT1                            ;
extern int MODBUS_INTERLOCK_OUTPUT2                            ;
extern int MODBUS_INTERLOCK_OUTPUT3                            ;
extern int MODBUS_INTERLOCK_OUTPUT4                            ;
extern int MODBUS_INTERLOCK_OUTPUT5                            ;
extern int MODBUS_INTERLOCK_OUTPUT6                            ;
extern int MODBUS_INTERLOCK_OUTPUT7                            ;
extern int MODBUS_FREEZE_DELAY_ON                              ;
extern int MODBUS_FREEZE_DELAY_OFF                             ;
extern int MODBUS_OUTPUT_MANU_ENABLE                           ;
extern int MODBUS_MANU_RELAY1                                  ;
extern int MODBUS_MANU_RELAY2                                  ;
extern int MODBUS_MANU_RELAY3                                  ;
extern int MODBUS_MANU_RELAY4                                  ;
extern int MODBUS_MANU_RELAY5                                  ;
extern int MODBUS_MANUAL_AO1                                   ;
extern int MODBUS_MANUAL_AO2                                   ;
extern int MODBUS_DEADMASTER_AUTO_MANUAL                       ;
extern int MODBUS_DEADMASTER_OUTPUT_STATE                      ;
extern int MODBUS_DEADMASTER_COOL_OUTPUT                       ;
extern int MODBUS_DEADMASTER_HEAT_OUTPUT                       ;
extern int MODBUS_OUTPUT1_FUNCTION                             ;
extern int MODBUS_OUTPUT2_FUNCTION                             ;
extern int MODBUS_OUTPUT3_FUNCTION                             ;
extern int MODBUS_OUTPUT4_FUNCTION                             ;
extern int MODBUS_OUTPUT5_FUNCTION                             ;
extern int MODBUS_OUTPUT6_FUNCTION                             ;
extern int MODBUS_OUTPUT7_FUNCTION                             ;
extern int MODBUS_FAN_SPEED                                    ;
extern int MODBUS_PID_OUTPUT1                                  ;
extern int MODBUS_PID_OUTPUT2                                  ;
extern int MODBUS_PID_OUTPUT3                                  ;
extern int MODBUS_PID_OUTPUT4                                  ;
extern int MODBUS_PID_OUTPUT5                                  ;
extern int MODBUS_PID_OUTPUT6                                  ;
extern int MODBUS_PID_OUTPUT7                                  ;
extern int MODBUS_UNIVERSAL_OUTPUT_BEGIN                       ;
extern int MODBUS_UNIVERSAL_OUTPUT_COOL1                       ;
extern int MODBUS_UNIVERSAL_OUTPUT_COOL2                       ;
extern int MODBUS_UNIVERSAL_OUTPUT_COOL3                       ;
extern int MODBUS_UNIVERSAL_OUTPUT_HEAT1                       ;
extern int MODBUS_UNIVERSAL_OUTPUT_HEAT2                       ;
extern int MODBUS_UNIVERSAL_OUTPUT_HEAT3                       ;
extern int MODBUS_FAN0_OPER_TABLE_COAST                        ;
extern int MODBUS_FAN0_OPER_TABLE_COOL1                        ;
extern int MODBUS_FAN0_OPER_TABLE_COOL2                        ;
extern int MODBUS_FAN0_OPER_TABLE_COOL3                        ;
extern int MODBUS_FAN0_OPER_TABLE_HEAT1                        ;
extern int MODBUS_FAN0_OPER_TABLE_HEAT2                        ;
extern int MODBUS_FAN0_OPER_TABLE_HEAT3                        ;
extern int MODBUS_FAN1_OPER_TABLE_COAST                        ;
extern int MODBUS_FAN1_OPER_TABLE_COOL1                        ;
extern int MODBUS_FAN1_OPER_TABLE_COOL2                        ;
extern int MODBUS_FAN1_OPER_TABLE_COOL3                        ;
extern int MODBUS_FAN1_OPER_TABLE_HEAT1                        ;
extern int MODBUS_FAN1_OPER_TABLE_HEAT2                        ;
extern int MODBUS_FAN1_OPER_TABLE_HEAT3                        ;
extern int MODBUS_FAN2_OPER_TABLE_COAST                        ;
extern int MODBUS_FAN2_OPER_TABLE_COOL1                        ;
extern int MODBUS_FAN2_OPER_TABLE_COOL2                        ;
extern int MODBUS_FAN2_OPER_TABLE_COOL3                        ;
extern int MODBUS_FAN2_OPER_TABLE_HEAT1                        ;
extern int MODBUS_FAN2_OPER_TABLE_HEAT2                        ;
extern int MODBUS_FAN2_OPER_TABLE_HEAT3                        ;
extern int MODBUS_FAN3_OPER_TABLE_COAST                        ;
extern int MODBUS_FAN3_OPER_TABLE_COOL1                        ;
extern int MODBUS_FAN3_OPER_TABLE_COOL2                        ;
extern int MODBUS_FAN3_OPER_TABLE_COOL3                        ;
extern int MODBUS_FAN3_OPER_TABLE_HEAT1                        ;
extern int MODBUS_FAN3_OPER_TABLE_HEAT2                        ;
extern int MODBUS_FAN3_OPER_TABLE_HEAT3                        ;
extern int MODBUS_FANAUT_OPER_TABLE_COAST                      ;
extern int MODBUS_FANAUT_OPER_TABLE_COOL1                      ;
extern int MODBUS_FANAUT_OPER_TABLE_COOL2                      ;
extern int MODBUS_FANAUT_OPER_TABLE_COOL3                      ;
extern int MODBUS_FANAUT_OPER_TABLE_HEAT1                      ;
extern int MODBUS_FANAUT_OPER_TABLE_HEAT2                      ;
extern int MODBUS_FANAUT_OPER_TABLE_HEAT3                      ;
extern int MODBUS_VALVE_OPERATION_TABLE_BEGIN                  ;
extern int MODBUS_VALVE_OPER_TABLE_COOL1                       ;
extern int MODBUS_VALVE_OPER_TABLE_COOL2                       ;
extern int MODBUS_VALVE_OPER_TABLE_COOL3                       ;
extern int MODBUS_VALVE_OPER_TABLE_HEAT1                       ;
extern int MODBUS_VALVE_OPER_TABLE_HEAT2                       ;
extern int MODBUS_VALVE_OPER_TABLE_HEAT3                       ;
extern int MODBUS_HEAT_UNIVERSAL_TABLE                         ;
extern int MODBUS_COOL_UNIVERSAL_TABLE                         ;
extern int MODBUS_HEAT_ORIGINAL_TABLE                          ;
extern int MODBUS_COOL_ORIGINAL_TABLE                          ;
extern int MODBUS_VALVE_OFF_TABLE_COAST                        ;
extern int MODBUS_VALVE_OFF_TABLE_COOL1                        ;
extern int MODBUS_VALVE_OFF_TABLE_COOL2                        ;
extern int MODBUS_VALVE_OFF_TABLE_COOL3                        ;
extern int MODBUS_VALVE_OFF_TABLE_HEAT1                        ;
extern int MODBUS_VALVE_OFF_TABLE_HEAT2                        ;
extern int MODBUS_VALVE_OFF_TABLE_HEAT3                        ;
extern int MODBUS_DEFAULT_SETPOINT                             ;
extern int MODBUS_SETPOINT_CONTROL                             ;
extern int MODBUS_DAYSETPOINT_OPTION                           ;
extern int MODBUS_MIDDLE_SETPOINT                              ;
extern int MODBUS_DAY_SETPOINT                                 ;
extern int MODBUS_DAY_COOLING_DEADBAND                         ;
extern int MODBUS_DAY_HEATING_DEADBAND                         ;
extern int MODBUS_DAY_COOLING_SETPOINT                         ;
extern int MODBUS_DAY_HEATING_SETPOINT                         ;
extern int MODBUS_NIGHT_SETPOINT                               ;
extern int MODBUS_APPLICATION                                  ;
extern int MODBUS_NIGHT_HEATING_DEADBAND                       ;
extern int MODBUS_NIGHT_COOLING_DEADBAND                       ;
extern int MODBUS_NIGHT_HEATING_SETPOINT                       ;
extern int MODBUS_NIGHT_COOLING_SETPOINT                       ;
extern int MODBUS_WINDOW_INTERLOCK_COOLING_SETPOINT         	 ;
extern int MODBUS_WINDOW_INTERLOCK_HEATING_SETPOINT            ;
extern int MODBUS_UNIVERSAL_NIGHTSET                           ;
extern int MODBUS_UNIVERSAL_SET                                ;
extern int MODBUS_UNIVERSAL_DB_HI                              ;
extern int MODBUS_UNIVERSAL_DB_LO                              ;
extern int MODBUS_ECOMONY_COOLING_SETPOINT                     ;
extern int MODBUS_ECOMONY_HEATING_SETPOINT                     ;
extern int MODBUS_POWERUP_SETPOINT                             ;
extern int MODBUS_MAX_SETPOINT                                 ;
extern int MODBUS_MIN_SETPOINT                                 ;
extern int MODBUS_MAX_SETPOINT2                                ;
extern int MODBUS_MIN_SETPOINT2                                ;
extern int MODBUS_MAX_SETPOINT3                                ;
extern int MODBUS_MIN_SETPOINT3                                ;
extern int MODBUS_MAX_SETPOINT4                                ;
extern int MODBUS_MIN_SETPOINT4                                ;
extern int MODBUS_SETPOINT_INCREASE                            ;
extern int MODBUS_FREEZE_TEMP_SETPOINT                         ;
extern int MODBUS_WALL_SETPOINT                                ;
extern int MODBUS_CEILING_SETPOINT                             ;
extern int MODBUS_AVERAGE_SETPOINT                             ;
extern int MODBUS_UNOCCUPIED_HEATING                           ;
extern int MODBUS_UNOCCUPIED_COOLING                           ;
extern int MODBUS_RH_SETPOINT                                  ;
extern int MODBUS_CURRENT1_SETPOINT                            ;
extern int MODBUS_TEMP_SELECT                                  ;
extern int MODBUS_INPUT1_SELECT                                ;
extern int MODBUS_COOLING_PID                                  ;
extern int MODBUS_COOLING_PTERM                                ;
extern int MODBUS_COOLING_ITERM                                ;
extern int MODBUS_UNIVERSAL_PTERM                              ;
extern int MODBUS_UNIVERSAL_ITERM                              ;
extern int MODBUS_PID_UNIVERSAL                                ;
extern int MODBUS_UNITS1_HIGH                                  ;
extern int MODBUS_UNITS1_LOW                                   ;
extern int MODBUS_UNITS2_HIGH                                  ;
extern int MODBUS_UNITS2_LOW                                   ;
extern int MODBUS_PID2_MODE_OPERATION                          ;
extern int MODBUS_KEYPAD_SELECT                                ;
extern int MODBUS_SPECIAL_MENU_LOCK                            ;
extern int MODBUS_DISPLAY                                      ;
extern int MODBUS_ICON                                         ;
extern int MODBUS_LAST_KEY_TIMER                               ;
extern int MODBUS_KEYPAD_VALUE                                 ;
extern int MODBUS_DISPLAY_HUNDRED                              ;
extern int MODBUS_DISPLAY_TEN                                  ;
extern int MODBUS_DISPLAY_DIGITAL                              ;
extern int MODBUS_DISPLAY_STATUS                               ;
extern int MODBUS_ROUND_DISPLAY                                ;
extern int MODBUS_MIN_ADDRESS                                  ;
extern int MODBUS_MAX_ADDRESS                                  ;
extern int MODBUS_EEPROM_SIZE                                  ;
extern int MODBUS_TIMER_SELECT                                 ;
extern int MODBUS_YEAR                                         ;
extern int MODBUS_MONTH                                        ;
extern int MODBUS_WEEK                                         ;
extern int MODBUS_DAY                                          ;
extern int MODBUS_HOUR                                         ;
extern int MODBUS_MINUTE                                       ;
extern int MODBUS_SECOND                                       ;
extern int MODBUS_DIAGNOSTIC_ALARM                             ;
extern int MODBUS_DAY1_EVENT1_HI                               ;
extern int MODBUS_DAY1_EVENT1_LO                               ;
extern int MODBUS_DAY1_EVENT2_HI                               ;
extern int MODBUS_DAY1_EVENT2_LO                               ;
extern int MODBUS_DAY1_EVENT3_HI                               ;
extern int MODBUS_DAY1_EVENT3_LO                               ;
extern int MODBUS_DAY1_EVENT4_HI                               ;
extern int MODBUS_DAY1_EVENT4_LO                               ;
extern int MODBUS_DAY2_EVENT1_HI                               ;
extern int MODBUS_DAY2_EVENT1_LO                               ;
extern int MODBUS_DAY2_EVENT2_HI                               ;
extern int MODBUS_DAY2_EVENT2_LO                               ;
extern int MODBUS_DAY2_EVENT3_HI                               ;
extern int MODBUS_DAY2_EVENT3_LO                               ;
extern int MODBUS_DAY2_EVENT4_HI                               ;
extern int MODBUS_DAY2_EVENT4_LO                               ;
extern int MODBUS_LCD_TURN_OFF                                 ;
extern int MODBUS_LINE1_CHAR1                                  ;
extern int MODBUS_LINE1_CHAR2                                  ;
extern int MODBUS_LINE1_CHAR3                                  ;
extern int MODBUS_LINE1_CHAR4                                  ;
extern int MODBUS_LINE2_CHAR1                                  ;
extern int MODBUS_LINE2_CHAR2                                  ;
extern int MODBUS_LINE2_CHAR3                                  ;
extern int MODBUS_LINE2_CHAR4                                  ;
extern int MODBUS_INTERNAL_CHAR1                               ;
extern int MODBUS_INTERNAL_CHAR2                               ;
extern int MODBUS_INTERNAL_CHAR3                               ;
extern int MODBUS_INTERNAL_CHAR4                               ;
extern int MODBUS_AI1_CHAR1                                    ;
extern int MODBUS_AI1_CHAR2                                    ;
extern int MODBUS_AI1_CHAR3                                    ;
extern int MODBUS_AI1_CHAR4                                    ;
extern int MODBUS_AI2_CHAR1                                    ;
extern int MODBUS_AI2_CHAR2                                    ;
extern int MODBUS_AI2_CHAR3                                    ;
extern int MODBUS_AI2_CHAR4                                    ;
extern int MODBUS_AI3_CHAR1                                    ;
extern int MODBUS_AI3_CHAR2                                    ;
extern int MODBUS_AI3_CHAR3                                    ;
extern int MODBUS_AI3_CHAR4                                    ;
extern int MODBUS_AI4_CHAR1                                    ;
extern int MODBUS_AI4_CHAR2                                    ;
extern int MODBUS_AI4_CHAR3                                    ;
extern int MODBUS_AI4_CHAR4                                    ;
extern int MODBUS_AI5_CHAR1                                    ;
extern int MODBUS_AI5_CHAR2                                    ;
extern int MODBUS_AI5_CHAR3                                    ;
extern int MODBUS_AI5_CHAR4                                    ;
extern int MODBUS_AI6_CHAR1                                    ;
extern int MODBUS_AI6_CHAR2                                    ;
extern int MODBUS_AI6_CHAR3                                    ;
extern int MODBUS_AI6_CHAR4                                    ;
extern int MODBUS_AI7_CHAR1                                    ;
extern int MODBUS_AI7_CHAR2                                    ;
extern int MODBUS_AI7_CHAR3                                    ;
extern int MODBUS_AI7_CHAR4                                    ;
extern int MODBUS_AI8_CHAR1                                    ;
extern int MODBUS_AI8_CHAR2                                    ;
extern int MODBUS_AI8_CHAR3                                    ;
extern int MODBUS_AI8_CHAR4                                    ;
extern int MODBUS_OUTPUT1_CHAR1                                ;
extern int MODBUS_OUTPUT1_CHAR2                                ;
extern int MODBUS_OUTPUT1_CHAR3                                ;
extern int MODBUS_OUTPUT1_CHAR4                                ;
extern int MODBUS_OUTPUT2_CHAR1                                ;
extern int MODBUS_OUTPUT2_CHAR2                                ;
extern int MODBUS_OUTPUT2_CHAR3                                ;
extern int MODBUS_OUTPUT2_CHAR4                                ;
extern int MODBUS_OUTPUT3_CHAR1                                ;
extern int MODBUS_OUTPUT3_CHAR2                                ;
extern int MODBUS_OUTPUT3_CHAR3                                ;
extern int MODBUS_OUTPUT3_CHAR4                                ;
extern int MODBUS_OUTPUT4_CHAR1                                ;
extern int MODBUS_OUTPUT4_CHAR2                                ;
extern int MODBUS_OUTPUT4_CHAR3                                ;
extern int MODBUS_OUTPUT4_CHAR4                                ;
extern int MODBUS_OUTPUT5_CHAR1                                ;
extern int MODBUS_OUTPUT5_CHAR2                                ;
extern int MODBUS_OUTPUT5_CHAR3                                ;
extern int MODBUS_OUTPUT5_CHAR4                                ;
extern int MODBUS_OUTPUT6_CHAR1                                ;
extern int MODBUS_OUTPUT6_CHAR2                                ;
extern int MODBUS_OUTPUT6_CHAR3                                ;
extern int MODBUS_OUTPUT6_CHAR4                                ;
extern int MODBUS_OUTPUT7_CHAR1                                ;
extern int MODBUS_OUTPUT7_CHAR2                                ;
extern int MODBUS_OUTPUT7_CHAR3                                ;
extern int MODBUS_OUTPUT7_CHAR4                                ;
extern int MODBUS_SCHEDULEA_CHAR1                              ;
extern int MODBUS_SCHEDULEA_CHAR2                              ;
extern int MODBUS_SCHEDULEA_CHAR3                              ;
extern int MODBUS_SCHEDULEA_CHAR4                              ;
extern int MODBUS_SCHEDULEB_CHAR1                              ;
extern int MODBUS_SCHEDULEB_CHAR2                              ;
extern int MODBUS_SCHEDULEB_CHAR3                              ;
extern int MODBUS_SCHEDULEB_CHAR4                              ;
extern int MODBUS_SCHEDULEC_CHAR1                              ;
extern int MODBUS_SCHEDULEC_CHAR2                              ;
extern int MODBUS_SCHEDULEC_CHAR3                              ;
extern int MODBUS_SCHEDULEC_CHAR4                              ;
extern int MODBUS_SCHEDULED_CHAR1                              ;
extern int MODBUS_SCHEDULED_CHAR2                              ;
extern int MODBUS_SCHEDULED_CHAR3                              ;
extern int MODBUS_SCHEDULED_CHAR4                              ;
extern int MODBUS_WALL_CHAR1                                   ;
extern int MODBUS_WALL_CHAR2                                   ;
extern int MODBUS_WALL_CHAR3                                   ;
extern int MODBUS_WALL_CHAR4                                   ;
extern int MODBUS_CEILING_CHAR1                                ;
extern int MODBUS_CEILING_CHAR2                                ;
extern int MODBUS_CEILING_CHAR3                                ;
extern int MODBUS_CEILING_CHAR4                                ;
extern int MODBUS_OUTDOOR_CHAR1                                ;
extern int MODBUS_OUTDOOR_CHAR2                                ;
extern int MODBUS_OUTDOOR_CHAR3                                ;
extern int MODBUS_OUTDOOR_CHAR4                                ;
extern int MODBUS_AVERAGE_CHAR1                                ;
extern int MODBUS_AVERAGE_CHAR2                                ;
extern int MODBUS_AVERAGE_CHAR3                                ;
extern int MODBUS_AVERAGE_CHAR4                                ;
extern int MODBUS_LCD_SCREEN1                                  ;
extern int MODBUS_LCD_SCREEN2                                  ;
extern int MODBUS_DEMAND_RESPONSE                              ;
extern int MODBUS_LOCK_REGISTER                                ;
extern int MODBUS_PIR_STAGE                                    ;
extern int MODBUS_FIRST_CAL_FLAG                               ;
extern int MODBUS_HUM_CAL_EREASE                               ;
extern int MODBUS_HUMCOUNT3_H                                  ;
extern int MODBUS_HUMRH3_H                                     ;
extern int MODBUS_HUMCOUNT4_H                                  ;
extern int MODBUS_HUMRH4_H                                     ;
extern int MODBUS_HUMCOUNT5_H                                  ;
extern int MODBUS_HUMRH5_H                                     ;
extern int MODBUS_HUMCOUNT6_H                                  ;
extern int MODBUS_HUMRH6_H                                     ;
extern int MODBUS_HUMCOUNT7_H                                  ;
extern int MODBUS_HUMRH7_H                                     ;
extern int MODBUS_HUMCOUNT8_H                                  ;
extern int MODBUS_HUMRH8_H                                     ;
extern int MODBUS_HUMCOUNT9_H                                  ;
extern int MODBUS_HUMRH9_H                                     ;
extern int MODBUS_HUMCOUNT10_H                                 ;
extern int MODBUS_HUMRH10_H                                    ;
extern int MODBUS_HUM_LOCK_A                                   ;
extern int MODBUS_HUM_LOCK_B                                   ;
extern int MODBUS_LCD_ROTATE_ENABLE                            ;
extern int MODBUS_SCHEDULE_ON_OFF                              ;
extern int MODBUS_DISP_ITEM_TEMPERATURE                        ;
extern int MODBUS_DISP_ITEM_SETPOINT                           ;
extern int MODBUS_DISP_ITEM_AI1                                ;
extern int MODBUS_DISP_ITEM_AI2                                ;
extern int MODBUS_DISP_ITEM_AI3                                ;
extern int MODBUS_DISP_ITEM_AI4                                ;
extern int MODBUS_DISP_ITEM_AI5                                ;
extern int MODBUS_DISP_ITEM_AI6                                ;
extern int MODBUS_DISP_ITEM_AI7                                ;
extern int MODBUS_DISP_ITEM_AI8                                ;
extern int MODBUS_DISP_ITEM_MODE                               ;
extern int MODBUS_DISP_ITEM_USER_INFO                          ;
extern int MODBUS_DISP_ITEM_CLOCK_DATE                         ;
extern int MODBUS_DISP_ITEM_CLOCK_TIME                         ;
extern int MODBUS_DISP_ITEM_EXTENAL_SENSOR1                    ;
extern int MODBUS_DISP_ITEM_EXTENAL_SENSOR2                    ;
extern int MODBUS_DISP_ITEM_EXTENAL_SENSOR3                    ;
extern int MODBUS_DISP_ITEM_EXTENAL_SENSOR4                    ;
extern int MODBUS_DISP_ITEM_OUT1                               ;
extern int MODBUS_DISP_ITEM_OUT2                               ;
extern int MODBUS_DISP_ITEM_OUT3                               ;
extern int MODBUS_DISP_ITEM_OUT4                               ;
extern int MODBUS_DISP_ITEM_OUT5                               ;
extern int MODBUS_DISP_ITEM_OUT6                               ;
extern int MODBUS_DISP_ITEM_OUT7                               ;
extern int MODBUS_OUTPUT_PWM_AUTO_COAST                        ;
extern int MODBUS_OUTPUT_PWM_AUTO_COOL1                        ;
extern int MODBUS_OUTPUT_PWM_AUTO_COOL2                        ;
extern int MODBUS_OUTPUT_PWM_AUTO_COOL3                        ;
extern int MODBUS_OUTPUT_PWM_AUTO_HEAT1                        ;
extern int MODBUS_OUTPUT_PWM_AUTO_HEAT2                        ;
extern int MODBUS_OUTPUT_PWM_AUTO_HEAT3                        ;
extern int MODBUS_PWM_OUT4                                     ;
extern int MODBUS_PWM_OUT5                                     ;
extern int MODBUS_SUN_ICON_CONTROL                             ;
extern int MODBUS_MOON_ICON_CONTROL                            ;
extern int MODBUS_EXT_SENSOR_TEMP_CAL                          ;
extern int MODBUS_BUTTON_LEFT1                                 ;
extern int MODBUS_BUTTON_LEFT2                                 ;
extern int MODBUS_BUTTON_LEFT3                                 ;
extern int MODBUS_BUTTON_LEFT4                                 ;


extern int MODBUS_HUM_HEATER_CONTROL_ENABLE;
extern int MODBUS_HUM_INPUT_MANUAL_ENABLE;
extern int MODBUS_HUM_INPUT_MANUAL_VALUE;                             
extern int MODBUS_CO2_INPUT_MANUAL_ENABLE;                            
extern int MODBUS_CO2_INPUT_VALUE    ;                                
extern int MODBUS_CO2_CALIBRATION_DATA   ;                           
extern int MODBUS_UNIVERSAL_OFF_OUTPUT_BEGIN       ;                  
extern int MODBUS_UNIVERSAL_OFF_OUTPUT_COOL1   ;                      
extern int MODBUS_UNIVERSAL_OFF_OUTPUT_COOL2  ;                       
extern int MODBUS_UNIVERSAL_OFF_OUTPUT_COOL3   ;                      
extern int MODBUS_UNIVERSAL_OFF_OUTPUT_HEAT1  ;                       
extern int MODBUS_UNIVERSAL_OFF_OUTPUT_HEAT2  ;                       
extern int MODBUS_UNIVERSAL_OFF_OUTPUT_HEAT3 ;                       
extern int MODBUS_UNIVERSAL_OFF_VALVE_BEGIN ;                        
extern int MODBUS_UNIVERSAL_OFF_VALVE_COOL1;                          
extern int MODBUS_UNIVERSAL_OFF_VALVE_COOL2 ;                         
extern int MODBUS_UNIVERSAL_OFF_VALVE_COOL3   ;                       
extern int MODBUS_UNIVERSAL_OFF_VALVE_HEAT1   ;                       
extern int MODBUS_UNIVERSAL_OFF_VALVE_HEAT2   ;                       
extern int MODBUS_UNIVERSAL_OFF_VALVE_HEAT3   ;                      

extern int MODBUS_VALUE_SENSOR        ;                             
extern int MODBUS_PIR_SELECT_ENABLE      ;                           
extern int MODBUS_PIR_REAL_VALUE    ;                                 
extern int MODBUS_PIR_OCCUPIED      ;                                 
                            


extern int MODBUS_HEATING_PID                                  ;
extern int MODBUS_CALIBRATION                                  ;
extern int MODBUS_CALIBRATION_ANALOG_IN1                       ;
extern int MODBUS_DELAY                                        ;
extern int MODBUS_HEATING_PTERM                                ;
extern int MODBUS_HEATING_ITERM                                ;
extern int MODBUS_COOLING_DEADBAND                             ;
extern int MODBUS_HEATING_DEADBAND                             ;
extern int MODBUS_OUTPUT_SCALE                                 ;
extern int MODBUS_COOLING_SETPOINT                             ;
extern int MODBUS_HEATING_SETPOINT                             ;
extern int MODBUS_EXTERNAL_SENSOR_0                            ;
extern int MODBUS_EXTERNAL_SENSOR_1                            ;
extern int MODBUS_ANALOG_IN1                                   ;
extern int MODBUS_ANALOG_IN2                                   ;
extern int MODBUS_DIGITAL_IN1                                  ;
extern int MODBUS_LED1_CONTROL                                 ;
extern int MODBUS_LED2_CONTROL                                 ;
extern int MODBUS_LED3_CONTROL                                 ;
extern int MODBUS_LED4_CONTROL                                 ;
extern int MODBUS_LED5_CONTROL                                 ;
extern int MODBUS_LED6_CONTROL                                 ;
extern int MODBUS_LED7_CONTROL                                 ;
extern int MODBUS_INTERNAL_TEMP_IC                             ;
extern int MODBUS_CALIBRATION_ANALOG_IN2                       ;
extern int MODBUS_UNIVERSAL_VALVE_BEGIN                        ;
extern int MODBUS_UNIVERSAL_VALVE_COOL1                        ;
extern int MODBUS_UNIVERSAL_VALVE_COOL2                        ;
extern int MODBUS_UNIVERSAL_VALVE_COOL3                        ;
extern int MODBUS_UNIVERSAL_VALVE_HEAT1                        ;
extern int MODBUS_UNIVERSAL_VALVE_HEAT2                        ;
extern int MODBUS_UNIVERSAL_VALVE_HEAT3                        ;
extern int MODBUS_DIGITAL1_FUNCTION                            ;
extern int MODBUS_DIGITAL_INPUT                                ;
extern int MODBUS_DEBUGTIMER                                   ;
extern int MODBUS_FAN_GRIDPOINT                                ;
extern int MODBUS_MODE_GRIDPOINT                               ;
extern int MODBUS_HOLD_GRIDPOINT                               ;
extern int MODBUS_CONFIGURATION                                ;
extern int MODBUS_UTIL_MODE                                    ;
extern int MODBUS_ROTATION_OUT2                                ;
extern int MODBUS_ROTATION_OUT3                                ;
extern int MODBUS_ROTATION_OUT4                                ;
extern int MODBUS_ROTATION_OUT5                                ;
extern int MODBUS_ROTATION_TIME_LEFT                           ;
extern int MODBUS_FREE_COOL_OUT_TEMP                           ;
extern int MODBUS_NC_MASTER_TIME                               ;
extern int MODBUS_FREE_COOL_HYSTERISIS                         ;
extern int MODBUS_OUTPUT_FREE_COOL_COAST                       ;
extern int MODBUS_OUTPUT_FREE_COOL_COOL1                       ;
extern int MODBUS_OUTPUT_FREE_COOL_COOL2                       ;
extern int MODBUS_OUTPUT_FREE_COOL_COOL3                       ;
extern int MODBUS_OUTPUT_FREE_COOL_HEAT1                       ;
extern int MODBUS_OUTPUT_FREE_COOL_HEAT2                       ;
extern int MODBUS_OUTPUT_FREE_COOL_HEAT3                       ;
extern int MODBUS_MIN_AIR                                      ;
extern int MODBUS_OAT_HOTTEST                                  ;
extern int MODBUS_OAT_COLDEST                                  ;
extern int MODBUS_OFFSET_HOTTEST                               ;
extern int MODBUS_OFFSET_COLDEST                               ;
extern int MODBUS_TWO_BYTE_SETPOINT                            ;
extern int MODBUS_CURRENT_SETPOINT                             ;
extern int MODBUS_SETPOINT_OFFSET                              ;
extern int MODBUS_CHANGEOVER_SENSOR_MODE                       ;
extern int MODBUS_EXTERNAL_SENSOR_INUSE                        ;
extern int MODBUS_EXTERNAL_SENSOR_STATUS                       ;
extern int MODBUS_NEW_COOLING_SETPOINT                         ;
extern int MODBUS_LINE1_CHAR5                                  ;
extern int MODBUS_LINE1_CHAR6                                  ;
extern int MODBUS_LINE1_CHAR7                                  ;
extern int MODBUS_LINE1_CHAR8                                  ;
extern int MODBUS_WINDOW_INTERLOCK_DELAY                       ;
extern int MODBUS_LINE2_CHAR5                                  ;
extern int MODBUS_LINE2_CHAR6                                  ;
extern int MODBUS_LINE2_CHAR7                                  ;
extern int MODBUS_LINE2_CHAR8                                  ;
extern int MODBUS_DURA_WINTER_SUMMER                           ;
extern int MODBUS_FREE_COOL_SETPOINT                           ;
extern int MODBUS_FREE_COOL_MAX_SETPOINT                       ;
extern int MODBUS_FREE_COOL_MIN_SETPOINT                       ;
extern int MODBUS_FREE_COOL_MIN_DAMPER                         ;
extern int MODBUS_HEAT_COOL                                    ;
extern int MODBUS_TURN_OFF_FAN                                 ;
extern int MODBUS_UI_LINE1_CHAR1                               ;
extern int MODBUS_UI_LINE1_CHAR2                               ;
extern int MODBUS_UI_LINE1_CHAR3                               ;
extern int MODBUS_UI_LINE1_CHAR4                               ;
extern int MODBUS_UI_LINE2_CHAR1                               ;
extern int MODBUS_UI_LINE2_CHAR2                               ;
extern int MODBUS_UI_LINE2_CHAR3                               ;
extern int MODBUS_UI_LINE2_CHAR4                               ;
extern int MODBUS_UI_INTERNAL_CHAR1                            ;
extern int MODBUS_UI_INTERNAL_CHAR2                            ;
extern int MODBUS_UI_INTERNAL_CHAR3                            ;
extern int MODBUS_UI_INTERNAL_CHAR4                            ;
extern int MODBUS_UI_AI1_CHAR1                                 ;
extern int MODBUS_UI_AI1_CHAR2                                 ;
extern int MODBUS_UI_AI1_CHAR3                                 ;
extern int MODBUS_UI_AI1_CHAR4                                 ;
extern int MODBUS_UI_AI2_CHAR1                                 ;
extern int MODBUS_UI_AI2_CHAR2                                 ;
extern int MODBUS_UI_AI2_CHAR3                                 ;
extern int MODBUS_UI_AI2_CHAR4                                 ;
extern int MODBUS_UI_AI3_CHAR1                                 ;
extern int MODBUS_UI_AI3_CHAR2                                 ;
extern int MODBUS_UI_AI3_CHAR3                                 ;
extern int MODBUS_UI_AI3_CHAR4                                 ;
extern int MODBUS_UI_AI4_CHAR1                                 ;
extern int MODBUS_UI_AI4_CHAR2                                 ;
extern int MODBUS_UI_AI4_CHAR3                                 ;
extern int MODBUS_UI_AI4_CHAR4                                 ;
extern int MODBUS_UI_AI5_CHAR1                                 ;
extern int MODBUS_UI_AI5_CHAR2                                 ;
extern int MODBUS_UI_AI5_CHAR3                                 ;
extern int MODBUS_UI_AI5_CHAR4                                 ;
extern int MODBUS_UI_AI6_CHAR1                                 ;
extern int MODBUS_UI_AI6_CHAR2                                 ;
extern int MODBUS_UI_AI6_CHAR3                                 ;
extern int MODBUS_UI_AI6_CHAR4                                 ;
extern int MODBUS_UI_AI7_CHAR1                                 ;
extern int MODBUS_UI_AI7_CHAR2                                 ;
extern int MODBUS_UI_AI7_CHAR3                                 ;
extern int MODBUS_UI_AI7_CHAR4                                 ;
extern int MODBUS_UI_AI8_CHAR1                                 ;
extern int MODBUS_UI_AI8_CHAR2                                 ;
extern int MODBUS_UI_AI8_CHAR3                                 ;
extern int MODBUS_UI_AI8_CHAR4                                 ;
extern int MODBUS_WINDOW_HEATING_SETPOINT                      ;
extern int MODBUS_WINDOW_COOLING_SETPOINT                      ;
extern int MODBUS_RELAY_PWM_ENABLE                             ;
extern int MODBUS_RELAY_PWM_TOTAL_DUTY                         ;
extern int MODBUS_RELAY_PWM_HIGH_DUTY                          ;   

#pragma region For_bacnet
extern HWND      g_hwnd_now;
extern HWND      m_input_dlg_hwnd;
extern HWND      m_output_dlg_hwnd;
extern HWND      m_pragram_dlg_hwnd;
extern HWND      m_program_edit_hwnd;
extern HWND      m_variable_dlg_hwnd;
extern vector <Str_out_point> m_Output_data;
extern vector <Str_in_point>  m_Input_data;
extern vector <Str_program_point>  m_Program_data;
extern vector <Str_variable_point>  m_Variable_data;

#pragma endregion For_bacnet