// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "monthview1.h"

/////////////////////////////////////////////////////////////////////////////
// CMonthview1

IMPLEMENT_DYNCREATE(CMonthview1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CMonthview1 properties

/////////////////////////////////////////////////////////////////////////////
// CMonthview1 operations
