// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "mschart1.h"

/////////////////////////////////////////////////////////////////////////////
// CMschart1

IMPLEMENT_DYNCREATE(CMschart1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CMschart1 properties

/////////////////////////////////////////////////////////////////////////////
// CMschart1 operations
