#pragma once

#include "msflexgrid1.h"
 
#include "MainFrm.h"
#include "afxwin.h"
#include "global_struct.h"

// CNewHumChamberView form view
#define WM_FRESH_TESTO   WM_USER + 1011
#define WM_FRESH_HUM_CHAMBER   WM_USER + 1010
#define WM_FRESH_CO2   WM_USER+1009
class CNewHumChamberView : public CFormView
{
    DECLARE_DYNCREATE(CNewHumChamberView)

public:
    CNewHumChamberView();           // protected constructor used by dynamic creation
    virtual ~CNewHumChamberView();

public:
    enum { IDD = IDD_DIALOG_NEW_HUM_CHAMBER };
#ifdef _DEBUG
    virtual void AssertValid() const;
#ifndef _WIN32_WCE
    virtual void Dump(CDumpContext& dc) const;
#endif
#endif

protected:
    virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support

    DECLARE_MESSAGE_MAP()
public:
    void Fresh();
    void FreshUI();
    void Initial_RegisterList();
    vector<T3Register> m_vecT3Register;
    int  Get_RegID(CString Name);

public:
    void Main_infor();
    void Calibration_Points();
    void Fresh_CalibartionPoints();
    void Sensor_Reading_Table();
    void Sensor_Table();
    void start();
    void read_testo();
    unsigned short Get_Checks();
    unsigned long GetNewSerialNumber();
    void WriteSerialNumber(unsigned long SN);
    void Fresh_CO2();
public://涉及到的成员变量
    int m_nCurRow;
    int m_nCurCol;
    bool m_isstart;
    float m_value[4];
    CWinThread* m_pFreshMultiRegisters;
    double m_times;
    double m_Write_times;
    long  g_Time_Offset;
    BOOL is_Show_Write_singleDLG;
    int m_ID;
    int m_Value;
    int CurrentRow;
    int CurrentCol;
    BOOL m_Start;
    int m_test_status;
    CWinThread* hFirstThread;
    unsigned char m_tstatID;
    unsigned short m_SN[110];
	BOOL m_IsReadIniFile;
 /*   ULONG m_Time_Offset ; */
public:
#if 1
    int	MODBUS_SERIALNUMBER_LOWORD	;
    int	MODBUS_SERIALNUMBER_HIWORD	;
    int	MODBUS_VERSION_NUMBER_LO	;
    int	MODBUS_VERSION_NUMBER_HI	;
    int	MODBUS_ADDRESS	;
    int	MODBUS_PRODUCT_MODEL	;
    int	MODBUS_HARDWARE_REV	;
    int	MODBUS_PIC_VERSION	;
    int	MODBUS_ADDRESS_PLUG_N_PLAY	;
    int	MODBUS_BASE_ADDRESS	;
    int	MODBUS_UPDATE_STATUS	;
    int	MODBUS_SERINALNUMBER_WRITE_FLAG	;
    int	MODBUS_TESTO_CO2	;
    int	MODBUS_TESTO_HUM	;
    int	MODBUS_TESTO_T	;
    int	MODBUS_TESTO_P	;
    int	MODBUS_CO2_CAL_POINT	;
    int	MODBUS_CO2_SETTING0	;
    int	MODBUS_CO2_SETTING1	;
    int	MODBUS_CO2_SETTING2	;
    int	MODBUS_CO2_SETTING3	;
    int	MODBUS_CO2_SETTING4	;
    int	MODBUS_CO2_SETTING5	;
    int	MODBUS_CO2_SETTING6	;
    int	MODBUS_CO2_SETTING7	;
    int	MODBUS_CO2_SETTING8	;
    int	MODBUS_CO2_SETTING9	;
    int	MODBUS_CO2_RTD_SETTING0	;
    int	MODBUS_CO2_RTD_SETTING1	;
    int	MODBUS_CO2_SAMETIME_NUM	;
    int	MODBUS_SENSOR_TYPE	;
    int	MODBUS_HUM_CAL_POINT	;
    int	MODBUS_HUM_SETTING0	;
    int	MODBUS_HUM_SETTING1	;
    int	MODBUS_HUM_SETTING2	;
    int	MODBUS_HUM_SETTING3	;
    int	MODBUS_HUM_SETTING4	;
    int	MODBUS_HUM_SETTING5	;
    int	MODBUS_HUM_SETTING6	;
    int	MODBUS_HUM_SETTING7	;
    int	MODBUS_HUM_SETTING8	;
    int	MODBUS_HUM_SETTING9	;
    int	MODBUS_ALL_SENSOR_NUM 	;
    int	MODBUS_CAL_STEPS	;
    int	MODBUS_SENSOR_NUM_CALIBRATING	;
    int	MODBUS_SENSOR_POINT_CALIBRATING	;
    int	MODBUS_CO2_TSTAT_ADDR	;
    int	MODBUS_SET_CO2_ADDR	;
    int	MODBUS_CO2_ERROE	;
    int	MODBUS_CHARMBER_STABLE_TIME	;
    int	MODBUS_SENSOR_STABLE_TIME	;
    int	MODBUS_TIMER_SETTING0	;
    int	MODBUS_TIMER_SETTING1	;
    int	MODBUS_TIMER_SETTING2	;
    int	MODBUS_TIMER_SETTING3	;
    int	MODBUS_TIMER_SETTING4	;
    int	MODBUS_TIMER_SETTING5	;
    int	MODBUS_TIMER_SETTING6	;
    int	MODBUS_TIMER_SETTING7	;
    int	MODBUS_TIMER_SETTING8	;
    int	MODBUS_TIMER_SETTING9	;
    int	MODBUS_TEMP_SETTING0	;
    int	MODBUS_TEMP_SETTING1	;
    int	MODBUS_TEMP_SETTING2	;
    int	MODBUS_TEMP_SETTING3	;
    int	MODBUS_TEMP_SETTING4	;
    int	MODBUS_TEMP_SETTING5	;
    int	MODBUS_TEMP_SETTING6	;
    int	MODBUS_TEMP_SETTING7	;
    int	MODBUS_TEMP_SETTING8	;
    int	MODBUS_TEMP_SETTING9	;
    int	MODBUS_SENSOR_TEST_TIMER	;
    int	MODBUS_RAMPING_TIMER 	;
    int	MODBUS_RAMPING_TIMELEFT	;
    int	MODBUS_TIME_LEFT 	;
    int	MODBUS_POINT_TOTAL	;
    int	MODBUS_SENSOR_TOTAL	;
    int	MODBUS_POINT_NUM	;
    int	MODBUS_SENSOR_NUM	;
    int	MODBUS_SENSOR_HUM	;
    int	MODBUS_SENSOR_TEMP	;
    int	MODBUS_SENSOR_FRE	;
    int	MODBUS_SENSOR_POINTS	;
    int	MODBUS_SENSOR_HUMIDITY_ER	;
    int	MODBUS_SENSOR_FRE_ERROR	;
    int	MODBUS_ERROR_SENSOR_NUM	;
    int	MODBUS_CALIBRATE_STATE	;
    int	MODBUS_WORK_STEP	;
    int	MODBUS_POINTS_BITS_SET	;
    int	MODBUS_TSTAT_ADDRESS	;
    int	MODBUS_SET_TEMP_ADDR  	;
    int	MODBUS_SET_HUM_ADDR  	;
    int	MODBUS_CHAMBER_TEMP_ERROR	;
    int	MODBUS_CHAMBER_HUM_ERROR	;
    int	MODBUS_REFRESH_SENSOR	;
    int	MODBUS_HUMCOUNT1_H      	;
    int	MODBUS_HUMRH1_H	;
    int	MODBUS_HUMCOUNT2_H      	;
    int	MODBUS_HUMRH2_H	;
    int	MODBUS_HUMCOUNT3_H  	;
    int	MODBUS_HUMRH3_H	;
    int	MODBUS_HUMCOUNT4_H  	;
    int	MODBUS_HUMRH4_H	;
    int	MODBUS_HUMCOUNT5_H  	;
    int	MODBUS_HUMRH5_H	;
    int	MODBUS_HUMCOUNT6_H  	;
    int	MODBUS_HUMRH6_H	;
    int	MODBUS_HUMCOUNT7_H 	;
    int	MODBUS_HUMRH7_H	;
    int	MODBUS_HUMCOUNT8_H  	;
    int	MODBUS_HUMRH8_H	;
    int	MODBUS_HUMCOUNT9_H  	;
    int	MODBUS_HUMRH9_H	;
    int	MODBUS_HUMCOUNT10_H 	;
    int	MODBUS_HUMRH10_H        	;
    int	MODBUS_SENSOR1_STATE 	;
    int	MODBUS_SENSOR2_STATE	;
    int	MODBUS_SENSOR3_STATE	;
    int	MODBUS_SENSOR4_STATE	;
    int	MODBUS_SENSOR5_STATE	;
    int	MODBUS_SENSOR6_STATE	;
    int	MODBUS_SENSOR7_STATE	;
    int	MODBUS_SENSOR8_STATE	;
    int	MODBUS_SENSOR9_STATE	;
    int	MODBUS_SENSOR10_STATE	;
    int	MODBUS_SENSOR11_STATE	;
    int	MODBUS_SENSOR12_STATE	;
    int	MODBUS_SENSOR13_STATE	;
    int	MODBUS_SENSOR14_STATE	;
    int	MODBUS_SENSOR15_STATE	;
    int	MODBUS_SENSOR16_STATE	;
    int	MODBUS_SENSOR17_STATE	;
    int	MODBUS_SENSOR18_STATE	;
    int	MODBUS_SENSOR19_STATE	;
    int	MODBUS_SENSOR20_STATE	;
    int	MODBUS_SENSOR21_STATE	;
    int	MODBUS_SENSOR22_STATE	;
    int	MODBUS_SENSOR23_STATE	;
    int	MODBUS_SENSOR24_STATE	;
    int	MODBUS_SENSOR25_STATE	;
    int	MODBUS_SENSOR26_STATE	;
    int	MODBUS_SENSOR27_STATE	;
    int	MODBUS_SENSOR28_STATE	;
    int	MODBUS_SENSOR29_STATE	;
    int	MODBUS_SENSOR30_STATE	;
    int	MODBUS_SENSOR31_STATE	;
    int	MODBUS_SENSOR32_STATE	;
    int	MODBUS_SENSOR33_STATE	;
    int	MODBUS_SENSOR34_STATE	;
    int	MODBUS_SENSOR35_STATE	;
    int	MODBUS_SENSOR36_STATE	;
    int	MODBUS_SENSOR37_STATE	;
    int	MODBUS_SENSOR38_STATE	;
    int	MODBUS_SENSOR39_STATE	;
    int	MODBUS_SENSOR40_STATE	;
    int	MODBUS_SENSOR41_STATE	;
    int	MODBUS_SENSOR42_STATE	;
    int	MODBUS_SENSOR43_STATE	;
    int	MODBUS_SENSOR44_STATE	;
    int	MODBUS_SENSOR45_STATE	;
    int	MODBUS_SENSOR46_STATE	;
    int	MODBUS_SENSOR47_STATE	;
    int	MODBUS_SENSOR48_STATE	;
    int	MODBUS_SENSOR49_STATE	;
    int	MODBUS_SENSOR50_STATE	;
    int	MODBUS_SENSOR51_STATE	;
    int	MODBUS_SENSOR52_STATE	;
    int	MODBUS_SENSOR53_STATE	;
    int	MODBUS_SENSOR54_STATE	;
    int	MODBUS_SENSOR55_STATE	;
    int	MODBUS_SENSOR56_STATE	;
    int	MODBUS_SENSOR57_STATE	;
    int	MODBUS_SENSOR58_STATE	;
    int	MODBUS_SENSOR59_STATE	;
    int	MODBUS_SENSOR60_STATE	;
    int	MODBUS_SENSOR61_STATE	;
    int	MODBUS_SENSOR62_STATE	;
    int	MODBUS_SENSOR63_STATE	;
    int	MODBUS_SENSOR64_STATE	;
    int	MODBUS_SENSOR65_STATE	;
    int	MODBUS_SENSOR66_STATE	;
    int	MODBUS_SENSOR67_STATE	;
    int	MODBUS_SENSOR68_STATE	;
    int	MODBUS_SENSOR69_STATE	;
    int	MODBUS_SENSOR70_STATE	;
    int	MODBUS_SENSOR71_STATE	;
    int	MODBUS_SENSOR72_STATE	;
    int	MODBUS_SENSOR73_STATE	;
    int	MODBUS_SENSOR74_STATE	;
    int	MODBUS_SENSOR75_STATE	;
    int	MODBUS_SENSOR76_STATE	;
    int	MODBUS_SENSOR77_STATE	;
    int	MODBUS_SENSOR78_STATE	;
    int	MODBUS_SENSOR79_STATE	;
    int	MODBUS_SENSOR80_STATE	;
    int	MODBUS_SENSOR81_STATE	;
    int	MODBUS_SENSOR82_STATE	;
    int	MODBUS_SENSOR83_STATE	;
    int	MODBUS_SENSOR84_STATE	;
    int	MODBUS_SENSOR85_STATE	;
    int	MODBUS_SENSOR86_STATE	;
    int	MODBUS_SENSOR87_STATE	;
    int	MODBUS_SENSOR88_STATE	;
    int	MODBUS_SENSOR89_STATE	;
    int	MODBUS_SENSOR90_STATE	;
    int	MODBUS_SENSOR91_STATE	;
    int	MODBUS_SENSOR92_STATE	;
    int	MODBUS_SENSOR93_STATE	;
    int	MODBUS_SENSOR94_STATE	;
    int	MODBUS_SENSOR95_STATE	;
    int	MODBUS_SENSOR96_STATE	;
    int	MODBUS_SENSOR97_STATE	;
    int	MODBUS_SENSOR98_STATE	;
    int	MODBUS_SENSOR99_STATE	;
    int	MODBUS_SENSOR100_STATE	;
    int	MODBUS_SENSOR101_STATE	;
    int	MODBUS_SENSOR102_STATE	;
    int	MODBUS_SENSOR103_STATE	;
    int	MODBUS_SENSOR104_STATE 	;
    int	MODBUS_SENSOR1_TEMP     	;
    int	MODBUS_SENSOR1_HUM	;
    int	MODBUS_SENSOR2_TEMP    	;
    int	MODBUS_SENSOR2_HUM	;
    int	MODBUS_SENSOR3_TEMP    	;
    int	MODBUS_SENSOR3_HUM	;
    int	MODBUS_SENSOR4_TEMP    	;
    int	MODBUS_SENSOR4_HUM	;
    int	MODBUS_SENSOR5_TEMP    	;
    int	MODBUS_SENSOR5_HUM	;
    int	MODBUS_SENSOR6_TEMP    	;
    int	MODBUS_SENSOR6_HUM	;
    int	MODBUS_SENSOR7_TEMP    	;
    int	MODBUS_SENSOR7_HUM	;
    int	MODBUS_SENSOR8_TEMP    	;
    int	MODBUS_SENSOR8_HUM	;
    int	MODBUS_SENSOR9_TEMP    	;
    int	MODBUS_SENSOR9_HUM	;
    int	MODBUS_SENSOR10_TEMP    	;
    int	MODBUS_SENSOR10_HUM	;
    int	MODBUS_SENSOR11_TEMP    	;
    int	MODBUS_SENSOR11_HUM	;
    int	MODBUS_SENSOR12_TEMP    	;
    int	MODBUS_SENSOR12_HUM	;
    int	MODBUS_SENSOR13_TEMP    	;
    int	MODBUS_SENSOR13_HUM	;
    int	MODBUS_SENSOR14_TEMP    	;
    int	MODBUS_SENSOR14_HUM	;
    int	MODBUS_SENSOR15_TEMP    	;
    int	MODBUS_SENSOR15_HUM	;
    int	MODBUS_SENSOR16_TEMP    	;
    int	MODBUS_SENSOR16_HUM	;
    int	MODBUS_SENSOR17_TEMP    	;
    int	MODBUS_SENSOR17_HUM	;
    int	MODBUS_SENSOR18_TEMP    	;
    int	MODBUS_SENSOR18_HUM	;
    int	MODBUS_SENSOR19_TEMP    	;
    int	MODBUS_SENSOR19_HUM	;
    int	MODBUS_SENSOR20_TEMP    	;
    int	MODBUS_SENSOR20_HUM	;
    int	MODBUS_SENSOR21_TEMP    	;
    int	MODBUS_SENSOR21_HUM	;
    int	MODBUS_SENSOR22_TEMP    	;
    int	MODBUS_SENSOR22_HUM	;
    int	MODBUS_SENSOR23_TEMP    	;
    int	MODBUS_SENSOR23_HUM	;
    int	MODBUS_SENSOR24_TEMP    	;
    int	MODBUS_SENSOR24_HUM	;
    int	MODBUS_SENSOR25_TEMP    	;
    int	MODBUS_SENSOR25_HUM	;
    int	MODBUS_SENSOR26_TEMP    	;
    int	MODBUS_SENSOR26_HUM	;
    int	MODBUS_SENSOR27_TEMP    	;
    int	MODBUS_SENSOR27_HUM	;
    int	MODBUS_SENSOR28_TEMP    	;
    int	MODBUS_SENSOR28_HUM	;
    int	MODBUS_SENSOR29_TEMP    	;
    int	MODBUS_SENSOR29_HUM	;
    int	MODBUS_SENSOR30_TEMP    	;
    int	MODBUS_SENSOR30_HUM	;
    int	MODBUS_SENSOR31_TEMP    	;
    int	MODBUS_SENSOR31_HUM	;
    int	MODBUS_SENSOR32_TEMP    	;
    int	MODBUS_SENSOR32_HUM	;
    int	MODBUS_SENSOR33_TEMP    	;
    int	MODBUS_SENSOR33_HUM	;
    int	MODBUS_SENSOR34_TEMP    	;
    int	MODBUS_SENSOR34_HUM	;
    int	MODBUS_SENSOR35_TEMP    	;
    int	MODBUS_SENSOR35_HUM	;
    int	MODBUS_SENSOR36_TEMP    	;
    int	MODBUS_SENSOR36_HUM	;
    int	MODBUS_SENSOR37_TEMP    	;
    int	MODBUS_SENSOR37_HUM	;
    int	MODBUS_SENSOR38_TEMP    	;
    int	MODBUS_SENSOR38_HUM	;
    int	MODBUS_SENSOR39_TEMP    	;
    int	MODBUS_SENSOR39_HUM	;
    int	MODBUS_SENSOR40_TEMP    	;
    int	MODBUS_SENSOR40_HUM	;
    int	MODBUS_SENSOR41_TEMP    	;
    int	MODBUS_SENSOR41_HUM	;
    int	MODBUS_SENSOR42_TEMP    	;
    int	MODBUS_SENSOR42_HUM	;
    int	MODBUS_SENSOR43_TEMP    	;
    int	MODBUS_SENSOR43_HUM	;
    int	MODBUS_SENSOR44_TEMP    	;
    int	MODBUS_SENSOR44_HUM	;
    int	MODBUS_SENSOR45_TEMP    	;
    int	MODBUS_SENSOR45_HUM	;
    int	MODBUS_SENSOR46_TEMP    	;
    int	MODBUS_SENSOR46_HUM	;
    int	MODBUS_SENSOR47_TEMP    	;
    int	MODBUS_SENSOR47_HUM	;
    int	MODBUS_SENSOR48_TEMP    	;
    int	MODBUS_SENSOR48_HUM	;
    int	MODBUS_SENSOR49_TEMP    	;
    int	MODBUS_SENSOR49_HUM	;
    int	MODBUS_SENSOR50_TEMP    	;
    int	MODBUS_SENSOR50_HUM	;
    int	MODBUS_SENSOR51_TEMP    	;
    int	MODBUS_SENSOR51_HUM	;
    int	MODBUS_SENSOR52_TEMP    	;
    int	MODBUS_SENSOR52_HUM	;
    int	MODBUS_SENSOR53_TEMP    	;
    int	MODBUS_SENSOR53_HUM	;
    int	MODBUS_SENSOR54_TEMP    	;
    int	MODBUS_SENSOR54_HUM	;
    int	MODBUS_SENSOR55_TEMP    	;
    int	MODBUS_SENSOR55_HUM	;
    int	MODBUS_SENSOR56_TEMP    	;
    int	MODBUS_SENSOR56_HUM	;
    int	MODBUS_SENSOR57_TEMP    	;
    int	MODBUS_SENSOR57_HUM	;
    int	MODBUS_SENSOR58_TEMP    	;
    int	MODBUS_SENSOR58_HUM	;
    int	MODBUS_SENSOR59_TEMP	;
    int	MODBUS_SENSOR59_HUM	;
    int	MODBUS_SENSOR60_TEMP    	;
    int	MODBUS_SENSOR60_HUM	;
    int	MODBUS_SENSOR61_TEMP    	;
    int	MODBUS_SENSOR61_HUM	;
    int	MODBUS_SENSOR62_TEMP    	;
    int	MODBUS_SENSOR62_HUM	;
    int	MODBUS_SENSOR63_TEMP    	;
    int	MODBUS_SENSOR63_HUM	;
    int	MODBUS_SENSOR64_TEMP    	;
    int	MODBUS_SENSOR64_HUM	;
    int	MODBUS_SENSOR65_TEMP    	;
    int	MODBUS_SENSOR65_HUM	;
    int	MODBUS_SENSOR66_TEMP    	;
    int	MODBUS_SENSOR66_HUM	;
    int	MODBUS_SENSOR67_TEMP    	;
    int	MODBUS_SENSOR67_HUM	;
    int	MODBUS_SENSOR68_TEMP    	;
    int	MODBUS_SENSOR68_HUM	;
    int	MODBUS_SENSOR69_TEMP    	;
    int	MODBUS_SENSOR69_HUM	;
    int	MODBUS_SENSOR70_TEMP    	;
    int	MODBUS_SENSOR70_HUM	;
    int	MODBUS_SENSOR71_TEMP    	;
    int	MODBUS_SENSOR71_HUM	;
    int	MODBUS_SENSOR72_TEMP    	;
    int	MODBUS_SENSOR72_HUM	;
    int	MODBUS_SENSOR73_TEMP    	;
    int	MODBUS_SENSOR73_HUM	;
    int	MODBUS_SENSOR74_TEMP    	;
    int	MODBUS_SENSOR74_HUM	;
    int	MODBUS_SENSOR75_TEMP    	;
    int	MODBUS_SENSOR75_HUM	;
    int	MODBUS_SENSOR76_TEMP    	;
    int	MODBUS_SENSOR76_HUM	;
    int	MODBUS_SENSOR77_TEMP    	;
    int	MODBUS_SENSOR77_HUM	;
    int	MODBUS_SENSOR78_TEMP    	;
    int	MODBUS_SENSOR78_HUM	;
    int	MODBUS_SENSOR79_TEMP    	;
    int	MODBUS_SENSOR79_HUM	;
    int	MODBUS_SENSOR80_TEMP    	;
    int	MODBUS_SENSOR80_HUM	;
    int	MODBUS_SENSOR81_TEMP    	;
    int	MODBUS_SENSOR81_HUM	;
    int	MODBUS_SENSOR82_TEMP    	;
    int	MODBUS_SENSOR82_HUM	;
    int	MODBUS_SENSOR83_TEMP    	;
    int	MODBUS_SENSOR83_HUM	;
    int	MODBUS_SENSOR84_TEMP    	;
    int	MODBUS_SENSOR84_HUM	;
    int	MODBUS_SENSOR85_TEMP    	;
    int	MODBUS_SENSOR85_HUM	;
    int	MODBUS_SENSOR86_TEMP    	;
    int	MODBUS_SENSOR86_HUM	;
    int	MODBUS_SENSOR87_TEMP    	;
    int	MODBUS_SENSOR87_HUM	;
    int	MODBUS_SENSOR88_TEMP    	;
    int	MODBUS_SENSOR88_HUM	;
    int	MODBUS_SENSOR89_TEMP    	;
    int	MODBUS_SENSOR89_HUM	;
    int	MODBUS_SENSOR90_TEMP    	;
    int	MODBUS_SENSOR90_HUM	;
    int	MODBUS_SENSOR91_TEMP    	;
    int	MODBUS_SENSOR91_HUM	;
    int	MODBUS_SENSOR92_TEMP    	;
    int	MODBUS_SENSOR92_HUM	;
    int	MODBUS_SENSOR93_TEMP    	;
    int	MODBUS_SENSOR93_HUM	;
    int	MODBUS_SENSOR94_TEMP    	;
    int	MODBUS_SENSOR94_HUM	;
    int	MODBUS_SENSOR95_TEMP    	;
    int	MODBUS_SENSOR95_HUM	;
    int	MODBUS_SENSOR96_TEMP    	;
    int	MODBUS_SENSOR96_HUM	;
    int	MODBUS_SENSOR97_TEMP    	;
    int	MODBUS_SENSOR97_HUM	;
    int	MODBUS_SENSOR98_TEMP    	;
    int	MODBUS_SENSOR98_HUM	;
    int	MODBUS_SENSOR99_TEMP    	;
    int	MODBUS_SENSOR99_HUM	;
    int	MODBUS_SENSOR100_TEMP   	;
    int	MODBUS_SENSOR100_HUM	;
    int	MODBUS_SENSOR101_TEMP   	;
    int	MODBUS_SENSOR101_HUM	;
    int	MODBUS_SENSOR102_TEMP   	;
    int	MODBUS_SENSOR102_HUM	;
    int	MODBUS_SENSOR103_TEMP   	;
    int	MODBUS_SENSOR103_HUM	;
    int	MODBUS_SENSOR104_TEMP   	;
    int	MODBUS_SENSOR104_HUM   	;
    int	MODBUS_SENSOR1_SN	;
    int	MODBUS_SENSOR2_SN	;
    int	MODBUS_SENSOR3_SN	;
    int	MODBUS_SENSOR4_SN	;
    int	MODBUS_SENSOR5_SN	;
    int	MODBUS_SENSOR6_SN	;
    int	MODBUS_SENSOR7_SN	;
    int	MODBUS_SENSOR8_SN	;
    int	MODBUS_SENSOR9_SN	;
    int	MODBUS_SENSOR10_SN	;
    int	MODBUS_SENSOR11_SN	;
    int	MODBUS_SENSOR12_SN	;
    int	MODBUS_SENSOR13_SN	;
    int	MODBUS_SENSOR14_SN	;
    int	MODBUS_SENSOR15_SN	;
    int	MODBUS_SENSOR16_SN	;
    int	MODBUS_SENSOR17_SN	;
    int	MODBUS_SENSOR18_SN	;
    int	MODBUS_SENSOR19_SN	;
    int	MODBUS_SENSOR20_SN	;
    int	MODBUS_SENSOR21_SN	;
    int	MODBUS_SENSOR22_SN	;
    int	MODBUS_SENSOR23_SN	;
    int	MODBUS_SENSOR24_SN	;
    int	MODBUS_SENSOR25_SN	;
    int	MODBUS_SENSOR26_SN	;
    int	MODBUS_SENSOR27_SN	;
    int	MODBUS_SENSOR28_SN	;
    int	MODBUS_SENSOR29_SN	;
    int	MODBUS_SENSOR30_SN	;
    int	MODBUS_SENSOR31_SN	;
    int	MODBUS_SENSOR32_SN	;
    int	MODBUS_SENSOR33_SN	;
    int	MODBUS_SENSOR34_SN	;
    int	MODBUS_SENSOR35_SN	;
    int	MODBUS_SENSOR36_SN	;
    int	MODBUS_SENSOR37_SN	;
    int	MODBUS_SENSOR38_SN	;
    int	MODBUS_SENSOR39_SN	;
    int	MODBUS_SENSOR40_SN	;
    int	MODBUS_SENSOR41_SN	;
    int	MODBUS_SENSOR42_SN	;
    int	MODBUS_SENSOR43_SN	;
    int	MODBUS_SENSOR44_SN	;
    int	MODBUS_SENSOR45_SN	;
    int	MODBUS_SENSOR46_SN	;
    int	MODBUS_SENSOR47_SN	;
    int	MODBUS_SENSOR48_SN	;
    int	MODBUS_SENSOR49_SN	;
    int	MODBUS_SENSOR50_SN	;
    int	MODBUS_SENSOR51_SN	;
    int	MODBUS_SENSOR52_SN	;
    int	MODBUS_SENSOR53_SN	;
    int	MODBUS_SENSOR54_SN	;
    int	MODBUS_SENSOR55_SN	;
    int	MODBUS_SENSOR56_SN	;
    int	MODBUS_SENSOR57_SN	;
    int	MODBUS_SENSOR58_SN	;
    int	MODBUS_SENSOR59_SN	;
    int	MODBUS_SENSOR60_SN	;
    int	MODBUS_SENSOR61_SN	;
    int	MODBUS_SENSOR62_SN	;
    int	MODBUS_SENSOR63_SN	;
    int	MODBUS_SENSOR64_SN	;
    int	MODBUS_SENSOR65_SN	;
    int	MODBUS_SENSOR66_SN	;
    int	MODBUS_SENSOR67_SN	;
    int	MODBUS_SENSOR68_SN	;
    int	MODBUS_SENSOR69_SN	;
    int	MODBUS_SENSOR70_SN 	;
    int	MODBUS_SENSOR71_SN	;
    int	MODBUS_SENSOR72_SN	;
    int	MODBUS_SENSOR73_SN	;
    int	MODBUS_SENSOR74_SN	;
    int	MODBUS_SENSOR75_SN	;
    int	MODBUS_SENSOR76_SN	;
    int	MODBUS_SENSOR77_SN	;
    int	MODBUS_SENSOR78_SN	;
    int	MODBUS_SENSOR79_SN	;
    int	MODBUS_SENSOR80_SN	;
    int	MODBUS_SENSOR81_SN	;
    int	MODBUS_SENSOR82_SN	;
    int	MODBUS_SENSOR83_SN	;
    int	MODBUS_SENSOR84_SN	;
    int	MODBUS_SENSOR85_SN	;
    int	MODBUS_SENSOR86_SN	;
    int	MODBUS_SENSOR87_SN	;
    int	MODBUS_SENSOR88_SN	;
    int	MODBUS_SENSOR89_SN	;
    int	MODBUS_SENSOR90_SN	;
    int	MODBUS_SENSOR91_SN	;
    int	MODBUS_SENSOR92_SN	;
    int	MODBUS_SENSOR93_SN	;
    int	MODBUS_SENSOR94_SN	;
    int	MODBUS_SENSOR95_SN	;
    int	MODBUS_SENSOR96_SN	;
    int	MODBUS_SENSOR97_SN	;
    int	MODBUS_SENSOR98_SN	;
    int	MODBUS_SENSOR99_SN	;
    int	MODBUS_SENSOR100_SN	;
    int	MODBUS_SENSOR101_SN	;
    int	MODBUS_SENSOR102_SN	;
    int	MODBUS_SENSOR103_SN	;
    int	MODBUS_SENSOR104_SN	;
    int	MODBUS_CLEAR_TABLE_MANUAL	;
    int	MODBUS_CALIBRATE_MANUAL	;
    int	MODBUS_FRE_MANUAL	;
    int	MODBUS_HUM_MANUAL 	;
    int	MODBUS_RESULT2  	;
    int	MODBUS_TEST0	;
    int	MODBUS_TEST1	;
    int	MODBUS_TEST2	;
    int	MODBUS_TEST3	;
    int	MODBUS_TEST4	;
    int	MODBUS_TEST5	;
    int	MODBUS_TEST6	;
    int	MODBUS_FRE_TEMP0	;
    int	MODBUS_FRE_TEMP1	;
    int	MODBUS_FRE_TEMP2	;
    int	MODBUS_FRE_TEMP3	;
    int	MODBUS_FRE_TEMP4	;
    int	MODBUS_FRE_TEMP5	;
    int	MODBUS_FRE_TEMP6	;
    int	MODBUS_FRE_TEMP7	;
    int	MODBUS_FRE_TEMP8	;
    int	MODBUS_FRE_TEMP9	;
    int	MODBUS_HUM_TEMP0	;
    int	MODBUS_HUM_TEMP1	;
    int	MODBUS_HUM_TEMP2	;
    int	MODBUS_HUM_TEMP3	;
    int	MODBUS_HUM_TEMP4	;
    int	MODBUS_HUM_TEMP5	;
    int	MODBUS_HUM_TEMP6	;
    int	MODBUS_HUM_TEMP7	;
    int	MODBUS_HUM_TEMP8	;
    int	MODBUS_HUM_TEMP9	;
    int	MODBUS_REGISTER_END	;
#endif


    virtual void OnInitialUpdate();
    CButton m_check1;
    CButton m_check10;
    CButton m_check2;
    CButton m_check3;
    CButton m_check4;
    CButton m_check5;
    CButton m_check6;
    CButton m_check7;
    CButton m_check8;
    CButton m_check9;

    CEdit m_edit_co21;
    CEdit m_edit_co22;
    CEdit m_edit_co23;
    CEdit m_edit_co24;
    CEdit m_edit_co25;
    CEdit m_edit_co26;
    CEdit m_edit_co27;
    CEdit m_edit_co28;
    CEdit m_edit_co29;
    CEdit m_edit_co210;

    CComboBox m_combox_type;
    CComboBox m_combox_testo;
    CEdit m_edit_co2;
    CEdit m_edit_presure;
    CEdit m_edit_temp;
    CEdit m_edit_hum;
    CEdit m_edit_freq1;
    CEdit m_edit_freq10;
    CEdit m_edit_freq2;
    CEdit m_edit_freq3;
    CEdit m_edit_freq4;
    CEdit m_edit_freq5;
    CEdit m_edit_freq6;
    CEdit m_edit_freq7;
    CEdit m_edit_freq8;
    CEdit m_edit_freq9;
    CEdit m_edit_hum1;
    CEdit m_edit_hum10;
    CEdit m_edit_hum2;
    CEdit m_edit_hum3;
    CEdit m_edit_hum4;
    CEdit m_edit_hum5;
    CEdit m_edit_hum6;
    CEdit m_edit_hum7;
    CEdit m_edit_hum8;
    CEdit m_edit_hum9;
    CEdit m_edit_master_id;
    CEdit m_edit_error_sensors;
    CEdit m_edit_num_sensor;
    CEdit m_edit_rh1;
    CEdit m_edit_rh10;
    CEdit m_edit_rh2;
    CEdit m_edit_rh3;
    CEdit m_edit_rh4;
    CEdit m_edit_rh5;
    CEdit m_edit_rh6;
    CEdit m_edit_rh7;
    CEdit m_edit_rh8;
    CEdit m_edit_rh9;
    CEdit m_edit_time_left1;
    CEdit m_edit_time_left10;
    CEdit m_edit_time_left2;
    CEdit m_edit_time_left3;
    CEdit m_edit_time_left4;
    CEdit m_edit_time_left5;
    CEdit m_edit_time_left6;
    CEdit m_edit_time_left7;
    CEdit m_edit_time_left8;
    CEdit m_edit_time_left9;
    CEdit m_edit_temp1;
    CEdit m_edit_temp10;
    CEdit m_edit_temp2;
    CEdit m_edit_temp3;
    CEdit m_edit_temp4;
    CEdit m_edit_temp5;
    CEdit m_edit_temp6;
    CEdit m_edit_temp7;
    CEdit m_edit_temp8;
    CEdit m_edit_temp9;
    CEdit m_edit_time1;
    CEdit m_edit_time10;
    CEdit m_edit_time2;
    CEdit m_edit_time3;
    CEdit m_edit_time4;
    CEdit m_edit_time5;
    CEdit m_edit_time6;
    CEdit m_edit_time7;
    CEdit m_edit_time8;
    CEdit m_edit_time9;
    CMsflexgrid m_msflexgrid;


    int Time_left;
    int Hour;
    int Second;
    int Minute;
    CStatic m_cur_sensor;
    DECLARE_EVENTSINK_MAP()
    void ClickMsflexgridInput3();
    afx_msg void OnBnClickedButtonStart();
    virtual LRESULT WindowProc(UINT message, WPARAM wParam, LPARAM lParam);
    //	virtual BOOL DestroyWindow();
    afx_msg void OnDestroy();
    CStatic m_libel_times;
    afx_msg void OnBnClickedCheck1();
    afx_msg void OnBnClickedCheck2();
    afx_msg void OnClickedCheck3();
    afx_msg void OnClickedCheck4();
    afx_msg void OnClickedCheck5();
    afx_msg void OnClickedCheck6();
    afx_msg void OnClickedCheck7();
    afx_msg void OnClickedCheck8();
    afx_msg void OnClickedCheck9();
    afx_msg void OnClickedCheck10();
    //	afx_msg void OnKillfocusTemp1();
    afx_msg void OnSetfocusTemp1();
    //	afx_msg void OnKillfocusTemp10();
    afx_msg void OnSetfocusTemp10();
    //	afx_msg void OnKillfocusTemp2();
    afx_msg void OnSetfocusTemp2();
    //	afx_msg void OnKillfocusTemp3();
    afx_msg void OnSetfocusTemp3();
    //	afx_msg void OnKillfocusTemp4();
    afx_msg void OnSetfocusTemp4();
    //	afx_msg void OnKillfocusTemp5();
    afx_msg void OnSetfocusTemp5();
    //	afx_msg void OnKillfocusTemp6();
    afx_msg void OnSetfocusTemp6();
    //	afx_msg void OnKillfocusTemp7();
    afx_msg void OnSetfocusTemp7();
    //	afx_msg void OnKillfocusTemp8();
    afx_msg void OnSetfocusTemp8();
    //	afx_msg void OnKillfocusTemp9();
    afx_msg void OnSetfocusTemp9();

    void Set(int id,int value);
    virtual BOOL PreTranslateMessage(MSG* pMsg);
    afx_msg void OnSetfocusHum1();
    afx_msg void OnSetfocusHum10();
    //	afx_msg void OnChangeHum2();
    //	afx_msg void OnChangeHum3();
    //	afx_msg void OnChangeHum4();
    afx_msg void OnSetfocusHum2();
    afx_msg void OnSetfocusHum3();
    afx_msg void OnSetfocusHum4();
    afx_msg void OnSetfocusHum5();
    afx_msg void OnSetfocusHum6();
    afx_msg void OnSetfocusHum7();
    afx_msg void OnSetfocusHum8();
    afx_msg void OnSetfocusHum9();
    afx_msg void OnSetfocusTime1();
    afx_msg void OnSetfocusTime10();
    //	afx_msg void OnChangeTime2();
    afx_msg void OnSetfocusTime2();
    afx_msg void OnSetfocusTime3();
    afx_msg void OnSetfocusTime4();
    afx_msg void OnSetfocusTime5();
    afx_msg void OnSetfocusTime6();
    afx_msg void OnSetfocusTime7();
    afx_msg void OnSetfocusTime8();
    afx_msg void OnSetfocusTime9();
    afx_msg void OnBnClickedRefresh();
    void DblClickMsflexgridInput3();
    afx_msg void OnBnClickedBatchFlash();
    CButton m_CheckSkip;
    CButton m_batch_btn;
    afx_msg void OnBnClickedCalibrationPointReport();
    CButton m_StartBtn;
    CButton m_StopBtn;
    CButton m_ContinueBtn;
    afx_msg void OnBnClickedStart();
    afx_msg void OnBnClickedStop();
    afx_msg void OnBnClickedContinue();
    CStatic m_Static_TestStatus;

    afx_msg void OnEnSetfocusNumSensor();
    afx_msg void OnCbnDropdownComboUsbTesto();
    afx_msg void OnCbnSelchangeComboType();
    afx_msg void OnEnSetfocusCo21();
    afx_msg void OnSetfocusCo20();
    afx_msg void OnSetfocusCo22();
    afx_msg void OnSetfocusCo23();
    afx_msg void OnSetfocusCo24();
    afx_msg void OnSetfocusCo25();
    afx_msg void OnSetfocusCo26();
    afx_msg void OnSetfocusCo27();
    afx_msg void OnSetfocusCo28();
    afx_msg void OnSetfocusCo29();
    CComboBox m_combox_co2_setting;
    afx_msg void OnEnSetfocusEditTstataddress();
    afx_msg void OnEnSetfocusEditRegisterAddress();
    afx_msg void OnEnSetfocusEditCo2scale();
    afx_msg void OnEnSetfocusEditStabletimeChamber();
    afx_msg void OnEnSetfocusEditStabletimeSensor();
    afx_msg void OnEnSetfocusEditRtd1();
    afx_msg void OnEnSetfocusEditRtd2();

    afx_msg void OnEnSetfocusEditHumpoint();
    afx_msg void OnEnSetfocusEditCo2point();
    afx_msg void OnCbnSelchangeComboSettingCo2();
    void Fresh_CO2_Time();
    int m_current_Co2_sensorpoint;
    afx_msg void OnTimer(UINT_PTR nIDEvent);
    afx_msg void OnBnClickedCalibrationPointReport2();
    UINT m_frequence_seconds;

    afx_msg void OnBnClickedButtonTestoGraphic();
public:
    CDialog *g_Draw_dlg;
	afx_msg void OnBnClickedCheckRead();
};


