#pragma once
#define IDH_TOPIC_COVER_PAGE_TSTAT 6//T3000View
#define IDH_TOPIC_INPUTTABLE_TSTAT 24
#define IDH_TOPIC_OUTPUTTABLE_TSTAT 25
#define IDH_TOPIC_ONE_HEAT_ONE_COOL_SETTING 26
#define IDH_TOPIC_PID_HEAT_COOL_TSTAT 31//OutPutDlg
#define IDH_TOPIC_MANAGING_SCHEDULES_IN_T3000 35


